// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`GetDataTransformationProfile`](crate::operation::get_data_transformation_profile::builders::GetDataTransformationProfileFluentBuilder) operation.
    ///
    /// - The fluent builder is configurable:
    ///   - [`profile_id(impl Into<String>)`](crate::operation::get_data_transformation_profile::builders::GetDataTransformationProfileFluentBuilder::profile_id) / [`set_profile_id(Option<String>)`](crate::operation::get_data_transformation_profile::builders::GetDataTransformationProfileFluentBuilder::set_profile_id):<br>required: **true**<br><p>The unique identifier of the profile to retrieve.</p><br>
    ///   - [`profile_version(i32)`](crate::operation::get_data_transformation_profile::builders::GetDataTransformationProfileFluentBuilder::profile_version) / [`set_profile_version(Option<i32>)`](crate::operation::get_data_transformation_profile::builders::GetDataTransformationProfileFluentBuilder::set_profile_version):<br>required: **false**<br><p>The version number to retrieve. Specify 0 to retrieve the DRAFT version. If you omit this parameter, the service returns the latest published version.</p><br>
    /// - On success, responds with [`GetDataTransformationProfileOutput`](crate::operation::get_data_transformation_profile::GetDataTransformationProfileOutput) with field(s):
    ///   - [`profile_id(String)`](crate::operation::get_data_transformation_profile::GetDataTransformationProfileOutput::profile_id): <p>The unique identifier of the profile.</p>
    ///   - [`version(i32)`](crate::operation::get_data_transformation_profile::GetDataTransformationProfileOutput::version): <p>The version number of the retrieved profile.</p>
    ///   - [`source_format(SourceFormat)`](crate::operation::get_data_transformation_profile::GetDataTransformationProfileOutput::source_format): <p>The source data format of the profile.</p>
    ///   - [`target_format(TargetFormat)`](crate::operation::get_data_transformation_profile::GetDataTransformationProfileOutput::target_format): <p>The target output format of the profile.</p>
    ///   - [`profile_mapping(HashMap::<String, String>)`](crate::operation::get_data_transformation_profile::GetDataTransformationProfileOutput::profile_mapping): <p>The profile content as a map of file paths to content strings.</p>
    ///   - [`profile_name(Option<String>)`](crate::operation::get_data_transformation_profile::GetDataTransformationProfileOutput::profile_name): <p>The name of the profile.</p>
    ///   - [`profile_description(Option<String>)`](crate::operation::get_data_transformation_profile::GetDataTransformationProfileOutput::profile_description): <p>The description of the profile.</p>
    ///   - [`change_description(Option<String>)`](crate::operation::get_data_transformation_profile::GetDataTransformationProfileOutput::change_description): <p>A description of what changed in this version.</p>
    ///   - [`last_updated_at(DateTime)`](crate::operation::get_data_transformation_profile::GetDataTransformationProfileOutput::last_updated_at): <p>The timestamp when this version was last updated.</p>
    /// - On failure, responds with [`SdkError<GetDataTransformationProfileError>`](crate::operation::get_data_transformation_profile::GetDataTransformationProfileError)
    pub fn get_data_transformation_profile(
        &self,
    ) -> crate::operation::get_data_transformation_profile::builders::GetDataTransformationProfileFluentBuilder {
        crate::operation::get_data_transformation_profile::builders::GetDataTransformationProfileFluentBuilder::new(self.handle.clone())
    }
}
