// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`PublishDataTransformationProfile`](crate::operation::publish_data_transformation_profile::builders::PublishDataTransformationProfileFluentBuilder) operation.
    ///
    /// - The fluent builder is configurable:
    ///   - [`profile_id(impl Into<String>)`](crate::operation::publish_data_transformation_profile::builders::PublishDataTransformationProfileFluentBuilder::profile_id) / [`set_profile_id(Option<String>)`](crate::operation::publish_data_transformation_profile::builders::PublishDataTransformationProfileFluentBuilder::set_profile_id):<br>required: **true**<br><p>The unique identifier of the profile to publish.</p><br>
    ///   - [`source_format(SourceFormat)`](crate::operation::publish_data_transformation_profile::builders::PublishDataTransformationProfileFluentBuilder::source_format) / [`set_source_format(Option<SourceFormat>)`](crate::operation::publish_data_transformation_profile::builders::PublishDataTransformationProfileFluentBuilder::set_source_format):<br>required: **true**<br><p>The source data format of the profile.</p><br>
    ///   - [`from_existing_version(i32)`](crate::operation::publish_data_transformation_profile::builders::PublishDataTransformationProfileFluentBuilder::from_existing_version) / [`set_from_existing_version(Option<i32>)`](crate::operation::publish_data_transformation_profile::builders::PublishDataTransformationProfileFluentBuilder::set_from_existing_version):<br>required: **false**<br><p>The version number of a previously published version to republish as the new latest version. Use this parameter for rollback scenarios. If you omit this parameter, the service publishes the current DRAFT version.</p><br>
    ///   - [`change_description(impl Into<String>)`](crate::operation::publish_data_transformation_profile::builders::PublishDataTransformationProfileFluentBuilder::change_description) / [`set_change_description(Option<String>)`](crate::operation::publish_data_transformation_profile::builders::PublishDataTransformationProfileFluentBuilder::set_change_description):<br>required: **false**<br><p>A description of what changed or why this version is being published.</p><br>
    /// - On success, responds with [`PublishDataTransformationProfileOutput`](crate::operation::publish_data_transformation_profile::PublishDataTransformationProfileOutput) with field(s):
    ///   - [`profile_id(String)`](crate::operation::publish_data_transformation_profile::PublishDataTransformationProfileOutput::profile_id): <p>The unique identifier of the published profile.</p>
    ///   - [`version(i32)`](crate::operation::publish_data_transformation_profile::PublishDataTransformationProfileOutput::version): <p>The new version number that was created.</p>
    ///   - [`source_format(SourceFormat)`](crate::operation::publish_data_transformation_profile::PublishDataTransformationProfileOutput::source_format): <p>The source data format of the profile.</p>
    ///   - [`target_format(TargetFormat)`](crate::operation::publish_data_transformation_profile::PublishDataTransformationProfileOutput::target_format): <p>The target output format of the profile.</p>
    ///   - [`profile_name(Option<String>)`](crate::operation::publish_data_transformation_profile::PublishDataTransformationProfileOutput::profile_name): <p>The name of the published profile.</p>
    ///   - [`last_updated_at(DateTime)`](crate::operation::publish_data_transformation_profile::PublishDataTransformationProfileOutput::last_updated_at): <p>The timestamp when the profile was last updated.</p>
    /// - On failure, responds with [`SdkError<PublishDataTransformationProfileError>`](crate::operation::publish_data_transformation_profile::PublishDataTransformationProfileError)
    pub fn publish_data_transformation_profile(
        &self,
    ) -> crate::operation::publish_data_transformation_profile::builders::PublishDataTransformationProfileFluentBuilder {
        crate::operation::publish_data_transformation_profile::builders::PublishDataTransformationProfileFluentBuilder::new(self.handle.clone())
    }
}
