// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`UpdateProfileWithAgent`](crate::operation::update_profile_with_agent::builders::UpdateProfileWithAgentFluentBuilder) operation.
    ///
    /// - The fluent builder is configurable:
    ///   - [`profile_id(impl Into<String>)`](crate::operation::update_profile_with_agent::builders::UpdateProfileWithAgentFluentBuilder::profile_id) / [`set_profile_id(Option<String>)`](crate::operation::update_profile_with_agent::builders::UpdateProfileWithAgentFluentBuilder::set_profile_id):<br>required: **true**<br><p>The unique identifier of the profile to update via the agent.</p><br>
    ///   - [`source_format(SourceFormat)`](crate::operation::update_profile_with_agent::builders::UpdateProfileWithAgentFluentBuilder::source_format) / [`set_source_format(Option<SourceFormat>)`](crate::operation::update_profile_with_agent::builders::UpdateProfileWithAgentFluentBuilder::set_source_format):<br>required: **true**<br><p>The source data format for the transformation.</p><br>
    ///   - [`input_message(AgentInputMessage)`](crate::operation::update_profile_with_agent::builders::UpdateProfileWithAgentFluentBuilder::input_message) / [`set_input_message(Option<AgentInputMessage>)`](crate::operation::update_profile_with_agent::builders::UpdateProfileWithAgentFluentBuilder::set_input_message):<br>required: **true**<br><p>The message to send to the agent.</p><br>
    ///   - [`conversation_id(impl Into<String>)`](crate::operation::update_profile_with_agent::builders::UpdateProfileWithAgentFluentBuilder::conversation_id) / [`set_conversation_id(Option<String>)`](crate::operation::update_profile_with_agent::builders::UpdateProfileWithAgentFluentBuilder::set_conversation_id):<br>required: **false**<br><p>The conversation identifier for multi-turn interactions. Omit to start a new conversation.</p><br>
    /// - On success, responds with [`UpdateProfileWithAgentOutput`](crate::operation::update_profile_with_agent::UpdateProfileWithAgentOutput) with field(s):
    ///   - [`agent_response(Option<AgentOutputMessage>)`](crate::operation::update_profile_with_agent::UpdateProfileWithAgentOutput::agent_response): <p>The response message from the agent.</p>
    ///   - [`conversation_id(String)`](crate::operation::update_profile_with_agent::UpdateProfileWithAgentOutput::conversation_id): <p>The conversation identifier to use for follow-up messages in this conversation.</p>
    /// - On failure, responds with [`SdkError<UpdateProfileWithAgentError>`](crate::operation::update_profile_with_agent::UpdateProfileWithAgentError)
    pub fn update_profile_with_agent(&self) -> crate::operation::update_profile_with_agent::builders::UpdateProfileWithAgentFluentBuilder {
        crate::operation::update_profile_with_agent::builders::UpdateProfileWithAgentFluentBuilder::new(self.handle.clone())
    }
}
