// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>Contains configuration and status information for an Amazon Redshift Query Editor (QEV2) application that is registered with IAM Identity Center.</p>
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct Qev2IdcApplication {
    /// <p>The Amazon Resource Name (ARN) for the IAM Identity Center instance that the Amazon Redshift Query Editor (QEV2) application integrates with.</p>
    pub idc_instance_arn: ::std::option::Option<::std::string::String>,
    /// <p>The name of the Amazon Redshift Query Editor (QEV2) application in IAM Identity Center.</p>
    pub qev2_idc_application_name: ::std::option::Option<::std::string::String>,
    /// <p>The Amazon Resource Name (ARN) for the Amazon Redshift Query Editor (QEV2) application that integrates with IAM Identity Center.</p>
    pub qev2_idc_application_arn: ::std::option::Option<::std::string::String>,
    /// <p>The Amazon Resource Name (ARN) for the Amazon Redshift Query Editor (QEV2) IAM Identity Center managed application.</p>
    pub idc_managed_application_arn: ::std::option::Option<::std::string::String>,
    /// <p>The onboarding status for the Amazon Redshift Query Editor (QEV2) IAM Identity Center application.</p>
    pub idc_onboard_status: ::std::option::Option<::std::string::String>,
    /// <p>The display name for the Amazon Redshift Query Editor (QEV2) IAM Identity Center application. It appears in the console.</p>
    pub idc_display_name: ::std::option::Option<::std::string::String>,
    /// <p>A list of tags associated with the application. Tags are key-value pairs that you can use to organize and identify your resources.</p>
    pub tags: ::std::option::Option<::std::vec::Vec<crate::types::Tag>>,
}
impl Qev2IdcApplication {
    /// <p>The Amazon Resource Name (ARN) for the IAM Identity Center instance that the Amazon Redshift Query Editor (QEV2) application integrates with.</p>
    pub fn idc_instance_arn(&self) -> ::std::option::Option<&str> {
        self.idc_instance_arn.as_deref()
    }
    /// <p>The name of the Amazon Redshift Query Editor (QEV2) application in IAM Identity Center.</p>
    pub fn qev2_idc_application_name(&self) -> ::std::option::Option<&str> {
        self.qev2_idc_application_name.as_deref()
    }
    /// <p>The Amazon Resource Name (ARN) for the Amazon Redshift Query Editor (QEV2) application that integrates with IAM Identity Center.</p>
    pub fn qev2_idc_application_arn(&self) -> ::std::option::Option<&str> {
        self.qev2_idc_application_arn.as_deref()
    }
    /// <p>The Amazon Resource Name (ARN) for the Amazon Redshift Query Editor (QEV2) IAM Identity Center managed application.</p>
    pub fn idc_managed_application_arn(&self) -> ::std::option::Option<&str> {
        self.idc_managed_application_arn.as_deref()
    }
    /// <p>The onboarding status for the Amazon Redshift Query Editor (QEV2) IAM Identity Center application.</p>
    pub fn idc_onboard_status(&self) -> ::std::option::Option<&str> {
        self.idc_onboard_status.as_deref()
    }
    /// <p>The display name for the Amazon Redshift Query Editor (QEV2) IAM Identity Center application. It appears in the console.</p>
    pub fn idc_display_name(&self) -> ::std::option::Option<&str> {
        self.idc_display_name.as_deref()
    }
    /// <p>A list of tags associated with the application. Tags are key-value pairs that you can use to organize and identify your resources.</p>
    ///
    /// If no value was sent for this field, a default will be set. If you want to determine if no value was sent, use `.tags.is_none()`.
    pub fn tags(&self) -> &[crate::types::Tag] {
        self.tags.as_deref().unwrap_or_default()
    }
}
impl Qev2IdcApplication {
    /// Creates a new builder-style object to manufacture [`Qev2IdcApplication`](crate::types::Qev2IdcApplication).
    pub fn builder() -> crate::types::builders::Qev2IdcApplicationBuilder {
        crate::types::builders::Qev2IdcApplicationBuilder::default()
    }
}

/// A builder for [`Qev2IdcApplication`](crate::types::Qev2IdcApplication).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct Qev2IdcApplicationBuilder {
    pub(crate) idc_instance_arn: ::std::option::Option<::std::string::String>,
    pub(crate) qev2_idc_application_name: ::std::option::Option<::std::string::String>,
    pub(crate) qev2_idc_application_arn: ::std::option::Option<::std::string::String>,
    pub(crate) idc_managed_application_arn: ::std::option::Option<::std::string::String>,
    pub(crate) idc_onboard_status: ::std::option::Option<::std::string::String>,
    pub(crate) idc_display_name: ::std::option::Option<::std::string::String>,
    pub(crate) tags: ::std::option::Option<::std::vec::Vec<crate::types::Tag>>,
}
impl Qev2IdcApplicationBuilder {
    /// <p>The Amazon Resource Name (ARN) for the IAM Identity Center instance that the Amazon Redshift Query Editor (QEV2) application integrates with.</p>
    pub fn idc_instance_arn(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.idc_instance_arn = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The Amazon Resource Name (ARN) for the IAM Identity Center instance that the Amazon Redshift Query Editor (QEV2) application integrates with.</p>
    pub fn set_idc_instance_arn(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.idc_instance_arn = input;
        self
    }
    /// <p>The Amazon Resource Name (ARN) for the IAM Identity Center instance that the Amazon Redshift Query Editor (QEV2) application integrates with.</p>
    pub fn get_idc_instance_arn(&self) -> &::std::option::Option<::std::string::String> {
        &self.idc_instance_arn
    }
    /// <p>The name of the Amazon Redshift Query Editor (QEV2) application in IAM Identity Center.</p>
    pub fn qev2_idc_application_name(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.qev2_idc_application_name = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The name of the Amazon Redshift Query Editor (QEV2) application in IAM Identity Center.</p>
    pub fn set_qev2_idc_application_name(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.qev2_idc_application_name = input;
        self
    }
    /// <p>The name of the Amazon Redshift Query Editor (QEV2) application in IAM Identity Center.</p>
    pub fn get_qev2_idc_application_name(&self) -> &::std::option::Option<::std::string::String> {
        &self.qev2_idc_application_name
    }
    /// <p>The Amazon Resource Name (ARN) for the Amazon Redshift Query Editor (QEV2) application that integrates with IAM Identity Center.</p>
    pub fn qev2_idc_application_arn(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.qev2_idc_application_arn = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The Amazon Resource Name (ARN) for the Amazon Redshift Query Editor (QEV2) application that integrates with IAM Identity Center.</p>
    pub fn set_qev2_idc_application_arn(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.qev2_idc_application_arn = input;
        self
    }
    /// <p>The Amazon Resource Name (ARN) for the Amazon Redshift Query Editor (QEV2) application that integrates with IAM Identity Center.</p>
    pub fn get_qev2_idc_application_arn(&self) -> &::std::option::Option<::std::string::String> {
        &self.qev2_idc_application_arn
    }
    /// <p>The Amazon Resource Name (ARN) for the Amazon Redshift Query Editor (QEV2) IAM Identity Center managed application.</p>
    pub fn idc_managed_application_arn(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.idc_managed_application_arn = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The Amazon Resource Name (ARN) for the Amazon Redshift Query Editor (QEV2) IAM Identity Center managed application.</p>
    pub fn set_idc_managed_application_arn(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.idc_managed_application_arn = input;
        self
    }
    /// <p>The Amazon Resource Name (ARN) for the Amazon Redshift Query Editor (QEV2) IAM Identity Center managed application.</p>
    pub fn get_idc_managed_application_arn(&self) -> &::std::option::Option<::std::string::String> {
        &self.idc_managed_application_arn
    }
    /// <p>The onboarding status for the Amazon Redshift Query Editor (QEV2) IAM Identity Center application.</p>
    pub fn idc_onboard_status(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.idc_onboard_status = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The onboarding status for the Amazon Redshift Query Editor (QEV2) IAM Identity Center application.</p>
    pub fn set_idc_onboard_status(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.idc_onboard_status = input;
        self
    }
    /// <p>The onboarding status for the Amazon Redshift Query Editor (QEV2) IAM Identity Center application.</p>
    pub fn get_idc_onboard_status(&self) -> &::std::option::Option<::std::string::String> {
        &self.idc_onboard_status
    }
    /// <p>The display name for the Amazon Redshift Query Editor (QEV2) IAM Identity Center application. It appears in the console.</p>
    pub fn idc_display_name(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.idc_display_name = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The display name for the Amazon Redshift Query Editor (QEV2) IAM Identity Center application. It appears in the console.</p>
    pub fn set_idc_display_name(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.idc_display_name = input;
        self
    }
    /// <p>The display name for the Amazon Redshift Query Editor (QEV2) IAM Identity Center application. It appears in the console.</p>
    pub fn get_idc_display_name(&self) -> &::std::option::Option<::std::string::String> {
        &self.idc_display_name
    }
    /// Appends an item to `tags`.
    ///
    /// To override the contents of this collection use [`set_tags`](Self::set_tags).
    ///
    /// <p>A list of tags associated with the application. Tags are key-value pairs that you can use to organize and identify your resources.</p>
    pub fn tags(mut self, input: crate::types::Tag) -> Self {
        let mut v = self.tags.unwrap_or_default();
        v.push(input);
        self.tags = ::std::option::Option::Some(v);
        self
    }
    /// <p>A list of tags associated with the application. Tags are key-value pairs that you can use to organize and identify your resources.</p>
    pub fn set_tags(mut self, input: ::std::option::Option<::std::vec::Vec<crate::types::Tag>>) -> Self {
        self.tags = input;
        self
    }
    /// <p>A list of tags associated with the application. Tags are key-value pairs that you can use to organize and identify your resources.</p>
    pub fn get_tags(&self) -> &::std::option::Option<::std::vec::Vec<crate::types::Tag>> {
        &self.tags
    }
    /// Consumes the builder and constructs a [`Qev2IdcApplication`](crate::types::Qev2IdcApplication).
    pub fn build(self) -> crate::types::Qev2IdcApplication {
        crate::types::Qev2IdcApplication {
            idc_instance_arn: self.idc_instance_arn,
            qev2_idc_application_name: self.qev2_idc_application_name,
            qev2_idc_application_arn: self.qev2_idc_application_arn,
            idc_managed_application_arn: self.idc_managed_application_arn,
            idc_onboard_status: self.idc_onboard_status,
            idc_display_name: self.idc_display_name,
            tags: self.tags,
        }
    }
}
