// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`RegisterComputeNodeGroupInstance`](crate::operation::register_compute_node_group_instance::builders::RegisterComputeNodeGroupInstanceFluentBuilder) operation.
    ///
    /// - The fluent builder is configurable:
    ///   - [`cluster_identifier(impl Into<String>)`](crate::operation::register_compute_node_group_instance::builders::RegisterComputeNodeGroupInstanceFluentBuilder::cluster_identifier) / [`set_cluster_identifier(Option<String>)`](crate::operation::register_compute_node_group_instance::builders::RegisterComputeNodeGroupInstanceFluentBuilder::set_cluster_identifier):<br>required: **true**<br><p>The name or ID of the cluster to register the compute node group instance in.</p><br>
    ///   - [`bootstrap_id(impl Into<String>)`](crate::operation::register_compute_node_group_instance::builders::RegisterComputeNodeGroupInstanceFluentBuilder::bootstrap_id) / [`set_bootstrap_id(Option<String>)`](crate::operation::register_compute_node_group_instance::builders::RegisterComputeNodeGroupInstanceFluentBuilder::set_bootstrap_id):<br>required: **true**<br><p>The client-generated token to allow for retries.</p><br>
    /// - On success, responds with [`RegisterComputeNodeGroupInstanceOutput`](crate::operation::register_compute_node_group_instance::RegisterComputeNodeGroupInstanceOutput) with field(s):
    ///   - [`node_id(String)`](crate::operation::register_compute_node_group_instance::RegisterComputeNodeGroupInstanceOutput::node_id): <p>The scheduler node ID for this instance.</p>
    ///   - [`shared_secret(String)`](crate::operation::register_compute_node_group_instance::RegisterComputeNodeGroupInstanceOutput::shared_secret): <p>For the Slurm scheduler, this is the shared Munge key the scheduler uses to authenticate compute node group instances.</p>
    ///   - [`endpoints(Vec::<Endpoint>)`](crate::operation::register_compute_node_group_instance::RegisterComputeNodeGroupInstanceOutput::endpoints): <p>The list of endpoints available for interaction with the scheduler.</p>
    ///   - [`cluster_name(Option<String>)`](crate::operation::register_compute_node_group_instance::RegisterComputeNodeGroupInstanceOutput::cluster_name): <p>The name of the cluster that the compute node registered into.</p>
    ///   - [`compute_node_group_id(Option<String>)`](crate::operation::register_compute_node_group_instance::RegisterComputeNodeGroupInstanceOutput::compute_node_group_id): <p>The ID of the compute node group that the compute node registered into.</p>
    ///   - [`compute_node_group_name(Option<String>)`](crate::operation::register_compute_node_group_instance::RegisterComputeNodeGroupInstanceOutput::compute_node_group_name): <p>The name of the compute node group that the compute node registered into.</p>
    ///   - [`node_lifecycle_actions(Option<NodeLifecycleActions>)`](crate::operation::register_compute_node_group_instance::RegisterComputeNodeGroupInstanceOutput::node_lifecycle_actions): <p>The node lifecycle actions configured for the node group, including scripts to run when a compute node finishes bootstrapping or becomes ready to accept jobs.</p>
    /// - On failure, responds with [`SdkError<RegisterComputeNodeGroupInstanceError>`](crate::operation::register_compute_node_group_instance::RegisterComputeNodeGroupInstanceError)
    pub fn register_compute_node_group_instance(
        &self,
    ) -> crate::operation::register_compute_node_group_instance::builders::RegisterComputeNodeGroupInstanceFluentBuilder {
        crate::operation::register_compute_node_group_instance::builders::RegisterComputeNodeGroupInstanceFluentBuilder::new(self.handle.clone())
    }
}
