// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`PutFeedPolicy`](crate::operation::put_feed_policy::builders::PutFeedPolicyFluentBuilder) operation.
    ///
    /// - The fluent builder is configurable:
    ///   - [`id(impl Into<String>)`](crate::operation::put_feed_policy::builders::PutFeedPolicyFluentBuilder::id) / [`set_id(Option<String>)`](crate::operation::put_feed_policy::builders::PutFeedPolicyFluentBuilder::set_id):<br>required: **true**<br><p>The ID of the feed to attach the policy to.</p><br>
    ///   - [`policy(impl Into<String>)`](crate::operation::put_feed_policy::builders::PutFeedPolicyFluentBuilder::policy) / [`set_policy(Option<String>)`](crate::operation::put_feed_policy::builders::PutFeedPolicyFluentBuilder::set_policy):<br>required: **true**<br><p>The resource-based policy document to attach to the feed.</p><br>
    /// - On success, responds with [`PutFeedPolicyOutput`](crate::operation::put_feed_policy::PutFeedPolicyOutput)
    /// - On failure, responds with [`SdkError<PutFeedPolicyError>`](crate::operation::put_feed_policy::PutFeedPolicyError)
    pub fn put_feed_policy(&self) -> crate::operation::put_feed_policy::builders::PutFeedPolicyFluentBuilder {
        crate::operation::put_feed_policy::builders::PutFeedPolicyFluentBuilder::new(self.handle.clone())
    }
}
