// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_get_estimated_water_allocation_input_input(
    object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::operation::get_estimated_water_allocation::GetEstimatedWaterAllocationInput,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    if let Some(var_1) = &input.allocation_types {
        let mut array_2 = object.key("AllocationTypes").start_array();
        for item_3 in var_1 {
            {
                array_2.value().string(item_3.as_str());
            }
        }
        array_2.finish();
    }
    if let Some(var_4) = &input.filter_by {
        #[allow(unused_mut)]
        let mut object_5 = object.key("FilterBy").start_object();
        crate::protocol_serde::shape_filter_expression::ser_filter_expression(&mut object_5, var_4)?;
        object_5.finish();
    }
    if let Some(var_6) = &input.granularity {
        object.key("Granularity").string(var_6.as_str());
    }
    if let Some(var_7) = &input.group_by {
        let mut array_8 = object.key("GroupBy").start_array();
        for item_9 in var_7 {
            {
                array_8.value().string(item_9.as_str());
            }
        }
        array_8.finish();
    }
    if let Some(var_10) = &input.max_results {
        object.key("MaxResults").number(
            #[allow(clippy::useless_conversion)]
            ::aws_smithy_types::Number::NegInt((*var_10).into()),
        );
    }
    if let Some(var_11) = &input.next_token {
        object.key("NextToken").string(var_11.as_str());
    }
    if let Some(var_12) = &input.time_period {
        #[allow(unused_mut)]
        let mut object_13 = object.key("TimePeriod").start_object();
        crate::protocol_serde::shape_time_period::ser_time_period(&mut object_13, var_12)?;
        object_13.finish();
    }
    Ok(())
}
