// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>The payload of a test run source event. Exactly one member is set.</p>
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub enum TestRunSourceEventDetail {
    /// <p>A CloudWatch alarm state change.</p>
    AlarmStateChange(crate::types::AlarmStateChangeDetail),
    /// <p>An error that prevented event collection from the source.</p>
    Error(crate::types::TestRunSourceEventError),
    /// The `Unknown` variant represents cases where new union variant was received. Consider upgrading the SDK to the latest available version.
    /// An unknown enum variant
    ///
    /// _Note: If you encounter this error, consider upgrading your SDK to the latest version._
    /// The `Unknown` variant represents cases where the server sent a value that wasn't recognized
    /// by the client. This can happen when the server adds new functionality, but the client has not been updated.
    /// To investigate this, consider turning on debug logging to print the raw HTTP response.
    #[non_exhaustive]
    Unknown,
}
impl TestRunSourceEventDetail {
    /// Tries to convert the enum instance into [`AlarmStateChange`](crate::types::TestRunSourceEventDetail::AlarmStateChange), extracting the inner [`AlarmStateChangeDetail`](crate::types::AlarmStateChangeDetail).
    /// Returns `Err(&Self)` if it can't be converted.
    pub fn as_alarm_state_change(&self) -> ::std::result::Result<&crate::types::AlarmStateChangeDetail, &Self> {
        if let TestRunSourceEventDetail::AlarmStateChange(val) = &self {
            ::std::result::Result::Ok(val)
        } else {
            ::std::result::Result::Err(self)
        }
    }
    /// Returns true if this is a [`AlarmStateChange`](crate::types::TestRunSourceEventDetail::AlarmStateChange).
    pub fn is_alarm_state_change(&self) -> bool {
        self.as_alarm_state_change().is_ok()
    }
    /// Tries to convert the enum instance into [`Error`](crate::types::TestRunSourceEventDetail::Error), extracting the inner [`TestRunSourceEventError`](crate::types::TestRunSourceEventError).
    /// Returns `Err(&Self)` if it can't be converted.
    pub fn as_error(&self) -> ::std::result::Result<&crate::types::TestRunSourceEventError, &Self> {
        if let TestRunSourceEventDetail::Error(val) = &self {
            ::std::result::Result::Ok(val)
        } else {
            ::std::result::Result::Err(self)
        }
    }
    /// Returns true if this is a [`Error`](crate::types::TestRunSourceEventDetail::Error).
    pub fn is_error(&self) -> bool {
        self.as_error().is_ok()
    }
    /// Returns true if the enum instance is the `Unknown` variant.
    pub fn is_unknown(&self) -> bool {
        matches!(self, Self::Unknown)
    }
}
