// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct GetEstimatedCarbonEmissionsInput {
    /// <p>The date range for fetching estimated carbon emissions. The range must include the start date of a month for that month's data to be included in the response.</p>
    pub time_period: ::std::option::Option<crate::types::TimePeriod>,
    /// <p>The dimensions available for grouping estimated carbon emissions.</p>
    pub group_by: ::std::option::Option<::std::vec::Vec<crate::types::Dimension>>,
    /// <p>The criteria for filtering estimated carbon emissions. To determine which dimensions are available to be filtered by, you can first call <code>GetEstimatedCarbonEmissionsDimensionValues</code></p>
    pub filter_by: ::std::option::Option<crate::types::FilterExpression>,
    /// <p>The emission types to include in the results. If absent, returns <code>TOTAL_LBM_CARBON_EMISSIONS</code> and <code>TOTAL_MBM_CARBON_EMISSIONS</code> emissions types.</p>
    pub emissions_types: ::std::option::Option<::std::vec::Vec<crate::types::EmissionsType>>,
    /// <p>The time granularity for the results. If absent, uses <code>MONTHLY</code> time granularity. The smallest supported granularity for carbon emissions is <code>MONTHLY</code>.</p>
    /// <p>If requesting partial time periods, data will be returned based on the smallest supported granularity. For example, requesting <code>2025-04-01T00:00:00Z</code> to <code>2026-04-01T00:00:00Z</code> with <code>YEARLY_CALENDAR</code> granularity will return the last 9 months for 2025 and the first 3 months of 2026.</p>
    pub granularity: ::std::option::Option<crate::types::TimeGranularity>,
    /// <p>Configuration for fiscal year calculations when using <code>YEARLY_FISCAL</code> or <code>QUARTERLY_FISCAL</code> granularity.</p>
    pub granularity_configuration: ::std::option::Option<crate::types::GranularityConfiguration>,
    /// <p>The maximum number of results to return in a single call. Default is 1000.</p>
    pub max_results: ::std::option::Option<i32>,
    /// <p>The pagination token specifying which page of results to return in the response. If no token is provided, the default page is the first page.</p>
    pub next_token: ::std::option::Option<::std::string::String>,
}
impl GetEstimatedCarbonEmissionsInput {
    /// <p>The date range for fetching estimated carbon emissions. The range must include the start date of a month for that month's data to be included in the response.</p>
    pub fn time_period(&self) -> ::std::option::Option<&crate::types::TimePeriod> {
        self.time_period.as_ref()
    }
    /// <p>The dimensions available for grouping estimated carbon emissions.</p>
    ///
    /// If no value was sent for this field, a default will be set. If you want to determine if no value was sent, use `.group_by.is_none()`.
    pub fn group_by(&self) -> &[crate::types::Dimension] {
        self.group_by.as_deref().unwrap_or_default()
    }
    /// <p>The criteria for filtering estimated carbon emissions. To determine which dimensions are available to be filtered by, you can first call <code>GetEstimatedCarbonEmissionsDimensionValues</code></p>
    pub fn filter_by(&self) -> ::std::option::Option<&crate::types::FilterExpression> {
        self.filter_by.as_ref()
    }
    /// <p>The emission types to include in the results. If absent, returns <code>TOTAL_LBM_CARBON_EMISSIONS</code> and <code>TOTAL_MBM_CARBON_EMISSIONS</code> emissions types.</p>
    ///
    /// If no value was sent for this field, a default will be set. If you want to determine if no value was sent, use `.emissions_types.is_none()`.
    pub fn emissions_types(&self) -> &[crate::types::EmissionsType] {
        self.emissions_types.as_deref().unwrap_or_default()
    }
    /// <p>The time granularity for the results. If absent, uses <code>MONTHLY</code> time granularity. The smallest supported granularity for carbon emissions is <code>MONTHLY</code>.</p>
    /// <p>If requesting partial time periods, data will be returned based on the smallest supported granularity. For example, requesting <code>2025-04-01T00:00:00Z</code> to <code>2026-04-01T00:00:00Z</code> with <code>YEARLY_CALENDAR</code> granularity will return the last 9 months for 2025 and the first 3 months of 2026.</p>
    pub fn granularity(&self) -> ::std::option::Option<&crate::types::TimeGranularity> {
        self.granularity.as_ref()
    }
    /// <p>Configuration for fiscal year calculations when using <code>YEARLY_FISCAL</code> or <code>QUARTERLY_FISCAL</code> granularity.</p>
    pub fn granularity_configuration(&self) -> ::std::option::Option<&crate::types::GranularityConfiguration> {
        self.granularity_configuration.as_ref()
    }
    /// <p>The maximum number of results to return in a single call. Default is 1000.</p>
    pub fn max_results(&self) -> ::std::option::Option<i32> {
        self.max_results
    }
    /// <p>The pagination token specifying which page of results to return in the response. If no token is provided, the default page is the first page.</p>
    pub fn next_token(&self) -> ::std::option::Option<&str> {
        self.next_token.as_deref()
    }
}
impl GetEstimatedCarbonEmissionsInput {
    /// Creates a new builder-style object to manufacture [`GetEstimatedCarbonEmissionsInput`](crate::operation::get_estimated_carbon_emissions::GetEstimatedCarbonEmissionsInput).
    pub fn builder() -> crate::operation::get_estimated_carbon_emissions::builders::GetEstimatedCarbonEmissionsInputBuilder {
        crate::operation::get_estimated_carbon_emissions::builders::GetEstimatedCarbonEmissionsInputBuilder::default()
    }
}

/// A builder for [`GetEstimatedCarbonEmissionsInput`](crate::operation::get_estimated_carbon_emissions::GetEstimatedCarbonEmissionsInput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct GetEstimatedCarbonEmissionsInputBuilder {
    pub(crate) time_period: ::std::option::Option<crate::types::TimePeriod>,
    pub(crate) group_by: ::std::option::Option<::std::vec::Vec<crate::types::Dimension>>,
    pub(crate) filter_by: ::std::option::Option<crate::types::FilterExpression>,
    pub(crate) emissions_types: ::std::option::Option<::std::vec::Vec<crate::types::EmissionsType>>,
    pub(crate) granularity: ::std::option::Option<crate::types::TimeGranularity>,
    pub(crate) granularity_configuration: ::std::option::Option<crate::types::GranularityConfiguration>,
    pub(crate) max_results: ::std::option::Option<i32>,
    pub(crate) next_token: ::std::option::Option<::std::string::String>,
}
impl GetEstimatedCarbonEmissionsInputBuilder {
    /// <p>The date range for fetching estimated carbon emissions. The range must include the start date of a month for that month's data to be included in the response.</p>
    /// This field is required.
    pub fn time_period(mut self, input: crate::types::TimePeriod) -> Self {
        self.time_period = ::std::option::Option::Some(input);
        self
    }
    /// <p>The date range for fetching estimated carbon emissions. The range must include the start date of a month for that month's data to be included in the response.</p>
    pub fn set_time_period(mut self, input: ::std::option::Option<crate::types::TimePeriod>) -> Self {
        self.time_period = input;
        self
    }
    /// <p>The date range for fetching estimated carbon emissions. The range must include the start date of a month for that month's data to be included in the response.</p>
    pub fn get_time_period(&self) -> &::std::option::Option<crate::types::TimePeriod> {
        &self.time_period
    }
    /// Appends an item to `group_by`.
    ///
    /// To override the contents of this collection use [`set_group_by`](Self::set_group_by).
    ///
    /// <p>The dimensions available for grouping estimated carbon emissions.</p>
    pub fn group_by(mut self, input: crate::types::Dimension) -> Self {
        let mut v = self.group_by.unwrap_or_default();
        v.push(input);
        self.group_by = ::std::option::Option::Some(v);
        self
    }
    /// <p>The dimensions available for grouping estimated carbon emissions.</p>
    pub fn set_group_by(mut self, input: ::std::option::Option<::std::vec::Vec<crate::types::Dimension>>) -> Self {
        self.group_by = input;
        self
    }
    /// <p>The dimensions available for grouping estimated carbon emissions.</p>
    pub fn get_group_by(&self) -> &::std::option::Option<::std::vec::Vec<crate::types::Dimension>> {
        &self.group_by
    }
    /// <p>The criteria for filtering estimated carbon emissions. To determine which dimensions are available to be filtered by, you can first call <code>GetEstimatedCarbonEmissionsDimensionValues</code></p>
    pub fn filter_by(mut self, input: crate::types::FilterExpression) -> Self {
        self.filter_by = ::std::option::Option::Some(input);
        self
    }
    /// <p>The criteria for filtering estimated carbon emissions. To determine which dimensions are available to be filtered by, you can first call <code>GetEstimatedCarbonEmissionsDimensionValues</code></p>
    pub fn set_filter_by(mut self, input: ::std::option::Option<crate::types::FilterExpression>) -> Self {
        self.filter_by = input;
        self
    }
    /// <p>The criteria for filtering estimated carbon emissions. To determine which dimensions are available to be filtered by, you can first call <code>GetEstimatedCarbonEmissionsDimensionValues</code></p>
    pub fn get_filter_by(&self) -> &::std::option::Option<crate::types::FilterExpression> {
        &self.filter_by
    }
    /// Appends an item to `emissions_types`.
    ///
    /// To override the contents of this collection use [`set_emissions_types`](Self::set_emissions_types).
    ///
    /// <p>The emission types to include in the results. If absent, returns <code>TOTAL_LBM_CARBON_EMISSIONS</code> and <code>TOTAL_MBM_CARBON_EMISSIONS</code> emissions types.</p>
    pub fn emissions_types(mut self, input: crate::types::EmissionsType) -> Self {
        let mut v = self.emissions_types.unwrap_or_default();
        v.push(input);
        self.emissions_types = ::std::option::Option::Some(v);
        self
    }
    /// <p>The emission types to include in the results. If absent, returns <code>TOTAL_LBM_CARBON_EMISSIONS</code> and <code>TOTAL_MBM_CARBON_EMISSIONS</code> emissions types.</p>
    pub fn set_emissions_types(mut self, input: ::std::option::Option<::std::vec::Vec<crate::types::EmissionsType>>) -> Self {
        self.emissions_types = input;
        self
    }
    /// <p>The emission types to include in the results. If absent, returns <code>TOTAL_LBM_CARBON_EMISSIONS</code> and <code>TOTAL_MBM_CARBON_EMISSIONS</code> emissions types.</p>
    pub fn get_emissions_types(&self) -> &::std::option::Option<::std::vec::Vec<crate::types::EmissionsType>> {
        &self.emissions_types
    }
    /// <p>The time granularity for the results. If absent, uses <code>MONTHLY</code> time granularity. The smallest supported granularity for carbon emissions is <code>MONTHLY</code>.</p>
    /// <p>If requesting partial time periods, data will be returned based on the smallest supported granularity. For example, requesting <code>2025-04-01T00:00:00Z</code> to <code>2026-04-01T00:00:00Z</code> with <code>YEARLY_CALENDAR</code> granularity will return the last 9 months for 2025 and the first 3 months of 2026.</p>
    pub fn granularity(mut self, input: crate::types::TimeGranularity) -> Self {
        self.granularity = ::std::option::Option::Some(input);
        self
    }
    /// <p>The time granularity for the results. If absent, uses <code>MONTHLY</code> time granularity. The smallest supported granularity for carbon emissions is <code>MONTHLY</code>.</p>
    /// <p>If requesting partial time periods, data will be returned based on the smallest supported granularity. For example, requesting <code>2025-04-01T00:00:00Z</code> to <code>2026-04-01T00:00:00Z</code> with <code>YEARLY_CALENDAR</code> granularity will return the last 9 months for 2025 and the first 3 months of 2026.</p>
    pub fn set_granularity(mut self, input: ::std::option::Option<crate::types::TimeGranularity>) -> Self {
        self.granularity = input;
        self
    }
    /// <p>The time granularity for the results. If absent, uses <code>MONTHLY</code> time granularity. The smallest supported granularity for carbon emissions is <code>MONTHLY</code>.</p>
    /// <p>If requesting partial time periods, data will be returned based on the smallest supported granularity. For example, requesting <code>2025-04-01T00:00:00Z</code> to <code>2026-04-01T00:00:00Z</code> with <code>YEARLY_CALENDAR</code> granularity will return the last 9 months for 2025 and the first 3 months of 2026.</p>
    pub fn get_granularity(&self) -> &::std::option::Option<crate::types::TimeGranularity> {
        &self.granularity
    }
    /// <p>Configuration for fiscal year calculations when using <code>YEARLY_FISCAL</code> or <code>QUARTERLY_FISCAL</code> granularity.</p>
    pub fn granularity_configuration(mut self, input: crate::types::GranularityConfiguration) -> Self {
        self.granularity_configuration = ::std::option::Option::Some(input);
        self
    }
    /// <p>Configuration for fiscal year calculations when using <code>YEARLY_FISCAL</code> or <code>QUARTERLY_FISCAL</code> granularity.</p>
    pub fn set_granularity_configuration(mut self, input: ::std::option::Option<crate::types::GranularityConfiguration>) -> Self {
        self.granularity_configuration = input;
        self
    }
    /// <p>Configuration for fiscal year calculations when using <code>YEARLY_FISCAL</code> or <code>QUARTERLY_FISCAL</code> granularity.</p>
    pub fn get_granularity_configuration(&self) -> &::std::option::Option<crate::types::GranularityConfiguration> {
        &self.granularity_configuration
    }
    /// <p>The maximum number of results to return in a single call. Default is 1000.</p>
    pub fn max_results(mut self, input: i32) -> Self {
        self.max_results = ::std::option::Option::Some(input);
        self
    }
    /// <p>The maximum number of results to return in a single call. Default is 1000.</p>
    pub fn set_max_results(mut self, input: ::std::option::Option<i32>) -> Self {
        self.max_results = input;
        self
    }
    /// <p>The maximum number of results to return in a single call. Default is 1000.</p>
    pub fn get_max_results(&self) -> &::std::option::Option<i32> {
        &self.max_results
    }
    /// <p>The pagination token specifying which page of results to return in the response. If no token is provided, the default page is the first page.</p>
    pub fn next_token(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.next_token = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The pagination token specifying which page of results to return in the response. If no token is provided, the default page is the first page.</p>
    pub fn set_next_token(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.next_token = input;
        self
    }
    /// <p>The pagination token specifying which page of results to return in the response. If no token is provided, the default page is the first page.</p>
    pub fn get_next_token(&self) -> &::std::option::Option<::std::string::String> {
        &self.next_token
    }
    /// Consumes the builder and constructs a [`GetEstimatedCarbonEmissionsInput`](crate::operation::get_estimated_carbon_emissions::GetEstimatedCarbonEmissionsInput).
    pub fn build(
        self,
    ) -> ::std::result::Result<
        crate::operation::get_estimated_carbon_emissions::GetEstimatedCarbonEmissionsInput,
        ::aws_smithy_types::error::operation::BuildError,
    > {
        ::std::result::Result::Ok(crate::operation::get_estimated_carbon_emissions::GetEstimatedCarbonEmissionsInput {
            time_period: self.time_period,
            group_by: self.group_by,
            filter_by: self.filter_by,
            emissions_types: self.emissions_types,
            granularity: self.granularity,
            granularity_configuration: self.granularity_configuration,
            max_results: self.max_results,
            next_token: self.next_token,
        })
    }
}
