// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub use crate::operation::get_estimated_carbon_emissions::_get_estimated_carbon_emissions_input::GetEstimatedCarbonEmissionsInputBuilder;

pub use crate::operation::get_estimated_carbon_emissions::_get_estimated_carbon_emissions_output::GetEstimatedCarbonEmissionsOutputBuilder;

impl crate::operation::get_estimated_carbon_emissions::builders::GetEstimatedCarbonEmissionsInputBuilder {
    /// Sends a request with this input using the given client.
    pub async fn send_with(
        self,
        client: &crate::Client,
    ) -> ::std::result::Result<
        crate::operation::get_estimated_carbon_emissions::GetEstimatedCarbonEmissionsOutput,
        ::aws_smithy_runtime_api::client::result::SdkError<
            crate::operation::get_estimated_carbon_emissions::GetEstimatedCarbonEmissionsError,
            ::aws_smithy_runtime_api::client::orchestrator::HttpResponse,
        >,
    > {
        let mut fluent_builder = client.get_estimated_carbon_emissions();
        fluent_builder.inner = self;
        fluent_builder.send().await
    }
}
/// Fluent builder constructing a request to `GetEstimatedCarbonEmissions`.
///
/// <p>Returns estimated carbon emission values based on customer grouping and filtering parameters. We recommend using pagination to ensure that the operation returns quickly and successfully.</p>
#[derive(::std::clone::Clone, ::std::fmt::Debug)]
pub struct GetEstimatedCarbonEmissionsFluentBuilder {
    handle: ::std::sync::Arc<crate::client::Handle>,
    inner: crate::operation::get_estimated_carbon_emissions::builders::GetEstimatedCarbonEmissionsInputBuilder,
    config_override: ::std::option::Option<crate::config::Builder>,
}
impl
    crate::client::customize::internal::CustomizableSend<
        crate::operation::get_estimated_carbon_emissions::GetEstimatedCarbonEmissionsOutput,
        crate::operation::get_estimated_carbon_emissions::GetEstimatedCarbonEmissionsError,
    > for GetEstimatedCarbonEmissionsFluentBuilder
{
    fn send(
        self,
        config_override: crate::config::Builder,
    ) -> crate::client::customize::internal::BoxFuture<
        crate::client::customize::internal::SendResult<
            crate::operation::get_estimated_carbon_emissions::GetEstimatedCarbonEmissionsOutput,
            crate::operation::get_estimated_carbon_emissions::GetEstimatedCarbonEmissionsError,
        >,
    > {
        ::std::boxed::Box::pin(async move { self.config_override(config_override).send().await })
    }
}
impl GetEstimatedCarbonEmissionsFluentBuilder {
    /// Creates a new `GetEstimatedCarbonEmissionsFluentBuilder`.
    pub(crate) fn new(handle: ::std::sync::Arc<crate::client::Handle>) -> Self {
        Self {
            handle,
            inner: ::std::default::Default::default(),
            config_override: ::std::option::Option::None,
        }
    }
    /// Access the GetEstimatedCarbonEmissions as a reference.
    pub fn as_input(&self) -> &crate::operation::get_estimated_carbon_emissions::builders::GetEstimatedCarbonEmissionsInputBuilder {
        &self.inner
    }
    /// Sends the request and returns the response.
    ///
    /// If an error occurs, an `SdkError` will be returned with additional details that
    /// can be matched against.
    ///
    /// By default, any retryable failures will be retried twice. Retry behavior
    /// is configurable with the [RetryConfig](aws_smithy_types::retry::RetryConfig), which can be
    /// set when configuring the client.
    pub async fn send(
        self,
    ) -> ::std::result::Result<
        crate::operation::get_estimated_carbon_emissions::GetEstimatedCarbonEmissionsOutput,
        ::aws_smithy_runtime_api::client::result::SdkError<
            crate::operation::get_estimated_carbon_emissions::GetEstimatedCarbonEmissionsError,
            ::aws_smithy_runtime_api::client::orchestrator::HttpResponse,
        >,
    > {
        let input = self
            .inner
            .build()
            .map_err(::aws_smithy_runtime_api::client::result::SdkError::construction_failure)?;
        let runtime_plugins = crate::operation::get_estimated_carbon_emissions::GetEstimatedCarbonEmissions::operation_runtime_plugins(
            self.handle.runtime_plugins.clone(),
            &self.handle.conf,
            self.config_override,
        );
        crate::operation::get_estimated_carbon_emissions::GetEstimatedCarbonEmissions::orchestrate(&runtime_plugins, input).await
    }

    /// Consumes this builder, creating a customizable operation that can be modified before being sent.
    pub fn customize(
        self,
    ) -> crate::client::customize::CustomizableOperation<
        crate::operation::get_estimated_carbon_emissions::GetEstimatedCarbonEmissionsOutput,
        crate::operation::get_estimated_carbon_emissions::GetEstimatedCarbonEmissionsError,
        Self,
    > {
        crate::client::customize::CustomizableOperation::new(self)
    }
    pub(crate) fn config_override(mut self, config_override: impl ::std::convert::Into<crate::config::Builder>) -> Self {
        self.set_config_override(::std::option::Option::Some(config_override.into()));
        self
    }

    pub(crate) fn set_config_override(&mut self, config_override: ::std::option::Option<crate::config::Builder>) -> &mut Self {
        self.config_override = config_override;
        self
    }
    /// Create a paginator for this request
    ///
    /// Paginators are used by calling [`send().await`](crate::operation::get_estimated_carbon_emissions::paginator::GetEstimatedCarbonEmissionsPaginator::send) which returns a [`PaginationStream`](aws_smithy_async::future::pagination_stream::PaginationStream).
    pub fn into_paginator(self) -> crate::operation::get_estimated_carbon_emissions::paginator::GetEstimatedCarbonEmissionsPaginator {
        crate::operation::get_estimated_carbon_emissions::paginator::GetEstimatedCarbonEmissionsPaginator::new(self.handle, self.inner)
    }
    /// <p>The date range for fetching estimated carbon emissions. The range must include the start date of a month for that month's data to be included in the response.</p>
    pub fn time_period(mut self, input: crate::types::TimePeriod) -> Self {
        self.inner = self.inner.time_period(input);
        self
    }
    /// <p>The date range for fetching estimated carbon emissions. The range must include the start date of a month for that month's data to be included in the response.</p>
    pub fn set_time_period(mut self, input: ::std::option::Option<crate::types::TimePeriod>) -> Self {
        self.inner = self.inner.set_time_period(input);
        self
    }
    /// <p>The date range for fetching estimated carbon emissions. The range must include the start date of a month for that month's data to be included in the response.</p>
    pub fn get_time_period(&self) -> &::std::option::Option<crate::types::TimePeriod> {
        self.inner.get_time_period()
    }
    ///
    /// Appends an item to `GroupBy`.
    ///
    /// To override the contents of this collection use [`set_group_by`](Self::set_group_by).
    ///
    /// <p>The dimensions available for grouping estimated carbon emissions.</p>
    pub fn group_by(mut self, input: crate::types::Dimension) -> Self {
        self.inner = self.inner.group_by(input);
        self
    }
    /// <p>The dimensions available for grouping estimated carbon emissions.</p>
    pub fn set_group_by(mut self, input: ::std::option::Option<::std::vec::Vec<crate::types::Dimension>>) -> Self {
        self.inner = self.inner.set_group_by(input);
        self
    }
    /// <p>The dimensions available for grouping estimated carbon emissions.</p>
    pub fn get_group_by(&self) -> &::std::option::Option<::std::vec::Vec<crate::types::Dimension>> {
        self.inner.get_group_by()
    }
    /// <p>The criteria for filtering estimated carbon emissions. To determine which dimensions are available to be filtered by, you can first call <code>GetEstimatedCarbonEmissionsDimensionValues</code></p>
    pub fn filter_by(mut self, input: crate::types::FilterExpression) -> Self {
        self.inner = self.inner.filter_by(input);
        self
    }
    /// <p>The criteria for filtering estimated carbon emissions. To determine which dimensions are available to be filtered by, you can first call <code>GetEstimatedCarbonEmissionsDimensionValues</code></p>
    pub fn set_filter_by(mut self, input: ::std::option::Option<crate::types::FilterExpression>) -> Self {
        self.inner = self.inner.set_filter_by(input);
        self
    }
    /// <p>The criteria for filtering estimated carbon emissions. To determine which dimensions are available to be filtered by, you can first call <code>GetEstimatedCarbonEmissionsDimensionValues</code></p>
    pub fn get_filter_by(&self) -> &::std::option::Option<crate::types::FilterExpression> {
        self.inner.get_filter_by()
    }
    ///
    /// Appends an item to `EmissionsTypes`.
    ///
    /// To override the contents of this collection use [`set_emissions_types`](Self::set_emissions_types).
    ///
    /// <p>The emission types to include in the results. If absent, returns <code>TOTAL_LBM_CARBON_EMISSIONS</code> and <code>TOTAL_MBM_CARBON_EMISSIONS</code> emissions types.</p>
    pub fn emissions_types(mut self, input: crate::types::EmissionsType) -> Self {
        self.inner = self.inner.emissions_types(input);
        self
    }
    /// <p>The emission types to include in the results. If absent, returns <code>TOTAL_LBM_CARBON_EMISSIONS</code> and <code>TOTAL_MBM_CARBON_EMISSIONS</code> emissions types.</p>
    pub fn set_emissions_types(mut self, input: ::std::option::Option<::std::vec::Vec<crate::types::EmissionsType>>) -> Self {
        self.inner = self.inner.set_emissions_types(input);
        self
    }
    /// <p>The emission types to include in the results. If absent, returns <code>TOTAL_LBM_CARBON_EMISSIONS</code> and <code>TOTAL_MBM_CARBON_EMISSIONS</code> emissions types.</p>
    pub fn get_emissions_types(&self) -> &::std::option::Option<::std::vec::Vec<crate::types::EmissionsType>> {
        self.inner.get_emissions_types()
    }
    /// <p>The time granularity for the results. If absent, uses <code>MONTHLY</code> time granularity. The smallest supported granularity for carbon emissions is <code>MONTHLY</code>.</p>
    /// <p>If requesting partial time periods, data will be returned based on the smallest supported granularity. For example, requesting <code>2025-04-01T00:00:00Z</code> to <code>2026-04-01T00:00:00Z</code> with <code>YEARLY_CALENDAR</code> granularity will return the last 9 months for 2025 and the first 3 months of 2026.</p>
    pub fn granularity(mut self, input: crate::types::TimeGranularity) -> Self {
        self.inner = self.inner.granularity(input);
        self
    }
    /// <p>The time granularity for the results. If absent, uses <code>MONTHLY</code> time granularity. The smallest supported granularity for carbon emissions is <code>MONTHLY</code>.</p>
    /// <p>If requesting partial time periods, data will be returned based on the smallest supported granularity. For example, requesting <code>2025-04-01T00:00:00Z</code> to <code>2026-04-01T00:00:00Z</code> with <code>YEARLY_CALENDAR</code> granularity will return the last 9 months for 2025 and the first 3 months of 2026.</p>
    pub fn set_granularity(mut self, input: ::std::option::Option<crate::types::TimeGranularity>) -> Self {
        self.inner = self.inner.set_granularity(input);
        self
    }
    /// <p>The time granularity for the results. If absent, uses <code>MONTHLY</code> time granularity. The smallest supported granularity for carbon emissions is <code>MONTHLY</code>.</p>
    /// <p>If requesting partial time periods, data will be returned based on the smallest supported granularity. For example, requesting <code>2025-04-01T00:00:00Z</code> to <code>2026-04-01T00:00:00Z</code> with <code>YEARLY_CALENDAR</code> granularity will return the last 9 months for 2025 and the first 3 months of 2026.</p>
    pub fn get_granularity(&self) -> &::std::option::Option<crate::types::TimeGranularity> {
        self.inner.get_granularity()
    }
    /// <p>Configuration for fiscal year calculations when using <code>YEARLY_FISCAL</code> or <code>QUARTERLY_FISCAL</code> granularity.</p>
    pub fn granularity_configuration(mut self, input: crate::types::GranularityConfiguration) -> Self {
        self.inner = self.inner.granularity_configuration(input);
        self
    }
    /// <p>Configuration for fiscal year calculations when using <code>YEARLY_FISCAL</code> or <code>QUARTERLY_FISCAL</code> granularity.</p>
    pub fn set_granularity_configuration(mut self, input: ::std::option::Option<crate::types::GranularityConfiguration>) -> Self {
        self.inner = self.inner.set_granularity_configuration(input);
        self
    }
    /// <p>Configuration for fiscal year calculations when using <code>YEARLY_FISCAL</code> or <code>QUARTERLY_FISCAL</code> granularity.</p>
    pub fn get_granularity_configuration(&self) -> &::std::option::Option<crate::types::GranularityConfiguration> {
        self.inner.get_granularity_configuration()
    }
    /// <p>The maximum number of results to return in a single call. Default is 1000.</p>
    pub fn max_results(mut self, input: i32) -> Self {
        self.inner = self.inner.max_results(input);
        self
    }
    /// <p>The maximum number of results to return in a single call. Default is 1000.</p>
    pub fn set_max_results(mut self, input: ::std::option::Option<i32>) -> Self {
        self.inner = self.inner.set_max_results(input);
        self
    }
    /// <p>The maximum number of results to return in a single call. Default is 1000.</p>
    pub fn get_max_results(&self) -> &::std::option::Option<i32> {
        self.inner.get_max_results()
    }
    /// <p>The pagination token specifying which page of results to return in the response. If no token is provided, the default page is the first page.</p>
    pub fn next_token(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.inner = self.inner.next_token(input.into());
        self
    }
    /// <p>The pagination token specifying which page of results to return in the response. If no token is provided, the default page is the first page.</p>
    pub fn set_next_token(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.inner = self.inner.set_next_token(input);
        self
    }
    /// <p>The pagination token specifying which page of results to return in the response. If no token is provided, the default page is the first page.</p>
    pub fn get_next_token(&self) -> &::std::option::Option<::std::string::String> {
        self.inner.get_next_token()
    }
}
