// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>The official administrative names for an address component, returned when <code>AddressNamesMode</code> is set to <code>Administrative</code>.</p>
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct AdminNames {
    /// <p>A list of translation names for the administrative address component, including name variants and translations in available languages.</p>
    pub names: ::std::vec::Vec<crate::types::TranslationName>,
    /// <p>Indicates the preference level of the administrative name. Valid values are <code>Primary</code> and <code>Alternative</code>.</p>
    pub preference: ::std::option::Option<crate::types::AdminNamesPreference>,
}
impl AdminNames {
    /// <p>A list of translation names for the administrative address component, including name variants and translations in available languages.</p>
    pub fn names(&self) -> &[crate::types::TranslationName] {
        use std::ops::Deref;
        self.names.deref()
    }
    /// <p>Indicates the preference level of the administrative name. Valid values are <code>Primary</code> and <code>Alternative</code>.</p>
    pub fn preference(&self) -> ::std::option::Option<&crate::types::AdminNamesPreference> {
        self.preference.as_ref()
    }
}
impl AdminNames {
    /// Creates a new builder-style object to manufacture [`AdminNames`](crate::types::AdminNames).
    pub fn builder() -> crate::types::builders::AdminNamesBuilder {
        crate::types::builders::AdminNamesBuilder::default()
    }
}

/// A builder for [`AdminNames`](crate::types::AdminNames).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct AdminNamesBuilder {
    pub(crate) names: ::std::option::Option<::std::vec::Vec<crate::types::TranslationName>>,
    pub(crate) preference: ::std::option::Option<crate::types::AdminNamesPreference>,
}
impl AdminNamesBuilder {
    /// Appends an item to `names`.
    ///
    /// To override the contents of this collection use [`set_names`](Self::set_names).
    ///
    /// <p>A list of translation names for the administrative address component, including name variants and translations in available languages.</p>
    pub fn names(mut self, input: crate::types::TranslationName) -> Self {
        let mut v = self.names.unwrap_or_default();
        v.push(input);
        self.names = ::std::option::Option::Some(v);
        self
    }
    /// <p>A list of translation names for the administrative address component, including name variants and translations in available languages.</p>
    pub fn set_names(mut self, input: ::std::option::Option<::std::vec::Vec<crate::types::TranslationName>>) -> Self {
        self.names = input;
        self
    }
    /// <p>A list of translation names for the administrative address component, including name variants and translations in available languages.</p>
    pub fn get_names(&self) -> &::std::option::Option<::std::vec::Vec<crate::types::TranslationName>> {
        &self.names
    }
    /// <p>Indicates the preference level of the administrative name. Valid values are <code>Primary</code> and <code>Alternative</code>.</p>
    pub fn preference(mut self, input: crate::types::AdminNamesPreference) -> Self {
        self.preference = ::std::option::Option::Some(input);
        self
    }
    /// <p>Indicates the preference level of the administrative name. Valid values are <code>Primary</code> and <code>Alternative</code>.</p>
    pub fn set_preference(mut self, input: ::std::option::Option<crate::types::AdminNamesPreference>) -> Self {
        self.preference = input;
        self
    }
    /// <p>Indicates the preference level of the administrative name. Valid values are <code>Primary</code> and <code>Alternative</code>.</p>
    pub fn get_preference(&self) -> &::std::option::Option<crate::types::AdminNamesPreference> {
        &self.preference
    }
    /// Consumes the builder and constructs a [`AdminNames`](crate::types::AdminNames).
    /// This method will fail if any of the following fields are not set:
    /// - [`names`](crate::types::builders::AdminNamesBuilder::names)
    pub fn build(self) -> ::std::result::Result<crate::types::AdminNames, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(crate::types::AdminNames {
            names: self.names.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "names",
                    "names was not specified but it is required when building AdminNames",
                )
            })?,
            preference: self.preference,
        })
    }
}
