// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// Text Caption Position Settings
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct TextCaptionPositionSettings {
    /// Specifies the vertical position of the top edge of the caption relative to the top of the output as a percentage. A value of 0 places the caption at the top of the output and 100 at the bottom.
    pub y_position_percentage: ::std::option::Option<i32>,
}
impl TextCaptionPositionSettings {
    /// Specifies the vertical position of the top edge of the caption relative to the top of the output as a percentage. A value of 0 places the caption at the top of the output and 100 at the bottom.
    pub fn y_position_percentage(&self) -> ::std::option::Option<i32> {
        self.y_position_percentage
    }
}
impl TextCaptionPositionSettings {
    /// Creates a new builder-style object to manufacture [`TextCaptionPositionSettings`](crate::types::TextCaptionPositionSettings).
    pub fn builder() -> crate::types::builders::TextCaptionPositionSettingsBuilder {
        crate::types::builders::TextCaptionPositionSettingsBuilder::default()
    }
}

/// A builder for [`TextCaptionPositionSettings`](crate::types::TextCaptionPositionSettings).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct TextCaptionPositionSettingsBuilder {
    pub(crate) y_position_percentage: ::std::option::Option<i32>,
}
impl TextCaptionPositionSettingsBuilder {
    /// Specifies the vertical position of the top edge of the caption relative to the top of the output as a percentage. A value of 0 places the caption at the top of the output and 100 at the bottom.
    pub fn y_position_percentage(mut self, input: i32) -> Self {
        self.y_position_percentage = ::std::option::Option::Some(input);
        self
    }
    /// Specifies the vertical position of the top edge of the caption relative to the top of the output as a percentage. A value of 0 places the caption at the top of the output and 100 at the bottom.
    pub fn set_y_position_percentage(mut self, input: ::std::option::Option<i32>) -> Self {
        self.y_position_percentage = input;
        self
    }
    /// Specifies the vertical position of the top edge of the caption relative to the top of the output as a percentage. A value of 0 places the caption at the top of the output and 100 at the bottom.
    pub fn get_y_position_percentage(&self) -> &::std::option::Option<i32> {
        &self.y_position_percentage
    }
    /// Consumes the builder and constructs a [`TextCaptionPositionSettings`](crate::types::TextCaptionPositionSettings).
    pub fn build(self) -> crate::types::TextCaptionPositionSettings {
        crate::types::TextCaptionPositionSettings {
            y_position_percentage: self.y_position_percentage,
        }
    }
}
