// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// Webvtt Destination Settings
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct WebvttDestinationSettings {
    /// Controls whether the color and position of the source captions is passed through to the WebVTT output captions. PASSTHROUGH - Valid only if the source captions are EMBEDDED, TELETEXT, or SMART SUBTITLES. NO_STYLE_DATA - Don't pass through the style. The output captions will not contain any font styling information. MANUAL - Applies the specified styling and positioning. All other styling and positioning is given default values.
    pub style_control: ::std::option::Option<crate::types::WebvttDestinationStyleControl>,
    /// Specifies the position of the output captions. Applies only when styleControl is set to manual.
    pub position: ::std::option::Option<crate::types::TextCaptionPositionSettings>,
}
impl WebvttDestinationSettings {
    /// Controls whether the color and position of the source captions is passed through to the WebVTT output captions. PASSTHROUGH - Valid only if the source captions are EMBEDDED, TELETEXT, or SMART SUBTITLES. NO_STYLE_DATA - Don't pass through the style. The output captions will not contain any font styling information. MANUAL - Applies the specified styling and positioning. All other styling and positioning is given default values.
    pub fn style_control(&self) -> ::std::option::Option<&crate::types::WebvttDestinationStyleControl> {
        self.style_control.as_ref()
    }
    /// Specifies the position of the output captions. Applies only when styleControl is set to manual.
    pub fn position(&self) -> ::std::option::Option<&crate::types::TextCaptionPositionSettings> {
        self.position.as_ref()
    }
}
impl WebvttDestinationSettings {
    /// Creates a new builder-style object to manufacture [`WebvttDestinationSettings`](crate::types::WebvttDestinationSettings).
    pub fn builder() -> crate::types::builders::WebvttDestinationSettingsBuilder {
        crate::types::builders::WebvttDestinationSettingsBuilder::default()
    }
}

/// A builder for [`WebvttDestinationSettings`](crate::types::WebvttDestinationSettings).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct WebvttDestinationSettingsBuilder {
    pub(crate) style_control: ::std::option::Option<crate::types::WebvttDestinationStyleControl>,
    pub(crate) position: ::std::option::Option<crate::types::TextCaptionPositionSettings>,
}
impl WebvttDestinationSettingsBuilder {
    /// Controls whether the color and position of the source captions is passed through to the WebVTT output captions. PASSTHROUGH - Valid only if the source captions are EMBEDDED, TELETEXT, or SMART SUBTITLES. NO_STYLE_DATA - Don't pass through the style. The output captions will not contain any font styling information. MANUAL - Applies the specified styling and positioning. All other styling and positioning is given default values.
    pub fn style_control(mut self, input: crate::types::WebvttDestinationStyleControl) -> Self {
        self.style_control = ::std::option::Option::Some(input);
        self
    }
    /// Controls whether the color and position of the source captions is passed through to the WebVTT output captions. PASSTHROUGH - Valid only if the source captions are EMBEDDED, TELETEXT, or SMART SUBTITLES. NO_STYLE_DATA - Don't pass through the style. The output captions will not contain any font styling information. MANUAL - Applies the specified styling and positioning. All other styling and positioning is given default values.
    pub fn set_style_control(mut self, input: ::std::option::Option<crate::types::WebvttDestinationStyleControl>) -> Self {
        self.style_control = input;
        self
    }
    /// Controls whether the color and position of the source captions is passed through to the WebVTT output captions. PASSTHROUGH - Valid only if the source captions are EMBEDDED, TELETEXT, or SMART SUBTITLES. NO_STYLE_DATA - Don't pass through the style. The output captions will not contain any font styling information. MANUAL - Applies the specified styling and positioning. All other styling and positioning is given default values.
    pub fn get_style_control(&self) -> &::std::option::Option<crate::types::WebvttDestinationStyleControl> {
        &self.style_control
    }
    /// Specifies the position of the output captions. Applies only when styleControl is set to manual.
    pub fn position(mut self, input: crate::types::TextCaptionPositionSettings) -> Self {
        self.position = ::std::option::Option::Some(input);
        self
    }
    /// Specifies the position of the output captions. Applies only when styleControl is set to manual.
    pub fn set_position(mut self, input: ::std::option::Option<crate::types::TextCaptionPositionSettings>) -> Self {
        self.position = input;
        self
    }
    /// Specifies the position of the output captions. Applies only when styleControl is set to manual.
    pub fn get_position(&self) -> &::std::option::Option<crate::types::TextCaptionPositionSettings> {
        &self.position
    }
    /// Consumes the builder and constructs a [`WebvttDestinationSettings`](crate::types::WebvttDestinationSettings).
    pub fn build(self) -> crate::types::WebvttDestinationSettings {
        crate::types::WebvttDestinationSettings {
            style_control: self.style_control,
            position: self.position,
        }
    }
}
