// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_instance_network_performance_options_request(
    encoder: &mut ::aws_smithy_cbor::Encoder,
    #[allow(unused)] input: &crate::types::InstanceNetworkPerformanceOptionsRequest,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    encoder.begin_map();
    if let Some(var_1) = &input.bandwidth_weighting {
        encoder.str("BandwidthWeighting").str(var_1.as_str());
    }
    encoder.end();
    Ok(())
}
