// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`ModifyQev2IdcApplication`](crate::operation::modify_qev2_idc_application::builders::ModifyQev2IdcApplicationFluentBuilder) operation.
    ///
    /// - The fluent builder is configurable:
    ///   - [`qev2_idc_application_arn(impl Into<String>)`](crate::operation::modify_qev2_idc_application::builders::ModifyQev2IdcApplicationFluentBuilder::qev2_idc_application_arn) / [`set_qev2_idc_application_arn(Option<String>)`](crate::operation::modify_qev2_idc_application::builders::ModifyQev2IdcApplicationFluentBuilder::set_qev2_idc_application_arn):<br>required: **true**<br><p>The Amazon Resource Name (ARN) for the Amazon Redshift Query Editor (QEV2) application that integrates with IAM Identity Center.</p><br>
    ///   - [`idc_display_name(impl Into<String>)`](crate::operation::modify_qev2_idc_application::builders::ModifyQev2IdcApplicationFluentBuilder::idc_display_name) / [`set_idc_display_name(Option<String>)`](crate::operation::modify_qev2_idc_application::builders::ModifyQev2IdcApplicationFluentBuilder::set_idc_display_name):<br>required: **false**<br><p>The display name for the Amazon Redshift Query Editor (QEV2) IAM Identity Center application. It appears in the console.</p><br>
    /// - On success, responds with [`ModifyQev2IdcApplicationOutput`](crate::operation::modify_qev2_idc_application::ModifyQev2IdcApplicationOutput) with field(s):
    ///   - [`qev2_idc_application(Option<Qev2IdcApplication>)`](crate::operation::modify_qev2_idc_application::ModifyQev2IdcApplicationOutput::qev2_idc_application): <p>Contains configuration and status information for an Amazon Redshift Query Editor (QEV2) application that is registered with IAM Identity Center.</p>
    /// - On failure, responds with [`SdkError<ModifyQev2IdcApplicationError>`](crate::operation::modify_qev2_idc_application::ModifyQev2IdcApplicationError)
    pub fn modify_qev2_idc_application(&self) -> crate::operation::modify_qev2_idc_application::builders::ModifyQev2IdcApplicationFluentBuilder {
        crate::operation::modify_qev2_idc_application::builders::ModifyQev2IdcApplicationFluentBuilder::new(self.handle.clone())
    }
}
