// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct ListProcurementPortalSuppliersOutput {
    /// <p>The list of suppliers configured for the specified procurement portal.</p>
    pub procurement_portal_suppliers: ::std::vec::Vec<crate::types::ProcurementPortalSupplier>,
    /// <p>The token to use to retrieve the next set of results, or null if there are no more results.</p>
    pub next_token: ::std::option::Option<::std::string::String>,
    _request_id: Option<String>,
}
impl ListProcurementPortalSuppliersOutput {
    /// <p>The list of suppliers configured for the specified procurement portal.</p>
    pub fn procurement_portal_suppliers(&self) -> &[crate::types::ProcurementPortalSupplier] {
        use std::ops::Deref;
        self.procurement_portal_suppliers.deref()
    }
    /// <p>The token to use to retrieve the next set of results, or null if there are no more results.</p>
    pub fn next_token(&self) -> ::std::option::Option<&str> {
        self.next_token.as_deref()
    }
}
impl ::aws_types::request_id::RequestId for ListProcurementPortalSuppliersOutput {
    fn request_id(&self) -> Option<&str> {
        self._request_id.as_deref()
    }
}
impl ListProcurementPortalSuppliersOutput {
    /// Creates a new builder-style object to manufacture [`ListProcurementPortalSuppliersOutput`](crate::operation::list_procurement_portal_suppliers::ListProcurementPortalSuppliersOutput).
    pub fn builder() -> crate::operation::list_procurement_portal_suppliers::builders::ListProcurementPortalSuppliersOutputBuilder {
        crate::operation::list_procurement_portal_suppliers::builders::ListProcurementPortalSuppliersOutputBuilder::default()
    }
}

/// A builder for [`ListProcurementPortalSuppliersOutput`](crate::operation::list_procurement_portal_suppliers::ListProcurementPortalSuppliersOutput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct ListProcurementPortalSuppliersOutputBuilder {
    pub(crate) procurement_portal_suppliers: ::std::option::Option<::std::vec::Vec<crate::types::ProcurementPortalSupplier>>,
    pub(crate) next_token: ::std::option::Option<::std::string::String>,
    _request_id: Option<String>,
}
impl ListProcurementPortalSuppliersOutputBuilder {
    /// Appends an item to `procurement_portal_suppliers`.
    ///
    /// To override the contents of this collection use [`set_procurement_portal_suppliers`](Self::set_procurement_portal_suppliers).
    ///
    /// <p>The list of suppliers configured for the specified procurement portal.</p>
    pub fn procurement_portal_suppliers(mut self, input: crate::types::ProcurementPortalSupplier) -> Self {
        let mut v = self.procurement_portal_suppliers.unwrap_or_default();
        v.push(input);
        self.procurement_portal_suppliers = ::std::option::Option::Some(v);
        self
    }
    /// <p>The list of suppliers configured for the specified procurement portal.</p>
    pub fn set_procurement_portal_suppliers(
        mut self,
        input: ::std::option::Option<::std::vec::Vec<crate::types::ProcurementPortalSupplier>>,
    ) -> Self {
        self.procurement_portal_suppliers = input;
        self
    }
    /// <p>The list of suppliers configured for the specified procurement portal.</p>
    pub fn get_procurement_portal_suppliers(&self) -> &::std::option::Option<::std::vec::Vec<crate::types::ProcurementPortalSupplier>> {
        &self.procurement_portal_suppliers
    }
    /// <p>The token to use to retrieve the next set of results, or null if there are no more results.</p>
    pub fn next_token(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.next_token = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The token to use to retrieve the next set of results, or null if there are no more results.</p>
    pub fn set_next_token(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.next_token = input;
        self
    }
    /// <p>The token to use to retrieve the next set of results, or null if there are no more results.</p>
    pub fn get_next_token(&self) -> &::std::option::Option<::std::string::String> {
        &self.next_token
    }
    pub(crate) fn _request_id(mut self, request_id: impl Into<String>) -> Self {
        self._request_id = Some(request_id.into());
        self
    }

    pub(crate) fn _set_request_id(&mut self, request_id: Option<String>) -> &mut Self {
        self._request_id = request_id;
        self
    }
    /// Consumes the builder and constructs a [`ListProcurementPortalSuppliersOutput`](crate::operation::list_procurement_portal_suppliers::ListProcurementPortalSuppliersOutput).
    /// This method will fail if any of the following fields are not set:
    /// - [`procurement_portal_suppliers`](crate::operation::list_procurement_portal_suppliers::builders::ListProcurementPortalSuppliersOutputBuilder::procurement_portal_suppliers)
    pub fn build(
        self,
    ) -> ::std::result::Result<
        crate::operation::list_procurement_portal_suppliers::ListProcurementPortalSuppliersOutput,
        ::aws_smithy_types::error::operation::BuildError,
    > {
        ::std::result::Result::Ok(
            crate::operation::list_procurement_portal_suppliers::ListProcurementPortalSuppliersOutput {
                procurement_portal_suppliers: self.procurement_portal_suppliers.ok_or_else(|| {
                    ::aws_smithy_types::error::operation::BuildError::missing_field(
                        "procurement_portal_suppliers",
                        "procurement_portal_suppliers was not specified but it is required when building ListProcurementPortalSuppliersOutput",
                    )
                })?,
                next_token: self.next_token,
                _request_id: self._request_id,
            },
        )
    }
}
