// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct ListProcurementPortalSuppliersInput {
    /// <p>The unique identifier of the procurement portal for which to list suppliers. Use the <code>PortalIdentifier</code> value returned by <code>ListProcurementPortals</code>.</p>
    pub portal_identifier: ::std::option::Option<::std::string::String>,
    /// <p>The token for the next set of results. You received this token from a previous call.</p>
    pub next_token: ::std::option::Option<::std::string::String>,
    /// <p>The maximum number of results to return in a single call. To retrieve the remaining results, make another call with the returned NextToken value. Default is 100.</p>
    pub max_results: ::std::option::Option<i32>,
}
impl ListProcurementPortalSuppliersInput {
    /// <p>The unique identifier of the procurement portal for which to list suppliers. Use the <code>PortalIdentifier</code> value returned by <code>ListProcurementPortals</code>.</p>
    pub fn portal_identifier(&self) -> ::std::option::Option<&str> {
        self.portal_identifier.as_deref()
    }
    /// <p>The token for the next set of results. You received this token from a previous call.</p>
    pub fn next_token(&self) -> ::std::option::Option<&str> {
        self.next_token.as_deref()
    }
    /// <p>The maximum number of results to return in a single call. To retrieve the remaining results, make another call with the returned NextToken value. Default is 100.</p>
    pub fn max_results(&self) -> ::std::option::Option<i32> {
        self.max_results
    }
}
impl ListProcurementPortalSuppliersInput {
    /// Creates a new builder-style object to manufacture [`ListProcurementPortalSuppliersInput`](crate::operation::list_procurement_portal_suppliers::ListProcurementPortalSuppliersInput).
    pub fn builder() -> crate::operation::list_procurement_portal_suppliers::builders::ListProcurementPortalSuppliersInputBuilder {
        crate::operation::list_procurement_portal_suppliers::builders::ListProcurementPortalSuppliersInputBuilder::default()
    }
}

/// A builder for [`ListProcurementPortalSuppliersInput`](crate::operation::list_procurement_portal_suppliers::ListProcurementPortalSuppliersInput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct ListProcurementPortalSuppliersInputBuilder {
    pub(crate) portal_identifier: ::std::option::Option<::std::string::String>,
    pub(crate) next_token: ::std::option::Option<::std::string::String>,
    pub(crate) max_results: ::std::option::Option<i32>,
}
impl ListProcurementPortalSuppliersInputBuilder {
    /// <p>The unique identifier of the procurement portal for which to list suppliers. Use the <code>PortalIdentifier</code> value returned by <code>ListProcurementPortals</code>.</p>
    /// This field is required.
    pub fn portal_identifier(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.portal_identifier = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The unique identifier of the procurement portal for which to list suppliers. Use the <code>PortalIdentifier</code> value returned by <code>ListProcurementPortals</code>.</p>
    pub fn set_portal_identifier(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.portal_identifier = input;
        self
    }
    /// <p>The unique identifier of the procurement portal for which to list suppliers. Use the <code>PortalIdentifier</code> value returned by <code>ListProcurementPortals</code>.</p>
    pub fn get_portal_identifier(&self) -> &::std::option::Option<::std::string::String> {
        &self.portal_identifier
    }
    /// <p>The token for the next set of results. You received this token from a previous call.</p>
    pub fn next_token(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.next_token = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The token for the next set of results. You received this token from a previous call.</p>
    pub fn set_next_token(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.next_token = input;
        self
    }
    /// <p>The token for the next set of results. You received this token from a previous call.</p>
    pub fn get_next_token(&self) -> &::std::option::Option<::std::string::String> {
        &self.next_token
    }
    /// <p>The maximum number of results to return in a single call. To retrieve the remaining results, make another call with the returned NextToken value. Default is 100.</p>
    pub fn max_results(mut self, input: i32) -> Self {
        self.max_results = ::std::option::Option::Some(input);
        self
    }
    /// <p>The maximum number of results to return in a single call. To retrieve the remaining results, make another call with the returned NextToken value. Default is 100.</p>
    pub fn set_max_results(mut self, input: ::std::option::Option<i32>) -> Self {
        self.max_results = input;
        self
    }
    /// <p>The maximum number of results to return in a single call. To retrieve the remaining results, make another call with the returned NextToken value. Default is 100.</p>
    pub fn get_max_results(&self) -> &::std::option::Option<i32> {
        &self.max_results
    }
    /// Consumes the builder and constructs a [`ListProcurementPortalSuppliersInput`](crate::operation::list_procurement_portal_suppliers::ListProcurementPortalSuppliersInput).
    pub fn build(
        self,
    ) -> ::std::result::Result<
        crate::operation::list_procurement_portal_suppliers::ListProcurementPortalSuppliersInput,
        ::aws_smithy_types::error::operation::BuildError,
    > {
        ::std::result::Result::Ok(crate::operation::list_procurement_portal_suppliers::ListProcurementPortalSuppliersInput {
            portal_identifier: self.portal_identifier,
            next_token: self.next_token,
            max_results: self.max_results,
        })
    }
}
