// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_vmware_to_aws_tag_mapping(
    encoder: &mut ::aws_smithy_cbor::Encoder,
    #[allow(unused)] input: &crate::types::VmwareToAwsTagMapping,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    encoder.begin_map();
    {
        encoder.str("VmwareCategory").str(input.vmware_category.as_str());
    }
    {
        encoder.str("VmwareTagName").str(input.vmware_tag_name.as_str());
    }
    {
        encoder.str("AwsTagKey").str(input.aws_tag_key.as_str());
    }
    {
        encoder.str("AwsTagValue").str(input.aws_tag_value.as_str());
    }
    encoder.end();
    Ok(())
}

pub(crate) fn de_vmware_to_aws_tag_mapping(
    decoder: &mut ::aws_smithy_cbor::Decoder,
    depth: u32,
) -> ::std::result::Result<crate::types::VmwareToAwsTagMapping, ::aws_smithy_cbor::decode::DeserializeError> {
    if depth >= 128u32 {
        return Err(::aws_smithy_cbor::decode::DeserializeError::custom(
            "maximum nesting depth exceeded",
            decoder.position(),
        ));
    }
    #[allow(clippy::match_single_binding, unused_variables)]
    fn pair(
        mut builder: crate::types::builders::VmwareToAwsTagMappingBuilder,
        decoder: &mut ::aws_smithy_cbor::Decoder,
        depth: u32,
    ) -> ::std::result::Result<crate::types::builders::VmwareToAwsTagMappingBuilder, ::aws_smithy_cbor::decode::DeserializeError> {
        builder = match decoder.str()?.as_ref() {
            "VmwareCategory" => builder.set_vmware_category(Some(decoder.string()?)),
            "VmwareTagName" => builder.set_vmware_tag_name(Some(decoder.string()?)),
            "AwsTagKey" => builder.set_aws_tag_key(Some(decoder.string()?)),
            "AwsTagValue" => builder.set_aws_tag_value(Some(decoder.string()?)),
            _ => {
                decoder.skip()?;
                builder
            }
        };
        Ok(builder)
    }

    let mut builder = crate::types::builders::VmwareToAwsTagMappingBuilder::default();

    match decoder.map()? {
        None => loop {
            match decoder.datatype()? {
                ::aws_smithy_cbor::data::Type::Break => {
                    decoder.skip()?;
                    break;
                }
                _ => {
                    builder = pair(builder, decoder, depth)?;
                }
            };
        },
        Some(n) => {
            for _ in 0..n {
                builder = pair(builder, decoder, depth)?;
            }
        }
    };
    #[allow(clippy::needless_question_mark)]
    {
        return Ok(crate::serde_util::vmware_to_aws_tag_mapping_correct_errors(builder)
            .build()
            .map_err(|err| ::aws_smithy_cbor::decode::DeserializeError::custom(err.to_string(), decoder.position()))?);
    }
}
