// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_create_gateway_input_input(
    encoder: &mut ::aws_smithy_cbor::Encoder,
    #[allow(unused)] input: &crate::operation::create_gateway::CreateGatewayInput,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    encoder.begin_map();
    if let Some(var_1) = &input.activation_key {
        encoder.str("ActivationKey").str(var_1.as_str());
    }
    if let Some(var_2) = &input.gateway_display_name {
        encoder.str("GatewayDisplayName").str(var_2.as_str());
    }
    if let Some(var_3) = &input.gateway_type {
        encoder.str("GatewayType").str(var_3.as_str());
    }
    if let Some(var_4) = &input.tags {
        encoder.str("Tags");
        encoder.array((*var_4).len());
        for item_5 in var_4 {
            {
                crate::protocol_serde::shape_tag::ser_tag(encoder, item_5)?;
            }
        }
    }
    encoder.end();
    Ok(())
}
