// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>A candidate instance type preference in an <code>InstancePreferences</code> list.</p>
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct InstancePreference {
    /// <p>The ML compute instance type. An instance type can appear only once in an <code>InstancePreferences</code> list.</p>
    pub instance_type: ::std::option::Option<crate::types::TrainingInstanceType>,
    /// <p>The number of instances to launch if this instance type is selected. Specify the instance count for the training job in one of the following two ways:</p>
    /// <ol>
    /// <li>
    /// <p><b>Per preference</b> – Set <code>InstanceCount</code> on every preference in the <code>InstancePreferences</code> list and don't set <code>ResourceConfig$InstanceCount</code>. Use this when each instance type needs a different number of instances to deliver equivalent compute.</p></li>
    /// <li>
    /// <p><b>One count for the job</b> – Set <code>ResourceConfig$InstanceCount</code> and omit it from every preference. SageMaker applies this to all instance types in the list.</p></li>
    /// </ol>
    /// <p>For example, in a list of five preferences, either all five specify <code>InstanceCount</code> or none of them do. SageMaker rejects requests that set <code>InstanceCount</code> on only some preferences, that set it both per preference and in <code>ResourceConfig</code>, or that omit it in both places.</p>
    pub instance_count: ::std::option::Option<i32>,
    /// <p>The Amazon Resource Name (ARN) of a training plan to use if this instance type is selected. The plan's instance type must match <code>InstanceType</code>. A preference with a training plan uses that plan's reserved capacity; a preference without one uses on-demand capacity. Per-preference <code>TrainingPlanArns</code> is mutually exclusive with the job-level <code>TrainingPlanArn</code> in <code>ResourceConfig</code>.</p>
    pub training_plan_arns: ::std::option::Option<::std::vec::Vec<::std::string::String>>,
}
impl InstancePreference {
    /// <p>The ML compute instance type. An instance type can appear only once in an <code>InstancePreferences</code> list.</p>
    pub fn instance_type(&self) -> ::std::option::Option<&crate::types::TrainingInstanceType> {
        self.instance_type.as_ref()
    }
    /// <p>The number of instances to launch if this instance type is selected. Specify the instance count for the training job in one of the following two ways:</p>
    /// <ol>
    /// <li>
    /// <p><b>Per preference</b> – Set <code>InstanceCount</code> on every preference in the <code>InstancePreferences</code> list and don't set <code>ResourceConfig$InstanceCount</code>. Use this when each instance type needs a different number of instances to deliver equivalent compute.</p></li>
    /// <li>
    /// <p><b>One count for the job</b> – Set <code>ResourceConfig$InstanceCount</code> and omit it from every preference. SageMaker applies this to all instance types in the list.</p></li>
    /// </ol>
    /// <p>For example, in a list of five preferences, either all five specify <code>InstanceCount</code> or none of them do. SageMaker rejects requests that set <code>InstanceCount</code> on only some preferences, that set it both per preference and in <code>ResourceConfig</code>, or that omit it in both places.</p>
    pub fn instance_count(&self) -> ::std::option::Option<i32> {
        self.instance_count
    }
    /// <p>The Amazon Resource Name (ARN) of a training plan to use if this instance type is selected. The plan's instance type must match <code>InstanceType</code>. A preference with a training plan uses that plan's reserved capacity; a preference without one uses on-demand capacity. Per-preference <code>TrainingPlanArns</code> is mutually exclusive with the job-level <code>TrainingPlanArn</code> in <code>ResourceConfig</code>.</p>
    ///
    /// If no value was sent for this field, a default will be set. If you want to determine if no value was sent, use `.training_plan_arns.is_none()`.
    pub fn training_plan_arns(&self) -> &[::std::string::String] {
        self.training_plan_arns.as_deref().unwrap_or_default()
    }
}
impl InstancePreference {
    /// Creates a new builder-style object to manufacture [`InstancePreference`](crate::types::InstancePreference).
    pub fn builder() -> crate::types::builders::InstancePreferenceBuilder {
        crate::types::builders::InstancePreferenceBuilder::default()
    }
}

/// A builder for [`InstancePreference`](crate::types::InstancePreference).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct InstancePreferenceBuilder {
    pub(crate) instance_type: ::std::option::Option<crate::types::TrainingInstanceType>,
    pub(crate) instance_count: ::std::option::Option<i32>,
    pub(crate) training_plan_arns: ::std::option::Option<::std::vec::Vec<::std::string::String>>,
}
impl InstancePreferenceBuilder {
    /// <p>The ML compute instance type. An instance type can appear only once in an <code>InstancePreferences</code> list.</p>
    /// This field is required.
    pub fn instance_type(mut self, input: crate::types::TrainingInstanceType) -> Self {
        self.instance_type = ::std::option::Option::Some(input);
        self
    }
    /// <p>The ML compute instance type. An instance type can appear only once in an <code>InstancePreferences</code> list.</p>
    pub fn set_instance_type(mut self, input: ::std::option::Option<crate::types::TrainingInstanceType>) -> Self {
        self.instance_type = input;
        self
    }
    /// <p>The ML compute instance type. An instance type can appear only once in an <code>InstancePreferences</code> list.</p>
    pub fn get_instance_type(&self) -> &::std::option::Option<crate::types::TrainingInstanceType> {
        &self.instance_type
    }
    /// <p>The number of instances to launch if this instance type is selected. Specify the instance count for the training job in one of the following two ways:</p>
    /// <ol>
    /// <li>
    /// <p><b>Per preference</b> – Set <code>InstanceCount</code> on every preference in the <code>InstancePreferences</code> list and don't set <code>ResourceConfig$InstanceCount</code>. Use this when each instance type needs a different number of instances to deliver equivalent compute.</p></li>
    /// <li>
    /// <p><b>One count for the job</b> – Set <code>ResourceConfig$InstanceCount</code> and omit it from every preference. SageMaker applies this to all instance types in the list.</p></li>
    /// </ol>
    /// <p>For example, in a list of five preferences, either all five specify <code>InstanceCount</code> or none of them do. SageMaker rejects requests that set <code>InstanceCount</code> on only some preferences, that set it both per preference and in <code>ResourceConfig</code>, or that omit it in both places.</p>
    pub fn instance_count(mut self, input: i32) -> Self {
        self.instance_count = ::std::option::Option::Some(input);
        self
    }
    /// <p>The number of instances to launch if this instance type is selected. Specify the instance count for the training job in one of the following two ways:</p>
    /// <ol>
    /// <li>
    /// <p><b>Per preference</b> – Set <code>InstanceCount</code> on every preference in the <code>InstancePreferences</code> list and don't set <code>ResourceConfig$InstanceCount</code>. Use this when each instance type needs a different number of instances to deliver equivalent compute.</p></li>
    /// <li>
    /// <p><b>One count for the job</b> – Set <code>ResourceConfig$InstanceCount</code> and omit it from every preference. SageMaker applies this to all instance types in the list.</p></li>
    /// </ol>
    /// <p>For example, in a list of five preferences, either all five specify <code>InstanceCount</code> or none of them do. SageMaker rejects requests that set <code>InstanceCount</code> on only some preferences, that set it both per preference and in <code>ResourceConfig</code>, or that omit it in both places.</p>
    pub fn set_instance_count(mut self, input: ::std::option::Option<i32>) -> Self {
        self.instance_count = input;
        self
    }
    /// <p>The number of instances to launch if this instance type is selected. Specify the instance count for the training job in one of the following two ways:</p>
    /// <ol>
    /// <li>
    /// <p><b>Per preference</b> – Set <code>InstanceCount</code> on every preference in the <code>InstancePreferences</code> list and don't set <code>ResourceConfig$InstanceCount</code>. Use this when each instance type needs a different number of instances to deliver equivalent compute.</p></li>
    /// <li>
    /// <p><b>One count for the job</b> – Set <code>ResourceConfig$InstanceCount</code> and omit it from every preference. SageMaker applies this to all instance types in the list.</p></li>
    /// </ol>
    /// <p>For example, in a list of five preferences, either all five specify <code>InstanceCount</code> or none of them do. SageMaker rejects requests that set <code>InstanceCount</code> on only some preferences, that set it both per preference and in <code>ResourceConfig</code>, or that omit it in both places.</p>
    pub fn get_instance_count(&self) -> &::std::option::Option<i32> {
        &self.instance_count
    }
    /// Appends an item to `training_plan_arns`.
    ///
    /// To override the contents of this collection use [`set_training_plan_arns`](Self::set_training_plan_arns).
    ///
    /// <p>The Amazon Resource Name (ARN) of a training plan to use if this instance type is selected. The plan's instance type must match <code>InstanceType</code>. A preference with a training plan uses that plan's reserved capacity; a preference without one uses on-demand capacity. Per-preference <code>TrainingPlanArns</code> is mutually exclusive with the job-level <code>TrainingPlanArn</code> in <code>ResourceConfig</code>.</p>
    pub fn training_plan_arns(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        let mut v = self.training_plan_arns.unwrap_or_default();
        v.push(input.into());
        self.training_plan_arns = ::std::option::Option::Some(v);
        self
    }
    /// <p>The Amazon Resource Name (ARN) of a training plan to use if this instance type is selected. The plan's instance type must match <code>InstanceType</code>. A preference with a training plan uses that plan's reserved capacity; a preference without one uses on-demand capacity. Per-preference <code>TrainingPlanArns</code> is mutually exclusive with the job-level <code>TrainingPlanArn</code> in <code>ResourceConfig</code>.</p>
    pub fn set_training_plan_arns(mut self, input: ::std::option::Option<::std::vec::Vec<::std::string::String>>) -> Self {
        self.training_plan_arns = input;
        self
    }
    /// <p>The Amazon Resource Name (ARN) of a training plan to use if this instance type is selected. The plan's instance type must match <code>InstanceType</code>. A preference with a training plan uses that plan's reserved capacity; a preference without one uses on-demand capacity. Per-preference <code>TrainingPlanArns</code> is mutually exclusive with the job-level <code>TrainingPlanArn</code> in <code>ResourceConfig</code>.</p>
    pub fn get_training_plan_arns(&self) -> &::std::option::Option<::std::vec::Vec<::std::string::String>> {
        &self.training_plan_arns
    }
    /// Consumes the builder and constructs a [`InstancePreference`](crate::types::InstancePreference).
    pub fn build(self) -> crate::types::InstancePreference {
        crate::types::InstancePreference {
            instance_type: self.instance_type,
            instance_count: self.instance_count,
            training_plan_arns: self.training_plan_arns,
        }
    }
}
