// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>A candidate instance type preference in a processing <code>InstancePreferences</code> list.</p>
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct ProcessingInstancePreference {
    /// <p>The ML compute instance type. An instance type can appear only once in an <code>InstancePreferences</code> list.</p>
    pub instance_type: ::std::option::Option<crate::types::ProcessingInstanceType>,
    /// <p>The number of instances to launch if this instance type is selected. Specify the instance count for the processing job in one of the following two ways:</p>
    /// <ol>
    /// <li>
    /// <p><b>Per preference</b> – Set <code>InstanceCount</code> on every preference in the <code>InstancePreferences</code> list and don't set <code>ProcessingClusterConfig$InstanceCount</code>. Use this when each instance type needs a different number of instances to deliver equivalent compute.</p></li>
    /// <li>
    /// <p><b>One count for the job</b> – Set <code>ProcessingClusterConfig$InstanceCount</code> and omit it from every preference. Amazon SageMaker applies this to all instance types in the list.</p></li>
    /// </ol>
    /// <p>For example, in a list of five preferences, either all five specify <code>InstanceCount</code> or none of them do. Amazon SageMaker rejects requests that set <code>InstanceCount</code> on only some preferences, that set it both per preference and in <code>ProcessingClusterConfig</code>, or that omit it in both places.</p>
    pub instance_count: ::std::option::Option<i32>,
}
impl ProcessingInstancePreference {
    /// <p>The ML compute instance type. An instance type can appear only once in an <code>InstancePreferences</code> list.</p>
    pub fn instance_type(&self) -> ::std::option::Option<&crate::types::ProcessingInstanceType> {
        self.instance_type.as_ref()
    }
    /// <p>The number of instances to launch if this instance type is selected. Specify the instance count for the processing job in one of the following two ways:</p>
    /// <ol>
    /// <li>
    /// <p><b>Per preference</b> – Set <code>InstanceCount</code> on every preference in the <code>InstancePreferences</code> list and don't set <code>ProcessingClusterConfig$InstanceCount</code>. Use this when each instance type needs a different number of instances to deliver equivalent compute.</p></li>
    /// <li>
    /// <p><b>One count for the job</b> – Set <code>ProcessingClusterConfig$InstanceCount</code> and omit it from every preference. Amazon SageMaker applies this to all instance types in the list.</p></li>
    /// </ol>
    /// <p>For example, in a list of five preferences, either all five specify <code>InstanceCount</code> or none of them do. Amazon SageMaker rejects requests that set <code>InstanceCount</code> on only some preferences, that set it both per preference and in <code>ProcessingClusterConfig</code>, or that omit it in both places.</p>
    pub fn instance_count(&self) -> ::std::option::Option<i32> {
        self.instance_count
    }
}
impl ProcessingInstancePreference {
    /// Creates a new builder-style object to manufacture [`ProcessingInstancePreference`](crate::types::ProcessingInstancePreference).
    pub fn builder() -> crate::types::builders::ProcessingInstancePreferenceBuilder {
        crate::types::builders::ProcessingInstancePreferenceBuilder::default()
    }
}

/// A builder for [`ProcessingInstancePreference`](crate::types::ProcessingInstancePreference).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct ProcessingInstancePreferenceBuilder {
    pub(crate) instance_type: ::std::option::Option<crate::types::ProcessingInstanceType>,
    pub(crate) instance_count: ::std::option::Option<i32>,
}
impl ProcessingInstancePreferenceBuilder {
    /// <p>The ML compute instance type. An instance type can appear only once in an <code>InstancePreferences</code> list.</p>
    /// This field is required.
    pub fn instance_type(mut self, input: crate::types::ProcessingInstanceType) -> Self {
        self.instance_type = ::std::option::Option::Some(input);
        self
    }
    /// <p>The ML compute instance type. An instance type can appear only once in an <code>InstancePreferences</code> list.</p>
    pub fn set_instance_type(mut self, input: ::std::option::Option<crate::types::ProcessingInstanceType>) -> Self {
        self.instance_type = input;
        self
    }
    /// <p>The ML compute instance type. An instance type can appear only once in an <code>InstancePreferences</code> list.</p>
    pub fn get_instance_type(&self) -> &::std::option::Option<crate::types::ProcessingInstanceType> {
        &self.instance_type
    }
    /// <p>The number of instances to launch if this instance type is selected. Specify the instance count for the processing job in one of the following two ways:</p>
    /// <ol>
    /// <li>
    /// <p><b>Per preference</b> – Set <code>InstanceCount</code> on every preference in the <code>InstancePreferences</code> list and don't set <code>ProcessingClusterConfig$InstanceCount</code>. Use this when each instance type needs a different number of instances to deliver equivalent compute.</p></li>
    /// <li>
    /// <p><b>One count for the job</b> – Set <code>ProcessingClusterConfig$InstanceCount</code> and omit it from every preference. Amazon SageMaker applies this to all instance types in the list.</p></li>
    /// </ol>
    /// <p>For example, in a list of five preferences, either all five specify <code>InstanceCount</code> or none of them do. Amazon SageMaker rejects requests that set <code>InstanceCount</code> on only some preferences, that set it both per preference and in <code>ProcessingClusterConfig</code>, or that omit it in both places.</p>
    pub fn instance_count(mut self, input: i32) -> Self {
        self.instance_count = ::std::option::Option::Some(input);
        self
    }
    /// <p>The number of instances to launch if this instance type is selected. Specify the instance count for the processing job in one of the following two ways:</p>
    /// <ol>
    /// <li>
    /// <p><b>Per preference</b> – Set <code>InstanceCount</code> on every preference in the <code>InstancePreferences</code> list and don't set <code>ProcessingClusterConfig$InstanceCount</code>. Use this when each instance type needs a different number of instances to deliver equivalent compute.</p></li>
    /// <li>
    /// <p><b>One count for the job</b> – Set <code>ProcessingClusterConfig$InstanceCount</code> and omit it from every preference. Amazon SageMaker applies this to all instance types in the list.</p></li>
    /// </ol>
    /// <p>For example, in a list of five preferences, either all five specify <code>InstanceCount</code> or none of them do. Amazon SageMaker rejects requests that set <code>InstanceCount</code> on only some preferences, that set it both per preference and in <code>ProcessingClusterConfig</code>, or that omit it in both places.</p>
    pub fn set_instance_count(mut self, input: ::std::option::Option<i32>) -> Self {
        self.instance_count = input;
        self
    }
    /// <p>The number of instances to launch if this instance type is selected. Specify the instance count for the processing job in one of the following two ways:</p>
    /// <ol>
    /// <li>
    /// <p><b>Per preference</b> – Set <code>InstanceCount</code> on every preference in the <code>InstancePreferences</code> list and don't set <code>ProcessingClusterConfig$InstanceCount</code>. Use this when each instance type needs a different number of instances to deliver equivalent compute.</p></li>
    /// <li>
    /// <p><b>One count for the job</b> – Set <code>ProcessingClusterConfig$InstanceCount</code> and omit it from every preference. Amazon SageMaker applies this to all instance types in the list.</p></li>
    /// </ol>
    /// <p>For example, in a list of five preferences, either all five specify <code>InstanceCount</code> or none of them do. Amazon SageMaker rejects requests that set <code>InstanceCount</code> on only some preferences, that set it both per preference and in <code>ProcessingClusterConfig</code>, or that omit it in both places.</p>
    pub fn get_instance_count(&self) -> &::std::option::Option<i32> {
        &self.instance_count
    }
    /// Consumes the builder and constructs a [`ProcessingInstancePreference`](crate::types::ProcessingInstancePreference).
    pub fn build(self) -> crate::types::ProcessingInstancePreference {
        crate::types::ProcessingInstancePreference {
            instance_type: self.instance_type,
            instance_count: self.instance_count,
        }
    }
}
