// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct DeleteAttachmentInput {
    /// <p>The unique identifier of the asset from which to delete the attachment.</p>
    pub identifier: ::std::option::Option<::std::string::String>,
    /// <p>The name of the attachment to delete.</p>
    pub attachment_name: ::std::option::Option<::std::string::String>,
}
impl DeleteAttachmentInput {
    /// <p>The unique identifier of the asset from which to delete the attachment.</p>
    pub fn identifier(&self) -> ::std::option::Option<&str> {
        self.identifier.as_deref()
    }
    /// <p>The name of the attachment to delete.</p>
    pub fn attachment_name(&self) -> ::std::option::Option<&str> {
        self.attachment_name.as_deref()
    }
}
impl DeleteAttachmentInput {
    /// Creates a new builder-style object to manufacture [`DeleteAttachmentInput`](crate::operation::delete_attachment::DeleteAttachmentInput).
    pub fn builder() -> crate::operation::delete_attachment::builders::DeleteAttachmentInputBuilder {
        crate::operation::delete_attachment::builders::DeleteAttachmentInputBuilder::default()
    }
}

/// A builder for [`DeleteAttachmentInput`](crate::operation::delete_attachment::DeleteAttachmentInput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct DeleteAttachmentInputBuilder {
    pub(crate) identifier: ::std::option::Option<::std::string::String>,
    pub(crate) attachment_name: ::std::option::Option<::std::string::String>,
}
impl DeleteAttachmentInputBuilder {
    /// <p>The unique identifier of the asset from which to delete the attachment.</p>
    /// This field is required.
    pub fn identifier(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.identifier = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The unique identifier of the asset from which to delete the attachment.</p>
    pub fn set_identifier(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.identifier = input;
        self
    }
    /// <p>The unique identifier of the asset from which to delete the attachment.</p>
    pub fn get_identifier(&self) -> &::std::option::Option<::std::string::String> {
        &self.identifier
    }
    /// <p>The name of the attachment to delete.</p>
    /// This field is required.
    pub fn attachment_name(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.attachment_name = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The name of the attachment to delete.</p>
    pub fn set_attachment_name(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.attachment_name = input;
        self
    }
    /// <p>The name of the attachment to delete.</p>
    pub fn get_attachment_name(&self) -> &::std::option::Option<::std::string::String> {
        &self.attachment_name
    }
    /// Consumes the builder and constructs a [`DeleteAttachmentInput`](crate::operation::delete_attachment::DeleteAttachmentInput).
    pub fn build(
        self,
    ) -> ::std::result::Result<crate::operation::delete_attachment::DeleteAttachmentInput, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(crate::operation::delete_attachment::DeleteAttachmentInput {
            identifier: self.identifier,
            attachment_name: self.attachment_name,
        })
    }
}
