// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_s3_retention(
    input: &crate::types::S3Retention,
    writer: ::aws_smithy_xml::encode::ElWriter,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    if let Some(var_1) = &input.retain_until_date {
        let mut inner_writer = scope.start_el("RetainUntilDate").finish();
        inner_writer.data(var_1.fmt(::aws_smithy_types::date_time::Format::DateTimeWithOffset)?.as_ref());
    }
    if let Some(var_2) = &input.mode {
        let mut inner_writer = scope.start_el("Mode").finish();
        inner_writer.data(var_2.as_str());
    }
    if let Some(var_3) = &input.event_hold {
        let mut inner_writer = scope.start_el("EventHold").finish();
        inner_writer.data(var_3.as_str());
    }
    if let Some(var_4) = &input.event_hold_duration {
        let inner_writer = scope.start_el("EventHoldDuration");
        crate::protocol_serde::shape_s3_object_lock_retention_event_hold_duration::ser_s3_object_lock_retention_event_hold_duration(
            var_4,
            inner_writer,
        )?
    }
    scope.finish();
    Ok(())
}

#[allow(clippy::needless_question_mark)]
pub fn de_s3_retention(
    decoder: &mut ::aws_smithy_xml::decode::ScopedDecoder,
    depth: u32,
) -> ::std::result::Result<crate::types::S3Retention, ::aws_smithy_xml::decode::XmlDecodeError> {
    if depth >= 128u32 {
        return Err(::aws_smithy_xml::decode::XmlDecodeError::custom("maximum nesting depth exceeded"));
    }
    #[allow(unused_mut)]
    let mut builder = crate::types::S3Retention::builder();
    while let Some(mut tag) = decoder.next_tag() {
        match tag.start_el() {
            s if s.matches("RetainUntilDate") /* RetainUntilDate com.amazonaws.s3control#S3Retention$RetainUntilDate */ =>  {
                let var_5 =
                    Some(
                        ::aws_smithy_types::DateTime::from_str(
                            ::aws_smithy_xml::decode::try_data(&mut tag)?.as_ref()
                            , ::aws_smithy_types::date_time::Format::DateTimeWithOffset
                        )
                        .map_err(|_|::aws_smithy_xml::decode::XmlDecodeError::custom("expected (timestamp: `com.amazonaws.s3control#TimeStamp`)"))
                        ?
                    )
                ;
                builder = builder.set_retain_until_date(var_5);
            }
            ,
            s if s.matches("Mode") /* Mode com.amazonaws.s3control#S3Retention$Mode */ =>  {
                let var_6 =
                    Some(
                        Result::<crate::types::S3ObjectLockRetentionMode, ::aws_smithy_xml::decode::XmlDecodeError>::Ok(
                            crate::types::S3ObjectLockRetentionMode::from(
                                ::aws_smithy_xml::decode::try_data(&mut tag)?.as_ref()
                            )
                        )
                        ?
                    )
                ;
                builder = builder.set_mode(var_6);
            }
            ,
            s if s.matches("EventHold") /* EventHold com.amazonaws.s3control#S3Retention$EventHold */ =>  {
                let var_7 =
                    Some(
                        Result::<crate::types::S3ObjectLockRetentionEventHold, ::aws_smithy_xml::decode::XmlDecodeError>::Ok(
                            crate::types::S3ObjectLockRetentionEventHold::from(
                                ::aws_smithy_xml::decode::try_data(&mut tag)?.as_ref()
                            )
                        )
                        ?
                    )
                ;
                builder = builder.set_event_hold(var_7);
            }
            ,
            s if s.matches("EventHoldDuration") /* EventHoldDuration com.amazonaws.s3control#S3Retention$EventHoldDuration */ =>  {
                let var_8 =
                    Some(
                        crate::protocol_serde::shape_s3_object_lock_retention_event_hold_duration::de_s3_object_lock_retention_event_hold_duration(&mut tag, depth + 1)
                        ?
                    )
                ;
                builder = builder.set_event_hold_duration(var_8);
            }
            ,
            _ => {}
        }
    }
    Ok(builder.build())
}
