// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>Contains metadata for a supplier configured within a procurement portal.</p>
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct ProcurementPortalSupplier {
    /// <p>The unique identifier of the supplier within the procurement portal.</p>
    pub supplier_identifier: ::std::string::String,
    /// <p>The Amazon Web Services seller of record associated with the supplier—the Amazon Web Services legal entity that issues invoices for the account (for example, <code>AWS_INC</code> or <code>AWS_EUROPE</code>).</p>
    pub seller_of_record: ::std::option::Option<::std::string::String>,
    /// <p>The two-letter ISO 3166-1 alpha-2 country code associated with the supplier.</p>
    pub country_code: ::std::option::Option<::std::string::String>,
    /// <p>The environment identifier for the supplier in the procurement portal. PROD for production env, or TEST for sandbox/test env.</p>
    pub environment: ::std::option::Option<crate::types::ProcurementPortalEnv>,
}
impl ProcurementPortalSupplier {
    /// <p>The unique identifier of the supplier within the procurement portal.</p>
    pub fn supplier_identifier(&self) -> &str {
        use std::ops::Deref;
        self.supplier_identifier.deref()
    }
    /// <p>The Amazon Web Services seller of record associated with the supplier—the Amazon Web Services legal entity that issues invoices for the account (for example, <code>AWS_INC</code> or <code>AWS_EUROPE</code>).</p>
    pub fn seller_of_record(&self) -> ::std::option::Option<&str> {
        self.seller_of_record.as_deref()
    }
    /// <p>The two-letter ISO 3166-1 alpha-2 country code associated with the supplier.</p>
    pub fn country_code(&self) -> ::std::option::Option<&str> {
        self.country_code.as_deref()
    }
    /// <p>The environment identifier for the supplier in the procurement portal. PROD for production env, or TEST for sandbox/test env.</p>
    pub fn environment(&self) -> ::std::option::Option<&crate::types::ProcurementPortalEnv> {
        self.environment.as_ref()
    }
}
impl ProcurementPortalSupplier {
    /// Creates a new builder-style object to manufacture [`ProcurementPortalSupplier`](crate::types::ProcurementPortalSupplier).
    pub fn builder() -> crate::types::builders::ProcurementPortalSupplierBuilder {
        crate::types::builders::ProcurementPortalSupplierBuilder::default()
    }
}

/// A builder for [`ProcurementPortalSupplier`](crate::types::ProcurementPortalSupplier).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct ProcurementPortalSupplierBuilder {
    pub(crate) supplier_identifier: ::std::option::Option<::std::string::String>,
    pub(crate) seller_of_record: ::std::option::Option<::std::string::String>,
    pub(crate) country_code: ::std::option::Option<::std::string::String>,
    pub(crate) environment: ::std::option::Option<crate::types::ProcurementPortalEnv>,
}
impl ProcurementPortalSupplierBuilder {
    /// <p>The unique identifier of the supplier within the procurement portal.</p>
    /// This field is required.
    pub fn supplier_identifier(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.supplier_identifier = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The unique identifier of the supplier within the procurement portal.</p>
    pub fn set_supplier_identifier(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.supplier_identifier = input;
        self
    }
    /// <p>The unique identifier of the supplier within the procurement portal.</p>
    pub fn get_supplier_identifier(&self) -> &::std::option::Option<::std::string::String> {
        &self.supplier_identifier
    }
    /// <p>The Amazon Web Services seller of record associated with the supplier—the Amazon Web Services legal entity that issues invoices for the account (for example, <code>AWS_INC</code> or <code>AWS_EUROPE</code>).</p>
    pub fn seller_of_record(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.seller_of_record = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The Amazon Web Services seller of record associated with the supplier—the Amazon Web Services legal entity that issues invoices for the account (for example, <code>AWS_INC</code> or <code>AWS_EUROPE</code>).</p>
    pub fn set_seller_of_record(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.seller_of_record = input;
        self
    }
    /// <p>The Amazon Web Services seller of record associated with the supplier—the Amazon Web Services legal entity that issues invoices for the account (for example, <code>AWS_INC</code> or <code>AWS_EUROPE</code>).</p>
    pub fn get_seller_of_record(&self) -> &::std::option::Option<::std::string::String> {
        &self.seller_of_record
    }
    /// <p>The two-letter ISO 3166-1 alpha-2 country code associated with the supplier.</p>
    pub fn country_code(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.country_code = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The two-letter ISO 3166-1 alpha-2 country code associated with the supplier.</p>
    pub fn set_country_code(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.country_code = input;
        self
    }
    /// <p>The two-letter ISO 3166-1 alpha-2 country code associated with the supplier.</p>
    pub fn get_country_code(&self) -> &::std::option::Option<::std::string::String> {
        &self.country_code
    }
    /// <p>The environment identifier for the supplier in the procurement portal. PROD for production env, or TEST for sandbox/test env.</p>
    pub fn environment(mut self, input: crate::types::ProcurementPortalEnv) -> Self {
        self.environment = ::std::option::Option::Some(input);
        self
    }
    /// <p>The environment identifier for the supplier in the procurement portal. PROD for production env, or TEST for sandbox/test env.</p>
    pub fn set_environment(mut self, input: ::std::option::Option<crate::types::ProcurementPortalEnv>) -> Self {
        self.environment = input;
        self
    }
    /// <p>The environment identifier for the supplier in the procurement portal. PROD for production env, or TEST for sandbox/test env.</p>
    pub fn get_environment(&self) -> &::std::option::Option<crate::types::ProcurementPortalEnv> {
        &self.environment
    }
    /// Consumes the builder and constructs a [`ProcurementPortalSupplier`](crate::types::ProcurementPortalSupplier).
    /// This method will fail if any of the following fields are not set:
    /// - [`supplier_identifier`](crate::types::builders::ProcurementPortalSupplierBuilder::supplier_identifier)
    pub fn build(self) -> ::std::result::Result<crate::types::ProcurementPortalSupplier, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(crate::types::ProcurementPortalSupplier {
            supplier_identifier: self.supplier_identifier.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "supplier_identifier",
                    "supplier_identifier was not specified but it is required when building ProcurementPortalSupplier",
                )
            })?,
            seller_of_record: self.seller_of_record,
            country_code: self.country_code,
            environment: self.environment,
        })
    }
}
