// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_rules_search_filter(
    object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::types::RulesSearchFilter,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    if let Some(var_1) = &input.attribute_filter {
        #[allow(unused_mut)]
        let mut object_2 = object.key("AttributeFilter").start_object();
        crate::protocol_serde::shape_rule_attribute_filter::ser_rule_attribute_filter(&mut object_2, var_1)?;
        object_2.finish();
    }
    Ok(())
}
