// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_update_compute_node_group_slurm_configuration_request(
    object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::types::UpdateComputeNodeGroupSlurmConfigurationRequest,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    if let Some(var_1) = &input.scale_down_idle_time_in_seconds {
        object.key("scaleDownIdleTimeInSeconds").number(
            #[allow(clippy::useless_conversion)]
            ::aws_smithy_types::Number::NegInt((*var_1).into()),
        );
    }
    if let Some(var_2) = &input.slurm_custom_settings {
        let mut array_3 = object.key("slurmCustomSettings").start_array();
        for item_4 in var_2 {
            {
                #[allow(unused_mut)]
                let mut object_5 = array_3.value().start_object();
                crate::protocol_serde::shape_slurm_custom_setting::ser_slurm_custom_setting(&mut object_5, item_4)?;
                object_5.finish();
            }
        }
        array_3.finish();
    }
    if let Some(var_6) = &input.gres_custom_settings {
        let mut array_7 = object.key("gresCustomSettings").start_array();
        for item_8 in var_6 {
            {
                #[allow(unused_mut)]
                let mut object_9 = array_7.value().start_object();
                for (key_10, value_11) in item_8 {
                    {
                        object_9.key(key_10.as_str()).string(value_11.as_str());
                    }
                }
                object_9.finish();
            }
        }
        array_7.finish();
    }
    Ok(())
}
