// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>The default session parameters for the multicast group.</p>
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct DefaultSessionParametersMulticast {
    /// <p>Downlink data rate.</p>
    pub dl_dr: ::std::option::Option<i32>,
    /// <p>Downlink frequency.</p>
    pub dl_freq: ::std::option::Option<i32>,
}
impl DefaultSessionParametersMulticast {
    /// <p>Downlink data rate.</p>
    pub fn dl_dr(&self) -> ::std::option::Option<i32> {
        self.dl_dr
    }
    /// <p>Downlink frequency.</p>
    pub fn dl_freq(&self) -> ::std::option::Option<i32> {
        self.dl_freq
    }
}
impl DefaultSessionParametersMulticast {
    /// Creates a new builder-style object to manufacture [`DefaultSessionParametersMulticast`](crate::types::DefaultSessionParametersMulticast).
    pub fn builder() -> crate::types::builders::DefaultSessionParametersMulticastBuilder {
        crate::types::builders::DefaultSessionParametersMulticastBuilder::default()
    }
}

/// A builder for [`DefaultSessionParametersMulticast`](crate::types::DefaultSessionParametersMulticast).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct DefaultSessionParametersMulticastBuilder {
    pub(crate) dl_dr: ::std::option::Option<i32>,
    pub(crate) dl_freq: ::std::option::Option<i32>,
}
impl DefaultSessionParametersMulticastBuilder {
    /// <p>Downlink data rate.</p>
    pub fn dl_dr(mut self, input: i32) -> Self {
        self.dl_dr = ::std::option::Option::Some(input);
        self
    }
    /// <p>Downlink data rate.</p>
    pub fn set_dl_dr(mut self, input: ::std::option::Option<i32>) -> Self {
        self.dl_dr = input;
        self
    }
    /// <p>Downlink data rate.</p>
    pub fn get_dl_dr(&self) -> &::std::option::Option<i32> {
        &self.dl_dr
    }
    /// <p>Downlink frequency.</p>
    pub fn dl_freq(mut self, input: i32) -> Self {
        self.dl_freq = ::std::option::Option::Some(input);
        self
    }
    /// <p>Downlink frequency.</p>
    pub fn set_dl_freq(mut self, input: ::std::option::Option<i32>) -> Self {
        self.dl_freq = input;
        self
    }
    /// <p>Downlink frequency.</p>
    pub fn get_dl_freq(&self) -> &::std::option::Option<i32> {
        &self.dl_freq
    }
    /// Consumes the builder and constructs a [`DefaultSessionParametersMulticast`](crate::types::DefaultSessionParametersMulticast).
    pub fn build(self) -> crate::types::DefaultSessionParametersMulticast {
        crate::types::DefaultSessionParametersMulticast {
            dl_dr: self.dl_dr,
            dl_freq: self.dl_freq,
        }
    }
}
