// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>The source for initial content when creating a data transformation profile. Specify exactly one variant: a built-in starter profile, an existing profile version to clone, raw profile content, or a sample data file.</p>
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq)]
pub enum CreateDataTransformationProfileSource {
    /// <p>Creates the profile by cloning an existing profile at a specific version.</p>
    ExistingVersionedProfileId(crate::types::ExistingVersionedProfileSource),
    /// <p>Creates the profile from raw profile content that you provide directly. Use this variant for continuous integration and continuous delivery (CI/CD) workflows.</p>
    ProfileMapping(crate::types::ProfileMappingSource),
    /// <p>Creates the profile from a sample data file stored in Amazon S3. Valid only when the source format is Comma-separated values (CSV).</p>
    SampleData(crate::types::SampleDataSource),
    /// <p>Creates the profile from a built-in starter profile. Valid only when the source format is Consolidated Clinical Document Architecture (C-CDA).</p>
    StarterProfile(crate::types::StarterProfileSource),
    /// The `Unknown` variant represents cases where new union variant was received. Consider upgrading the SDK to the latest available version.
    /// An unknown enum variant
    ///
    /// _Note: If you encounter this error, consider upgrading your SDK to the latest version._
    /// The `Unknown` variant represents cases where the server sent a value that wasn't recognized
    /// by the client. This can happen when the server adds new functionality, but the client has not been updated.
    /// To investigate this, consider turning on debug logging to print the raw HTTP response.
    #[non_exhaustive]
    Unknown,
}
impl CreateDataTransformationProfileSource {
    /// Tries to convert the enum instance into [`ExistingVersionedProfileId`](crate::types::CreateDataTransformationProfileSource::ExistingVersionedProfileId), extracting the inner [`ExistingVersionedProfileSource`](crate::types::ExistingVersionedProfileSource).
    /// Returns `Err(&Self)` if it can't be converted.
    pub fn as_existing_versioned_profile_id(&self) -> ::std::result::Result<&crate::types::ExistingVersionedProfileSource, &Self> {
        if let CreateDataTransformationProfileSource::ExistingVersionedProfileId(val) = &self {
            ::std::result::Result::Ok(val)
        } else {
            ::std::result::Result::Err(self)
        }
    }
    /// Returns true if this is a [`ExistingVersionedProfileId`](crate::types::CreateDataTransformationProfileSource::ExistingVersionedProfileId).
    pub fn is_existing_versioned_profile_id(&self) -> bool {
        self.as_existing_versioned_profile_id().is_ok()
    }
    /// Tries to convert the enum instance into [`ProfileMapping`](crate::types::CreateDataTransformationProfileSource::ProfileMapping), extracting the inner [`ProfileMappingSource`](crate::types::ProfileMappingSource).
    /// Returns `Err(&Self)` if it can't be converted.
    pub fn as_profile_mapping(&self) -> ::std::result::Result<&crate::types::ProfileMappingSource, &Self> {
        if let CreateDataTransformationProfileSource::ProfileMapping(val) = &self {
            ::std::result::Result::Ok(val)
        } else {
            ::std::result::Result::Err(self)
        }
    }
    /// Returns true if this is a [`ProfileMapping`](crate::types::CreateDataTransformationProfileSource::ProfileMapping).
    pub fn is_profile_mapping(&self) -> bool {
        self.as_profile_mapping().is_ok()
    }
    /// Tries to convert the enum instance into [`SampleData`](crate::types::CreateDataTransformationProfileSource::SampleData), extracting the inner [`SampleDataSource`](crate::types::SampleDataSource).
    /// Returns `Err(&Self)` if it can't be converted.
    pub fn as_sample_data(&self) -> ::std::result::Result<&crate::types::SampleDataSource, &Self> {
        if let CreateDataTransformationProfileSource::SampleData(val) = &self {
            ::std::result::Result::Ok(val)
        } else {
            ::std::result::Result::Err(self)
        }
    }
    /// Returns true if this is a [`SampleData`](crate::types::CreateDataTransformationProfileSource::SampleData).
    pub fn is_sample_data(&self) -> bool {
        self.as_sample_data().is_ok()
    }
    /// Tries to convert the enum instance into [`StarterProfile`](crate::types::CreateDataTransformationProfileSource::StarterProfile), extracting the inner [`StarterProfileSource`](crate::types::StarterProfileSource).
    /// Returns `Err(&Self)` if it can't be converted.
    pub fn as_starter_profile(&self) -> ::std::result::Result<&crate::types::StarterProfileSource, &Self> {
        if let CreateDataTransformationProfileSource::StarterProfile(val) = &self {
            ::std::result::Result::Ok(val)
        } else {
            ::std::result::Result::Err(self)
        }
    }
    /// Returns true if this is a [`StarterProfile`](crate::types::CreateDataTransformationProfileSource::StarterProfile).
    pub fn is_starter_profile(&self) -> bool {
        self.as_starter_profile().is_ok()
    }
    /// Returns true if the enum instance is the `Unknown` variant.
    pub fn is_unknown(&self) -> bool {
        matches!(self, Self::Unknown)
    }
}
impl ::std::fmt::Debug for CreateDataTransformationProfileSource {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match self {
            CreateDataTransformationProfileSource::ExistingVersionedProfileId(val) => {
                f.debug_tuple("ExistingVersionedProfileId").field(&val).finish()
            }
            CreateDataTransformationProfileSource::ProfileMapping(_) => f.debug_tuple("*** Sensitive Data Redacted ***").finish(),
            CreateDataTransformationProfileSource::SampleData(val) => f.debug_tuple("SampleData").field(&val).finish(),
            CreateDataTransformationProfileSource::StarterProfile(val) => f.debug_tuple("StarterProfile").field(&val).finish(),
            CreateDataTransformationProfileSource::Unknown => f.debug_tuple("Unknown").finish(),
        }
    }
}
