// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>Identifies a built-in starter profile to use as the source when creating a data transformation profile. Valid only when the source format is Consolidated Clinical Document Architecture (C-CDA).</p>
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct StarterProfileSource {
    /// <p>The name of the built-in starter profile.</p>
    pub starter_profile_name: ::std::string::String,
}
impl StarterProfileSource {
    /// <p>The name of the built-in starter profile.</p>
    pub fn starter_profile_name(&self) -> &str {
        use std::ops::Deref;
        self.starter_profile_name.deref()
    }
}
impl StarterProfileSource {
    /// Creates a new builder-style object to manufacture [`StarterProfileSource`](crate::types::StarterProfileSource).
    pub fn builder() -> crate::types::builders::StarterProfileSourceBuilder {
        crate::types::builders::StarterProfileSourceBuilder::default()
    }
}

/// A builder for [`StarterProfileSource`](crate::types::StarterProfileSource).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct StarterProfileSourceBuilder {
    pub(crate) starter_profile_name: ::std::option::Option<::std::string::String>,
}
impl StarterProfileSourceBuilder {
    /// <p>The name of the built-in starter profile.</p>
    /// This field is required.
    pub fn starter_profile_name(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.starter_profile_name = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The name of the built-in starter profile.</p>
    pub fn set_starter_profile_name(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.starter_profile_name = input;
        self
    }
    /// <p>The name of the built-in starter profile.</p>
    pub fn get_starter_profile_name(&self) -> &::std::option::Option<::std::string::String> {
        &self.starter_profile_name
    }
    /// Consumes the builder and constructs a [`StarterProfileSource`](crate::types::StarterProfileSource).
    /// This method will fail if any of the following fields are not set:
    /// - [`starter_profile_name`](crate::types::builders::StarterProfileSourceBuilder::starter_profile_name)
    pub fn build(self) -> ::std::result::Result<crate::types::StarterProfileSource, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(crate::types::StarterProfileSource {
            starter_profile_name: self.starter_profile_name.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "starter_profile_name",
                    "starter_profile_name was not specified but it is required when building StarterProfileSource",
                )
            })?,
        })
    }
}
