// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`VerifyProcurementPortalValidation`](crate::operation::verify_procurement_portal_validation::builders::VerifyProcurementPortalValidationFluentBuilder) operation.
    ///
    /// - The fluent builder is configurable:
    ///   - [`procurement_portal_preference_arn(impl Into<String>)`](crate::operation::verify_procurement_portal_validation::builders::VerifyProcurementPortalValidationFluentBuilder::procurement_portal_preference_arn) / [`set_procurement_portal_preference_arn(Option<String>)`](crate::operation::verify_procurement_portal_validation::builders::VerifyProcurementPortalValidationFluentBuilder::set_procurement_portal_preference_arn):<br>required: **true**<br><p>The Amazon Resource Name (ARN) of the procurement portal preference to validate.</p><br>
    ///   - [`code(impl Into<String>)`](crate::operation::verify_procurement_portal_validation::builders::VerifyProcurementPortalValidationFluentBuilder::code) / [`set_code(Option<String>)`](crate::operation::verify_procurement_portal_validation::builders::VerifyProcurementPortalValidationFluentBuilder::set_code):<br>required: **true**<br><p>The validation code received from the procurement portal in response to a previous <code>SendProcurementPortalValidation</code> request.</p><br>
    ///   - [`client_token(impl Into<String>)`](crate::operation::verify_procurement_portal_validation::builders::VerifyProcurementPortalValidationFluentBuilder::client_token) / [`set_client_token(Option<String>)`](crate::operation::verify_procurement_portal_validation::builders::VerifyProcurementPortalValidationFluentBuilder::set_client_token):<br>required: **false**<br><p>A unique, case-sensitive identifier that you provide to ensure idempotency of the request.</p><br>
    /// - On success, responds with [`VerifyProcurementPortalValidationOutput`](crate::operation::verify_procurement_portal_validation::VerifyProcurementPortalValidationOutput) with field(s):
    ///   - [`procurement_portal_preference_arn(String)`](crate::operation::verify_procurement_portal_validation::VerifyProcurementPortalValidationOutput::procurement_portal_preference_arn): <p>The Amazon Resource Name (ARN) of the procurement portal preference for which validation was completed.</p>
    /// - On failure, responds with [`SdkError<VerifyProcurementPortalValidationError>`](crate::operation::verify_procurement_portal_validation::VerifyProcurementPortalValidationError)
    pub fn verify_procurement_portal_validation(
        &self,
    ) -> crate::operation::verify_procurement_portal_validation::builders::VerifyProcurementPortalValidationFluentBuilder {
        crate::operation::verify_procurement_portal_validation::builders::VerifyProcurementPortalValidationFluentBuilder::new(self.handle.clone())
    }
}
