// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>Describes a custom error response for a Lightsail distribution. A custom error response specifies the page that the distribution returns to the viewer. It also specifies the HTTP status code that the distribution sends when the origin responds with a given HTTP error code.</p>
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct DistributionCustomErrorResponse {
    /// <p>The HTTP error code from the origin that triggers the custom error response (for example, <code>403</code> or <code>404</code>).</p>
    pub error_code: ::std::option::Option<i32>,
    /// <p>The HTTP status code that the distribution returns to the viewer for the custom error response.</p>
    pub response_code: ::std::option::Option<::std::string::String>,
    /// <p>The path to the custom error page that the distribution returns to the viewer (for example, <code>/404.html</code>). The path must begin with a forward slash (<code>/</code>) and reference an object that is available from the origin.</p>
    pub response_page_path: ::std::option::Option<::std::string::String>,
    /// <p>The minimum time, in seconds, that the distribution caches the custom error response before requesting the object again from the origin. If you don't specify a value, the default is <code>10</code> seconds.</p>
    pub error_caching_min_ttl: ::std::option::Option<i64>,
}
impl DistributionCustomErrorResponse {
    /// <p>The HTTP error code from the origin that triggers the custom error response (for example, <code>403</code> or <code>404</code>).</p>
    pub fn error_code(&self) -> ::std::option::Option<i32> {
        self.error_code
    }
    /// <p>The HTTP status code that the distribution returns to the viewer for the custom error response.</p>
    pub fn response_code(&self) -> ::std::option::Option<&str> {
        self.response_code.as_deref()
    }
    /// <p>The path to the custom error page that the distribution returns to the viewer (for example, <code>/404.html</code>). The path must begin with a forward slash (<code>/</code>) and reference an object that is available from the origin.</p>
    pub fn response_page_path(&self) -> ::std::option::Option<&str> {
        self.response_page_path.as_deref()
    }
    /// <p>The minimum time, in seconds, that the distribution caches the custom error response before requesting the object again from the origin. If you don't specify a value, the default is <code>10</code> seconds.</p>
    pub fn error_caching_min_ttl(&self) -> ::std::option::Option<i64> {
        self.error_caching_min_ttl
    }
}
impl DistributionCustomErrorResponse {
    /// Creates a new builder-style object to manufacture [`DistributionCustomErrorResponse`](crate::types::DistributionCustomErrorResponse).
    pub fn builder() -> crate::types::builders::DistributionCustomErrorResponseBuilder {
        crate::types::builders::DistributionCustomErrorResponseBuilder::default()
    }
}

/// A builder for [`DistributionCustomErrorResponse`](crate::types::DistributionCustomErrorResponse).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct DistributionCustomErrorResponseBuilder {
    pub(crate) error_code: ::std::option::Option<i32>,
    pub(crate) response_code: ::std::option::Option<::std::string::String>,
    pub(crate) response_page_path: ::std::option::Option<::std::string::String>,
    pub(crate) error_caching_min_ttl: ::std::option::Option<i64>,
}
impl DistributionCustomErrorResponseBuilder {
    /// <p>The HTTP error code from the origin that triggers the custom error response (for example, <code>403</code> or <code>404</code>).</p>
    pub fn error_code(mut self, input: i32) -> Self {
        self.error_code = ::std::option::Option::Some(input);
        self
    }
    /// <p>The HTTP error code from the origin that triggers the custom error response (for example, <code>403</code> or <code>404</code>).</p>
    pub fn set_error_code(mut self, input: ::std::option::Option<i32>) -> Self {
        self.error_code = input;
        self
    }
    /// <p>The HTTP error code from the origin that triggers the custom error response (for example, <code>403</code> or <code>404</code>).</p>
    pub fn get_error_code(&self) -> &::std::option::Option<i32> {
        &self.error_code
    }
    /// <p>The HTTP status code that the distribution returns to the viewer for the custom error response.</p>
    pub fn response_code(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.response_code = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The HTTP status code that the distribution returns to the viewer for the custom error response.</p>
    pub fn set_response_code(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.response_code = input;
        self
    }
    /// <p>The HTTP status code that the distribution returns to the viewer for the custom error response.</p>
    pub fn get_response_code(&self) -> &::std::option::Option<::std::string::String> {
        &self.response_code
    }
    /// <p>The path to the custom error page that the distribution returns to the viewer (for example, <code>/404.html</code>). The path must begin with a forward slash (<code>/</code>) and reference an object that is available from the origin.</p>
    pub fn response_page_path(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.response_page_path = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The path to the custom error page that the distribution returns to the viewer (for example, <code>/404.html</code>). The path must begin with a forward slash (<code>/</code>) and reference an object that is available from the origin.</p>
    pub fn set_response_page_path(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.response_page_path = input;
        self
    }
    /// <p>The path to the custom error page that the distribution returns to the viewer (for example, <code>/404.html</code>). The path must begin with a forward slash (<code>/</code>) and reference an object that is available from the origin.</p>
    pub fn get_response_page_path(&self) -> &::std::option::Option<::std::string::String> {
        &self.response_page_path
    }
    /// <p>The minimum time, in seconds, that the distribution caches the custom error response before requesting the object again from the origin. If you don't specify a value, the default is <code>10</code> seconds.</p>
    pub fn error_caching_min_ttl(mut self, input: i64) -> Self {
        self.error_caching_min_ttl = ::std::option::Option::Some(input);
        self
    }
    /// <p>The minimum time, in seconds, that the distribution caches the custom error response before requesting the object again from the origin. If you don't specify a value, the default is <code>10</code> seconds.</p>
    pub fn set_error_caching_min_ttl(mut self, input: ::std::option::Option<i64>) -> Self {
        self.error_caching_min_ttl = input;
        self
    }
    /// <p>The minimum time, in seconds, that the distribution caches the custom error response before requesting the object again from the origin. If you don't specify a value, the default is <code>10</code> seconds.</p>
    pub fn get_error_caching_min_ttl(&self) -> &::std::option::Option<i64> {
        &self.error_caching_min_ttl
    }
    /// Consumes the builder and constructs a [`DistributionCustomErrorResponse`](crate::types::DistributionCustomErrorResponse).
    pub fn build(self) -> crate::types::DistributionCustomErrorResponse {
        crate::types::DistributionCustomErrorResponse {
            error_code: self.error_code,
            response_code: self.response_code,
            response_page_path: self.response_page_path,
            error_caching_min_ttl: self.error_caching_min_ttl,
        }
    }
}
