// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>Describes the origin resource of an Amazon Lightsail content delivery network (CDN) distribution.</p>
/// <p>An origin can be a Lightsail instance, bucket, or load balancer. A distribution pulls content from an origin, caches it, and serves it to viewers via a worldwide network of edge servers.</p>
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct Origin {
    /// <p>The name of the origin resource.</p>
    pub name: ::std::option::Option<::std::string::String>,
    /// <p>The resource type of the origin resource (<i>Instance</i>).</p>
    pub resource_type: ::std::option::Option<crate::types::ResourceType>,
    /// <p>The AWS Region name of the origin resource.</p>
    pub region_name: ::std::option::Option<crate::types::RegionName>,
    /// <p>The protocol that your Amazon Lightsail distribution uses when establishing a connection with your origin to pull content.</p>
    pub protocol_policy: ::std::option::Option<crate::types::OriginProtocolPolicyEnum>,
    /// <p>The amount of time, in seconds, that the distribution waits for a response after forwarding a request to the origin. The minimum timeout is 1 second, the maximum is 60 seconds, and the default (if you don't specify otherwise) is 30 seconds.</p>
    pub response_timeout: ::std::option::Option<i32>,
    /// <p>The IP address type that the distribution uses when connecting to the origin.</p>
    /// <p>The possible values are <code>ipv4</code> for IPv4 only, <code>ipv6</code> for IPv6 only, and <code>dualstack</code> for IPv4 and IPv6.</p>
    pub ip_address_type: ::std::option::Option<crate::types::OriginIpAddressTypeEnum>,
    /// <p>Specifies whether private origin access is enabled for the distribution's origin. With private origin access, the distribution can serve objects that aren't publicly accessible from a Lightsail bucket.</p>
    /// <p>This applies when you set the bucket's <code>getObject</code> access rule to <code>private</code>. It also applies when you set <code>getObject</code> to <code>public</code> but set individual objects to private.</p>
    pub is_private_origin_access_enabled: ::std::option::Option<bool>,
}
impl Origin {
    /// <p>The name of the origin resource.</p>
    pub fn name(&self) -> ::std::option::Option<&str> {
        self.name.as_deref()
    }
    /// <p>The resource type of the origin resource (<i>Instance</i>).</p>
    pub fn resource_type(&self) -> ::std::option::Option<&crate::types::ResourceType> {
        self.resource_type.as_ref()
    }
    /// <p>The AWS Region name of the origin resource.</p>
    pub fn region_name(&self) -> ::std::option::Option<&crate::types::RegionName> {
        self.region_name.as_ref()
    }
    /// <p>The protocol that your Amazon Lightsail distribution uses when establishing a connection with your origin to pull content.</p>
    pub fn protocol_policy(&self) -> ::std::option::Option<&crate::types::OriginProtocolPolicyEnum> {
        self.protocol_policy.as_ref()
    }
    /// <p>The amount of time, in seconds, that the distribution waits for a response after forwarding a request to the origin. The minimum timeout is 1 second, the maximum is 60 seconds, and the default (if you don't specify otherwise) is 30 seconds.</p>
    pub fn response_timeout(&self) -> ::std::option::Option<i32> {
        self.response_timeout
    }
    /// <p>The IP address type that the distribution uses when connecting to the origin.</p>
    /// <p>The possible values are <code>ipv4</code> for IPv4 only, <code>ipv6</code> for IPv6 only, and <code>dualstack</code> for IPv4 and IPv6.</p>
    pub fn ip_address_type(&self) -> ::std::option::Option<&crate::types::OriginIpAddressTypeEnum> {
        self.ip_address_type.as_ref()
    }
    /// <p>Specifies whether private origin access is enabled for the distribution's origin. With private origin access, the distribution can serve objects that aren't publicly accessible from a Lightsail bucket.</p>
    /// <p>This applies when you set the bucket's <code>getObject</code> access rule to <code>private</code>. It also applies when you set <code>getObject</code> to <code>public</code> but set individual objects to private.</p>
    pub fn is_private_origin_access_enabled(&self) -> ::std::option::Option<bool> {
        self.is_private_origin_access_enabled
    }
}
impl Origin {
    /// Creates a new builder-style object to manufacture [`Origin`](crate::types::Origin).
    pub fn builder() -> crate::types::builders::OriginBuilder {
        crate::types::builders::OriginBuilder::default()
    }
}

/// A builder for [`Origin`](crate::types::Origin).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct OriginBuilder {
    pub(crate) name: ::std::option::Option<::std::string::String>,
    pub(crate) resource_type: ::std::option::Option<crate::types::ResourceType>,
    pub(crate) region_name: ::std::option::Option<crate::types::RegionName>,
    pub(crate) protocol_policy: ::std::option::Option<crate::types::OriginProtocolPolicyEnum>,
    pub(crate) response_timeout: ::std::option::Option<i32>,
    pub(crate) ip_address_type: ::std::option::Option<crate::types::OriginIpAddressTypeEnum>,
    pub(crate) is_private_origin_access_enabled: ::std::option::Option<bool>,
}
impl OriginBuilder {
    /// <p>The name of the origin resource.</p>
    pub fn name(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.name = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The name of the origin resource.</p>
    pub fn set_name(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.name = input;
        self
    }
    /// <p>The name of the origin resource.</p>
    pub fn get_name(&self) -> &::std::option::Option<::std::string::String> {
        &self.name
    }
    /// <p>The resource type of the origin resource (<i>Instance</i>).</p>
    pub fn resource_type(mut self, input: crate::types::ResourceType) -> Self {
        self.resource_type = ::std::option::Option::Some(input);
        self
    }
    /// <p>The resource type of the origin resource (<i>Instance</i>).</p>
    pub fn set_resource_type(mut self, input: ::std::option::Option<crate::types::ResourceType>) -> Self {
        self.resource_type = input;
        self
    }
    /// <p>The resource type of the origin resource (<i>Instance</i>).</p>
    pub fn get_resource_type(&self) -> &::std::option::Option<crate::types::ResourceType> {
        &self.resource_type
    }
    /// <p>The AWS Region name of the origin resource.</p>
    pub fn region_name(mut self, input: crate::types::RegionName) -> Self {
        self.region_name = ::std::option::Option::Some(input);
        self
    }
    /// <p>The AWS Region name of the origin resource.</p>
    pub fn set_region_name(mut self, input: ::std::option::Option<crate::types::RegionName>) -> Self {
        self.region_name = input;
        self
    }
    /// <p>The AWS Region name of the origin resource.</p>
    pub fn get_region_name(&self) -> &::std::option::Option<crate::types::RegionName> {
        &self.region_name
    }
    /// <p>The protocol that your Amazon Lightsail distribution uses when establishing a connection with your origin to pull content.</p>
    pub fn protocol_policy(mut self, input: crate::types::OriginProtocolPolicyEnum) -> Self {
        self.protocol_policy = ::std::option::Option::Some(input);
        self
    }
    /// <p>The protocol that your Amazon Lightsail distribution uses when establishing a connection with your origin to pull content.</p>
    pub fn set_protocol_policy(mut self, input: ::std::option::Option<crate::types::OriginProtocolPolicyEnum>) -> Self {
        self.protocol_policy = input;
        self
    }
    /// <p>The protocol that your Amazon Lightsail distribution uses when establishing a connection with your origin to pull content.</p>
    pub fn get_protocol_policy(&self) -> &::std::option::Option<crate::types::OriginProtocolPolicyEnum> {
        &self.protocol_policy
    }
    /// <p>The amount of time, in seconds, that the distribution waits for a response after forwarding a request to the origin. The minimum timeout is 1 second, the maximum is 60 seconds, and the default (if you don't specify otherwise) is 30 seconds.</p>
    pub fn response_timeout(mut self, input: i32) -> Self {
        self.response_timeout = ::std::option::Option::Some(input);
        self
    }
    /// <p>The amount of time, in seconds, that the distribution waits for a response after forwarding a request to the origin. The minimum timeout is 1 second, the maximum is 60 seconds, and the default (if you don't specify otherwise) is 30 seconds.</p>
    pub fn set_response_timeout(mut self, input: ::std::option::Option<i32>) -> Self {
        self.response_timeout = input;
        self
    }
    /// <p>The amount of time, in seconds, that the distribution waits for a response after forwarding a request to the origin. The minimum timeout is 1 second, the maximum is 60 seconds, and the default (if you don't specify otherwise) is 30 seconds.</p>
    pub fn get_response_timeout(&self) -> &::std::option::Option<i32> {
        &self.response_timeout
    }
    /// <p>The IP address type that the distribution uses when connecting to the origin.</p>
    /// <p>The possible values are <code>ipv4</code> for IPv4 only, <code>ipv6</code> for IPv6 only, and <code>dualstack</code> for IPv4 and IPv6.</p>
    pub fn ip_address_type(mut self, input: crate::types::OriginIpAddressTypeEnum) -> Self {
        self.ip_address_type = ::std::option::Option::Some(input);
        self
    }
    /// <p>The IP address type that the distribution uses when connecting to the origin.</p>
    /// <p>The possible values are <code>ipv4</code> for IPv4 only, <code>ipv6</code> for IPv6 only, and <code>dualstack</code> for IPv4 and IPv6.</p>
    pub fn set_ip_address_type(mut self, input: ::std::option::Option<crate::types::OriginIpAddressTypeEnum>) -> Self {
        self.ip_address_type = input;
        self
    }
    /// <p>The IP address type that the distribution uses when connecting to the origin.</p>
    /// <p>The possible values are <code>ipv4</code> for IPv4 only, <code>ipv6</code> for IPv6 only, and <code>dualstack</code> for IPv4 and IPv6.</p>
    pub fn get_ip_address_type(&self) -> &::std::option::Option<crate::types::OriginIpAddressTypeEnum> {
        &self.ip_address_type
    }
    /// <p>Specifies whether private origin access is enabled for the distribution's origin. With private origin access, the distribution can serve objects that aren't publicly accessible from a Lightsail bucket.</p>
    /// <p>This applies when you set the bucket's <code>getObject</code> access rule to <code>private</code>. It also applies when you set <code>getObject</code> to <code>public</code> but set individual objects to private.</p>
    pub fn is_private_origin_access_enabled(mut self, input: bool) -> Self {
        self.is_private_origin_access_enabled = ::std::option::Option::Some(input);
        self
    }
    /// <p>Specifies whether private origin access is enabled for the distribution's origin. With private origin access, the distribution can serve objects that aren't publicly accessible from a Lightsail bucket.</p>
    /// <p>This applies when you set the bucket's <code>getObject</code> access rule to <code>private</code>. It also applies when you set <code>getObject</code> to <code>public</code> but set individual objects to private.</p>
    pub fn set_is_private_origin_access_enabled(mut self, input: ::std::option::Option<bool>) -> Self {
        self.is_private_origin_access_enabled = input;
        self
    }
    /// <p>Specifies whether private origin access is enabled for the distribution's origin. With private origin access, the distribution can serve objects that aren't publicly accessible from a Lightsail bucket.</p>
    /// <p>This applies when you set the bucket's <code>getObject</code> access rule to <code>private</code>. It also applies when you set <code>getObject</code> to <code>public</code> but set individual objects to private.</p>
    pub fn get_is_private_origin_access_enabled(&self) -> &::std::option::Option<bool> {
        &self.is_private_origin_access_enabled
    }
    /// Consumes the builder and constructs a [`Origin`](crate::types::Origin).
    pub fn build(self) -> crate::types::Origin {
        crate::types::Origin {
            name: self.name,
            resource_type: self.resource_type,
            region_name: self.region_name,
            protocol_policy: self.protocol_policy,
            response_timeout: self.response_timeout,
            ip_address_type: self.ip_address_type,
            is_private_origin_access_enabled: self.is_private_origin_access_enabled,
        }
    }
}
