// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`AttachClusterNodeNetworkInterface`](crate::operation::attach_cluster_node_network_interface::builders::AttachClusterNodeNetworkInterfaceFluentBuilder) operation.
    ///
    /// - The fluent builder is configurable:
    ///   - [`cluster_name(impl Into<String>)`](crate::operation::attach_cluster_node_network_interface::builders::AttachClusterNodeNetworkInterfaceFluentBuilder::cluster_name) / [`set_cluster_name(Option<String>)`](crate::operation::attach_cluster_node_network_interface::builders::AttachClusterNodeNetworkInterfaceFluentBuilder::set_cluster_name):<br>required: **true**<br><p>The name or Amazon Resource Name (ARN) of the SageMaker HyperPod cluster that contains the target node.</p><br>
    ///   - [`node_id(impl Into<String>)`](crate::operation::attach_cluster_node_network_interface::builders::AttachClusterNodeNetworkInterfaceFluentBuilder::node_id) / [`set_node_id(Option<String>)`](crate::operation::attach_cluster_node_network_interface::builders::AttachClusterNodeNetworkInterfaceFluentBuilder::set_node_id):<br>required: **true**<br><p>The unique identifier of the cluster node to which you want to attach the network interface. The node must belong to your specified HyperPod cluster and cannot be part of a Restricted Instance Group (RIG).</p><br>
    ///   - [`network_interface_id(impl Into<String>)`](crate::operation::attach_cluster_node_network_interface::builders::AttachClusterNodeNetworkInterfaceFluentBuilder::network_interface_id) / [`set_network_interface_id(Option<String>)`](crate::operation::attach_cluster_node_network_interface::builders::AttachClusterNodeNetworkInterfaceFluentBuilder::set_network_interface_id):<br>required: **true**<br><p>The unique identifier of the elastic network interface (ENI) to attach.</p><br>
    /// - On success, responds with [`AttachClusterNodeNetworkInterfaceOutput`](crate::operation::attach_cluster_node_network_interface::AttachClusterNodeNetworkInterfaceOutput) with field(s):
    ///   - [`cluster_arn(Option<String>)`](crate::operation::attach_cluster_node_network_interface::AttachClusterNodeNetworkInterfaceOutput::cluster_arn): <p>The Amazon Resource Name (ARN) of your SageMaker HyperPod cluster where the network interface attachment operation was performed.</p>
    ///   - [`node_id(Option<String>)`](crate::operation::attach_cluster_node_network_interface::AttachClusterNodeNetworkInterfaceOutput::node_id): <p>The unique identifier of the cluster node where your network interface was attached.</p>
    ///   - [`network_interface_id(Option<String>)`](crate::operation::attach_cluster_node_network_interface::AttachClusterNodeNetworkInterfaceOutput::network_interface_id): <p>The unique identifier of the elastic network interface (ENI) that was attached.</p>
    ///   - [`attachment_id(Option<String>)`](crate::operation::attach_cluster_node_network_interface::AttachClusterNodeNetworkInterfaceOutput::attachment_id): <p>The unique identifier of the network interface attachment. Use this value to reference or detach the network interface later.</p>
    /// - On failure, responds with [`SdkError<AttachClusterNodeNetworkInterfaceError>`](crate::operation::attach_cluster_node_network_interface::AttachClusterNodeNetworkInterfaceError)
    pub fn attach_cluster_node_network_interface(
        &self,
    ) -> crate::operation::attach_cluster_node_network_interface::builders::AttachClusterNodeNetworkInterfaceFluentBuilder {
        crate::operation::attach_cluster_node_network_interface::builders::AttachClusterNodeNetworkInterfaceFluentBuilder::new(self.handle.clone())
    }
}
