// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct GetFeedPolicyInput {
    /// <p>The ID of the feed whose policy you want to retrieve.</p>
    pub id: ::std::option::Option<::std::string::String>,
}
impl GetFeedPolicyInput {
    /// <p>The ID of the feed whose policy you want to retrieve.</p>
    pub fn id(&self) -> ::std::option::Option<&str> {
        self.id.as_deref()
    }
}
impl GetFeedPolicyInput {
    /// Creates a new builder-style object to manufacture [`GetFeedPolicyInput`](crate::operation::get_feed_policy::GetFeedPolicyInput).
    pub fn builder() -> crate::operation::get_feed_policy::builders::GetFeedPolicyInputBuilder {
        crate::operation::get_feed_policy::builders::GetFeedPolicyInputBuilder::default()
    }
}

/// A builder for [`GetFeedPolicyInput`](crate::operation::get_feed_policy::GetFeedPolicyInput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct GetFeedPolicyInputBuilder {
    pub(crate) id: ::std::option::Option<::std::string::String>,
}
impl GetFeedPolicyInputBuilder {
    /// <p>The ID of the feed whose policy you want to retrieve.</p>
    /// This field is required.
    pub fn id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.id = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The ID of the feed whose policy you want to retrieve.</p>
    pub fn set_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.id = input;
        self
    }
    /// <p>The ID of the feed whose policy you want to retrieve.</p>
    pub fn get_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.id
    }
    /// Consumes the builder and constructs a [`GetFeedPolicyInput`](crate::operation::get_feed_policy::GetFeedPolicyInput).
    pub fn build(
        self,
    ) -> ::std::result::Result<crate::operation::get_feed_policy::GetFeedPolicyInput, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(crate::operation::get_feed_policy::GetFeedPolicyInput { id: self.id })
    }
}
