// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(unused_mut)]
pub fn ser_fleet_instance_metadata_options_request(
    mut writer: ::aws_smithy_query::QueryValueWriter,
    input: &crate::types::FleetInstanceMetadataOptionsRequest,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    #[allow(unused_mut)]
    let mut scope_1 = writer.prefix("HttpTokens");
    if let Some(var_2) = &input.http_tokens {
        scope_1.string(var_2.as_str());
    }
    #[allow(unused_mut)]
    let mut scope_3 = writer.prefix("HttpPutResponseHopLimit");
    if let Some(var_4) = &input.http_put_response_hop_limit {
        scope_3.number(
            #[allow(clippy::useless_conversion)]
            ::aws_smithy_types::Number::NegInt((*var_4).into()),
        );
    }
    #[allow(unused_mut)]
    let mut scope_5 = writer.prefix("HttpEndpoint");
    if let Some(var_6) = &input.http_endpoint {
        scope_5.string(var_6.as_str());
    }
    Ok(())
}
