// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_list_bill_estimate_commitments_input_input(
    encoder: &mut ::aws_smithy_cbor::Encoder,
    #[allow(unused)] input: &crate::operation::list_bill_estimate_commitments::ListBillEstimateCommitmentsInput,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    encoder.begin_map();
    if let Some(var_1) = &input.bill_estimate_id {
        encoder.str("billEstimateId").str(var_1.as_str());
    }
    if let Some(var_2) = &input.next_token {
        encoder.str("nextToken").str(var_2.as_str());
    }
    if let Some(var_3) = &input.max_results {
        encoder.str("maxResults").integer(*var_3);
    }
    encoder.end();
    Ok(())
}
