// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(clippy::unnecessary_wraps)]
pub fn de_update_bill_estimate_http_error(
    _response_status: u16,
    _response_headers: &::aws_smithy_runtime_api::http::Headers,
    _response_body: &[u8],
) -> std::result::Result<
    crate::operation::update_bill_estimate::UpdateBillEstimateOutput,
    crate::operation::update_bill_estimate::UpdateBillEstimateError,
> {
    #[allow(unused_mut)]
    let mut generic_builder = crate::cbor_errors::parse_error_metadata(_response_status, _response_headers, _response_body)
        .map_err(crate::operation::update_bill_estimate::UpdateBillEstimateError::unhandled)?;
    generic_builder = ::aws_types::request_id::apply_request_id(generic_builder, _response_headers);
    let generic = generic_builder.build();
    let error_code = match generic.code() {
        Some(code) => code,
        None => return Err(crate::operation::update_bill_estimate::UpdateBillEstimateError::unhandled(generic)),
    };

    let _error_message = generic.message().map(|msg| msg.to_owned());
    Err(match error_code {
        "ConflictException" => crate::operation::update_bill_estimate::UpdateBillEstimateError::ConflictException({
            #[allow(unused_mut)]
            let mut tmp = {
                #[allow(unused_mut)]
                let mut output = crate::types::error::builders::ConflictExceptionBuilder::default();
                output = crate::protocol_serde::shape_conflict_exception::de_conflict_exception_cbor_err(_response_body, output)
                    .map_err(crate::operation::update_bill_estimate::UpdateBillEstimateError::unhandled)?;
                let output = output.meta(generic);
                crate::serde_util::conflict_exception_correct_errors(output)
                    .build()
                    .map_err(crate::operation::update_bill_estimate::UpdateBillEstimateError::unhandled)?
            };
            tmp
        }),
        "DataUnavailableException" => crate::operation::update_bill_estimate::UpdateBillEstimateError::DataUnavailableException({
            #[allow(unused_mut)]
            let mut tmp = {
                #[allow(unused_mut)]
                let mut output = crate::types::error::builders::DataUnavailableExceptionBuilder::default();
                output = crate::protocol_serde::shape_data_unavailable_exception::de_data_unavailable_exception_cbor_err(_response_body, output)
                    .map_err(crate::operation::update_bill_estimate::UpdateBillEstimateError::unhandled)?;
                let output = output.meta(generic);
                crate::serde_util::data_unavailable_exception_correct_errors(output)
                    .build()
                    .map_err(crate::operation::update_bill_estimate::UpdateBillEstimateError::unhandled)?
            };
            tmp
        }),
        "ResourceNotFoundException" => crate::operation::update_bill_estimate::UpdateBillEstimateError::ResourceNotFoundException({
            #[allow(unused_mut)]
            let mut tmp = {
                #[allow(unused_mut)]
                let mut output = crate::types::error::builders::ResourceNotFoundExceptionBuilder::default();
                output = crate::protocol_serde::shape_resource_not_found_exception::de_resource_not_found_exception_cbor_err(_response_body, output)
                    .map_err(crate::operation::update_bill_estimate::UpdateBillEstimateError::unhandled)?;
                let output = output.meta(generic);
                crate::serde_util::resource_not_found_exception_correct_errors(output)
                    .build()
                    .map_err(crate::operation::update_bill_estimate::UpdateBillEstimateError::unhandled)?
            };
            tmp
        }),
        "AccessDeniedException" => crate::operation::update_bill_estimate::UpdateBillEstimateError::AccessDeniedException({
            #[allow(unused_mut)]
            let mut tmp = {
                #[allow(unused_mut)]
                let mut output = crate::types::error::builders::AccessDeniedExceptionBuilder::default();
                output = crate::protocol_serde::shape_access_denied_exception::de_access_denied_exception_cbor_err(_response_body, output)
                    .map_err(crate::operation::update_bill_estimate::UpdateBillEstimateError::unhandled)?;
                let output = output.meta(generic);
                crate::serde_util::access_denied_exception_correct_errors(output)
                    .build()
                    .map_err(crate::operation::update_bill_estimate::UpdateBillEstimateError::unhandled)?
            };
            tmp
        }),
        "InternalServerException" => crate::operation::update_bill_estimate::UpdateBillEstimateError::InternalServerException({
            #[allow(unused_mut)]
            let mut tmp = {
                #[allow(unused_mut)]
                let mut output = crate::types::error::builders::InternalServerExceptionBuilder::default();
                output = crate::protocol_serde::shape_internal_server_exception::de_internal_server_exception_cbor_err(_response_body, output)
                    .map_err(crate::operation::update_bill_estimate::UpdateBillEstimateError::unhandled)?;
                let output = output.meta(generic);
                crate::serde_util::internal_server_exception_correct_errors(output)
                    .build()
                    .map_err(crate::operation::update_bill_estimate::UpdateBillEstimateError::unhandled)?
            };
            tmp
        }),
        "ThrottlingException" => crate::operation::update_bill_estimate::UpdateBillEstimateError::ThrottlingException({
            #[allow(unused_mut)]
            let mut tmp = {
                #[allow(unused_mut)]
                let mut output = crate::types::error::builders::ThrottlingExceptionBuilder::default();
                output = crate::protocol_serde::shape_throttling_exception::de_throttling_exception_cbor_err(_response_body, output)
                    .map_err(crate::operation::update_bill_estimate::UpdateBillEstimateError::unhandled)?;
                let output = output.meta(generic);
                crate::serde_util::throttling_exception_correct_errors(output)
                    .build()
                    .map_err(crate::operation::update_bill_estimate::UpdateBillEstimateError::unhandled)?
            };
            tmp
        }),
        "ValidationException" => crate::operation::update_bill_estimate::UpdateBillEstimateError::ValidationException({
            #[allow(unused_mut)]
            let mut tmp = {
                #[allow(unused_mut)]
                let mut output = crate::types::error::builders::ValidationExceptionBuilder::default();
                output = crate::protocol_serde::shape_validation_exception::de_validation_exception_cbor_err(_response_body, output)
                    .map_err(crate::operation::update_bill_estimate::UpdateBillEstimateError::unhandled)?;
                let output = output.meta(generic);
                crate::serde_util::validation_exception_correct_errors(output)
                    .build()
                    .map_err(crate::operation::update_bill_estimate::UpdateBillEstimateError::unhandled)?
            };
            tmp
        }),
        _ => crate::operation::update_bill_estimate::UpdateBillEstimateError::generic(generic),
    })
}

#[allow(clippy::unnecessary_wraps)]
pub fn de_update_bill_estimate_http_response(
    _response_status: u16,
    _response_headers: &::aws_smithy_runtime_api::http::Headers,
    _response_body: &[u8],
) -> std::result::Result<
    crate::operation::update_bill_estimate::UpdateBillEstimateOutput,
    crate::operation::update_bill_estimate::UpdateBillEstimateError,
> {
    Ok({
        #[allow(unused_mut)]
        let mut output = crate::operation::update_bill_estimate::builders::UpdateBillEstimateOutputBuilder::default();
        output = crate::protocol_serde::shape_update_bill_estimate::de_update_bill_estimate(_response_body, output)
            .map_err(crate::operation::update_bill_estimate::UpdateBillEstimateError::unhandled)?;
        output._set_request_id(::aws_types::request_id::RequestId::request_id(_response_headers).map(str::to_string));
        crate::serde_util::update_bill_estimate_output_output_correct_errors(output)
            .build()
            .map_err(crate::operation::update_bill_estimate::UpdateBillEstimateError::unhandled)?
    })
}

pub fn ser_update_bill_estimate_input(
    input: &crate::operation::update_bill_estimate::UpdateBillEstimateInput,
) -> ::std::result::Result<::aws_smithy_types::body::SdkBody, ::aws_smithy_types::error::operation::SerializationError> {
    let mut encoder = ::aws_smithy_cbor::Encoder::new(Vec::new());
    {
        let encoder = &mut encoder;
        crate::protocol_serde::shape_update_bill_estimate_input::ser_update_bill_estimate_input_input(encoder, input)?;
    }
    Ok(::aws_smithy_types::body::SdkBody::from(encoder.into_writer()))
}

pub(crate) fn de_update_bill_estimate(
    value: &[u8],
    mut builder: crate::operation::update_bill_estimate::builders::UpdateBillEstimateOutputBuilder,
) -> ::std::result::Result<
    crate::operation::update_bill_estimate::builders::UpdateBillEstimateOutputBuilder,
    ::aws_smithy_cbor::decode::DeserializeError,
> {
    #[allow(clippy::match_single_binding, unused_variables)]
    fn pair(
        mut builder: crate::operation::update_bill_estimate::builders::UpdateBillEstimateOutputBuilder,
        decoder: &mut ::aws_smithy_cbor::Decoder,
        depth: u32,
    ) -> ::std::result::Result<
        crate::operation::update_bill_estimate::builders::UpdateBillEstimateOutputBuilder,
        ::aws_smithy_cbor::decode::DeserializeError,
    > {
        builder =
            match decoder.str()?.as_ref() {
                "id" => builder.set_id(Some(decoder.string()?)),
                "name" => {
                    ::aws_smithy_cbor::decode::set_optional(builder, decoder, |builder, decoder| Ok(builder.set_name(Some(decoder.string()?))))?
                }
                "status" => ::aws_smithy_cbor::decode::set_optional(builder, decoder, |builder, decoder| {
                    Ok(builder.set_status(Some(decoder.string().map(|s| crate::types::BillEstimateStatus::from(s.as_ref()))?)))
                })?,
                "failureMessage" => ::aws_smithy_cbor::decode::set_optional(builder, decoder, |builder, decoder| {
                    Ok(builder.set_failure_message(Some(decoder.string()?)))
                })?,
                "billInterval" => ::aws_smithy_cbor::decode::set_optional(builder, decoder, |builder, decoder| {
                    Ok(builder.set_bill_interval(Some(crate::protocol_serde::shape_bill_interval::de_bill_interval(decoder, depth + 1)?)))
                })?,
                "costSummary" => ::aws_smithy_cbor::decode::set_optional(builder, decoder, |builder, decoder| {
                    Ok(builder.set_cost_summary(Some(
                        crate::protocol_serde::shape_bill_estimate_cost_summary::de_bill_estimate_cost_summary(decoder, depth + 1)?,
                    )))
                })?,
                "createdAt" => ::aws_smithy_cbor::decode::set_optional(builder, decoder, |builder, decoder| {
                    Ok(builder.set_created_at(Some(decoder.timestamp()?)))
                })?,
                "expiresAt" => ::aws_smithy_cbor::decode::set_optional(builder, decoder, |builder, decoder| {
                    Ok(builder.set_expires_at(Some(decoder.timestamp()?)))
                })?,
                "groupSharingPreference" => ::aws_smithy_cbor::decode::set_optional(builder, decoder, |builder, decoder| {
                    Ok(builder.set_group_sharing_preference(Some(
                        decoder.string().map(|s| crate::types::GroupSharingPreferenceEnum::from(s.as_ref()))?,
                    )))
                })?,
                "costCategoryGroupSharingPreferenceArn" => ::aws_smithy_cbor::decode::set_optional(builder, decoder, |builder, decoder| {
                    Ok(builder.set_cost_category_group_sharing_preference_arn(Some(decoder.string()?)))
                })?,
                "costCategoryGroupSharingPreferenceEffectiveDate" => {
                    ::aws_smithy_cbor::decode::set_optional(builder, decoder, |builder, decoder| {
                        Ok(builder.set_cost_category_group_sharing_preference_effective_date(Some(decoder.timestamp()?)))
                    })?
                }
                _ => {
                    decoder.skip()?;
                    builder
                }
            };
        Ok(builder)
    }

    let decoder = &mut ::aws_smithy_cbor::Decoder::new(value);
    #[allow(unused_variables)]
    let depth = 0u32;

    match decoder.map()? {
        None => loop {
            match decoder.datatype()? {
                ::aws_smithy_cbor::data::Type::Break => {
                    decoder.skip()?;
                    break;
                }
                _ => {
                    builder = pair(builder, decoder, depth)?;
                }
            };
        },
        Some(n) => {
            for _ in 0..n {
                builder = pair(builder, decoder, depth)?;
            }
        }
    };

    if decoder.position() != value.len() {
        return Err(::aws_smithy_cbor::decode::DeserializeError::expected_end_of_stream(decoder.position()));
    }

    Ok(builder)
}
