// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_bill_scenario_commitment_modification_action(
    encoder: &mut ::aws_smithy_cbor::Encoder,
    input: &crate::types::BillScenarioCommitmentModificationAction,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    encoder.map(1);
    match input {
        crate::types::BillScenarioCommitmentModificationAction::AddReservedInstanceAction(inner) => {
            encoder.str("addReservedInstanceAction");
            crate::protocol_serde::shape_add_reserved_instance_action::ser_add_reserved_instance_action(encoder, inner)?;
        }
        crate::types::BillScenarioCommitmentModificationAction::AddSavingsPlanAction(inner) => {
            encoder.str("addSavingsPlanAction");
            crate::protocol_serde::shape_add_savings_plan_action::ser_add_savings_plan_action(encoder, inner)?;
        }
        crate::types::BillScenarioCommitmentModificationAction::NegateReservedInstanceAction(inner) => {
            encoder.str("negateReservedInstanceAction");
            crate::protocol_serde::shape_negate_reserved_instance_action::ser_negate_reserved_instance_action(encoder, inner)?;
        }
        crate::types::BillScenarioCommitmentModificationAction::NegateSavingsPlanAction(inner) => {
            encoder.str("negateSavingsPlanAction");
            crate::protocol_serde::shape_negate_savings_plan_action::ser_negate_savings_plan_action(encoder, inner)?;
        }
        crate::types::BillScenarioCommitmentModificationAction::Unknown => {
            return ::std::result::Result::Err(::aws_smithy_types::error::operation::SerializationError::unknown_variant(
                "BillScenarioCommitmentModificationAction",
            ))
        }
    }
    ::std::result::Result::Ok(())
}

pub(crate) fn de_bill_scenario_commitment_modification_action(
    decoder: &mut ::aws_smithy_cbor::Decoder,
    depth: u32,
) -> ::std::result::Result<crate::types::BillScenarioCommitmentModificationAction, ::aws_smithy_cbor::decode::DeserializeError> {
    if depth >= 128u32 {
        return Err(::aws_smithy_cbor::decode::DeserializeError::custom(
            "maximum nesting depth exceeded",
            decoder.position(),
        ));
    }

    #[allow(unused_variables)]
    fn pair(
        decoder: &mut ::aws_smithy_cbor::Decoder,
        depth: u32,
    ) -> ::std::result::Result<crate::types::BillScenarioCommitmentModificationAction, ::aws_smithy_cbor::decode::DeserializeError> {
        Ok(match decoder.str()?.as_ref() {
            "addReservedInstanceAction" => crate::types::BillScenarioCommitmentModificationAction::AddReservedInstanceAction(
                crate::protocol_serde::shape_add_reserved_instance_action::de_add_reserved_instance_action(decoder, depth + 1)?,
            ),
            "addSavingsPlanAction" => crate::types::BillScenarioCommitmentModificationAction::AddSavingsPlanAction(
                crate::protocol_serde::shape_add_savings_plan_action::de_add_savings_plan_action(decoder, depth + 1)?,
            ),
            "negateReservedInstanceAction" => crate::types::BillScenarioCommitmentModificationAction::NegateReservedInstanceAction(
                crate::protocol_serde::shape_negate_reserved_instance_action::de_negate_reserved_instance_action(decoder, depth + 1)?,
            ),
            "negateSavingsPlanAction" => crate::types::BillScenarioCommitmentModificationAction::NegateSavingsPlanAction(
                crate::protocol_serde::shape_negate_savings_plan_action::de_negate_savings_plan_action(decoder, depth + 1)?,
            ),
            _ => {
                decoder.skip()?;
                crate::types::BillScenarioCommitmentModificationAction::Unknown
            }
        })
    }

    match decoder.map()? {
        None => {
            let variant = pair(decoder, depth)?;
            match decoder.datatype()? {
                ::aws_smithy_cbor::data::Type::Break => {
                    decoder.skip()?;
                    Ok(variant)
                }
                ty => Err(::aws_smithy_cbor::decode::DeserializeError::unexpected_union_variant(
                    ty,
                    decoder.position(),
                )),
            }
        }
        Some(1) => pair(decoder, depth),
        Some(_) => Err(::aws_smithy_cbor::decode::DeserializeError::mixed_union_variants(decoder.position())),
    }
}
