// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_batch_delete_bill_scenario_usage_modification_input_input(
    encoder: &mut ::aws_smithy_cbor::Encoder,
    #[allow(unused)] input: &crate::operation::batch_delete_bill_scenario_usage_modification::BatchDeleteBillScenarioUsageModificationInput,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    encoder.begin_map();
    if let Some(var_1) = &input.bill_scenario_id {
        encoder.str("billScenarioId").str(var_1.as_str());
    }
    if let Some(var_2) = &input.ids {
        encoder.str("ids");
        encoder.array((*var_2).len());
        for item_3 in var_2 {
            {
                encoder.str(item_3.as_str());
            }
        }
    }
    encoder.end();
    Ok(())
}
