// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_batch_update_bill_scenario_usage_modification_entry(
    encoder: &mut ::aws_smithy_cbor::Encoder,
    #[allow(unused)] input: &crate::types::BatchUpdateBillScenarioUsageModificationEntry,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    encoder.begin_map();
    {
        encoder.str("id").str(input.id.as_str());
    }
    if let Some(var_1) = &input.group {
        encoder.str("group").str(var_1.as_str());
    }
    if let Some(var_2) = &input.amounts {
        encoder.str("amounts");
        encoder.array((*var_2).len());
        for item_3 in var_2 {
            {
                crate::protocol_serde::shape_usage_amount::ser_usage_amount(encoder, item_3)?;
            }
        }
    }
    encoder.end();
    Ok(())
}
