// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_expression(
    encoder: &mut ::aws_smithy_cbor::Encoder,
    #[allow(unused)] input: &crate::types::Expression,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    encoder.begin_map();
    if let Some(var_1) = &input.and {
        encoder.str("and");
        encoder.array((*var_1).len());
        for item_2 in var_1 {
            {
                crate::protocol_serde::shape_expression::ser_expression(encoder, item_2)?;
            }
        }
    }
    if let Some(var_3) = &input.or {
        encoder.str("or");
        encoder.array((*var_3).len());
        for item_4 in var_3 {
            {
                crate::protocol_serde::shape_expression::ser_expression(encoder, item_4)?;
            }
        }
    }
    if let Some(var_5) = &input.not {
        encoder.str("not");
        crate::protocol_serde::shape_expression::ser_expression(encoder, var_5)?;
    }
    if let Some(var_6) = &input.cost_categories {
        encoder.str("costCategories");
        crate::protocol_serde::shape_expression_filter::ser_expression_filter(encoder, var_6)?;
    }
    if let Some(var_7) = &input.dimensions {
        encoder.str("dimensions");
        crate::protocol_serde::shape_expression_filter::ser_expression_filter(encoder, var_7)?;
    }
    if let Some(var_8) = &input.tags {
        encoder.str("tags");
        crate::protocol_serde::shape_expression_filter::ser_expression_filter(encoder, var_8)?;
    }
    encoder.end();
    Ok(())
}

pub(crate) fn de_expression(
    decoder: &mut ::aws_smithy_cbor::Decoder,
    depth: u32,
) -> ::std::result::Result<crate::types::Expression, ::aws_smithy_cbor::decode::DeserializeError> {
    if depth >= 128u32 {
        return Err(::aws_smithy_cbor::decode::DeserializeError::custom(
            "maximum nesting depth exceeded",
            decoder.position(),
        ));
    }
    #[allow(clippy::match_single_binding, unused_variables)]
    fn pair(
        mut builder: crate::types::builders::ExpressionBuilder,
        decoder: &mut ::aws_smithy_cbor::Decoder,
        depth: u32,
    ) -> ::std::result::Result<crate::types::builders::ExpressionBuilder, ::aws_smithy_cbor::decode::DeserializeError> {
        builder = match decoder.str()?.as_ref() {
            "and" => ::aws_smithy_cbor::decode::set_optional(builder, decoder, |builder, decoder| {
                Ok(builder.set_and(Some(crate::protocol_serde::shape_expression_list::de_expression_list(
                    decoder,
                    depth + 1,
                )?)))
            })?,
            "or" => ::aws_smithy_cbor::decode::set_optional(builder, decoder, |builder, decoder| {
                Ok(builder.set_or(Some(crate::protocol_serde::shape_expression_list::de_expression_list(
                    decoder,
                    depth + 1,
                )?)))
            })?,
            "not" => ::aws_smithy_cbor::decode::set_optional(builder, decoder, |builder, decoder| {
                Ok(builder.set_not(Some({
                    let v = crate::protocol_serde::shape_expression::de_expression(decoder, depth + 1)?;
                    Box::new(v)
                })))
            })?,
            "costCategories" => ::aws_smithy_cbor::decode::set_optional(builder, decoder, |builder, decoder| {
                Ok(
                    builder.set_cost_categories(Some(crate::protocol_serde::shape_expression_filter::de_expression_filter(
                        decoder,
                        depth + 1,
                    )?)),
                )
            })?,
            "dimensions" => ::aws_smithy_cbor::decode::set_optional(builder, decoder, |builder, decoder| {
                Ok(
                    builder.set_dimensions(Some(crate::protocol_serde::shape_expression_filter::de_expression_filter(
                        decoder,
                        depth + 1,
                    )?)),
                )
            })?,
            "tags" => ::aws_smithy_cbor::decode::set_optional(builder, decoder, |builder, decoder| {
                Ok(
                    builder.set_tags(Some(crate::protocol_serde::shape_expression_filter::de_expression_filter(
                        decoder,
                        depth + 1,
                    )?)),
                )
            })?,
            _ => {
                decoder.skip()?;
                builder
            }
        };
        Ok(builder)
    }

    let mut builder = crate::types::builders::ExpressionBuilder::default();

    match decoder.map()? {
        None => loop {
            match decoder.datatype()? {
                ::aws_smithy_cbor::data::Type::Break => {
                    decoder.skip()?;
                    break;
                }
                _ => {
                    builder = pair(builder, decoder, depth)?;
                }
            };
        },
        Some(n) => {
            for _ in 0..n {
                builder = pair(builder, decoder, depth)?;
            }
        }
    };
    #[allow(clippy::needless_question_mark)]
    {
        return Ok(builder.build());
    }
}
