// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>The stages of a compute node's lifecycle where you can configure scripts to run.</p>
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct NodeLifecycleStages {
    /// <p>The scripts to run after PCS finishes setting up the compute node and before the Slurm daemon (<code>slurmd</code>) starts. Use this stage for tasks that must complete before the node accepts jobs, such as mounting shared storage, configuring networking, or installing software packages.</p>
    pub node_bootstrapped: ::std::option::Option<::std::vec::Vec<crate::types::NodeLifecycleScript>>,
    /// <p>The scripts to run after the Slurm daemon (<code>slurmd</code>) starts and the compute node registers with the Slurm controller. Use this stage for tasks that require Slurm to be running, such as running Slurm commands.</p>
    pub node_ready: ::std::option::Option<::std::vec::Vec<crate::types::NodeLifecycleScript>>,
}
impl NodeLifecycleStages {
    /// <p>The scripts to run after PCS finishes setting up the compute node and before the Slurm daemon (<code>slurmd</code>) starts. Use this stage for tasks that must complete before the node accepts jobs, such as mounting shared storage, configuring networking, or installing software packages.</p>
    ///
    /// If no value was sent for this field, a default will be set. If you want to determine if no value was sent, use `.node_bootstrapped.is_none()`.
    pub fn node_bootstrapped(&self) -> &[crate::types::NodeLifecycleScript] {
        self.node_bootstrapped.as_deref().unwrap_or_default()
    }
    /// <p>The scripts to run after the Slurm daemon (<code>slurmd</code>) starts and the compute node registers with the Slurm controller. Use this stage for tasks that require Slurm to be running, such as running Slurm commands.</p>
    ///
    /// If no value was sent for this field, a default will be set. If you want to determine if no value was sent, use `.node_ready.is_none()`.
    pub fn node_ready(&self) -> &[crate::types::NodeLifecycleScript] {
        self.node_ready.as_deref().unwrap_or_default()
    }
}
impl NodeLifecycleStages {
    /// Creates a new builder-style object to manufacture [`NodeLifecycleStages`](crate::types::NodeLifecycleStages).
    pub fn builder() -> crate::types::builders::NodeLifecycleStagesBuilder {
        crate::types::builders::NodeLifecycleStagesBuilder::default()
    }
}

/// A builder for [`NodeLifecycleStages`](crate::types::NodeLifecycleStages).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct NodeLifecycleStagesBuilder {
    pub(crate) node_bootstrapped: ::std::option::Option<::std::vec::Vec<crate::types::NodeLifecycleScript>>,
    pub(crate) node_ready: ::std::option::Option<::std::vec::Vec<crate::types::NodeLifecycleScript>>,
}
impl NodeLifecycleStagesBuilder {
    /// Appends an item to `node_bootstrapped`.
    ///
    /// To override the contents of this collection use [`set_node_bootstrapped`](Self::set_node_bootstrapped).
    ///
    /// <p>The scripts to run after PCS finishes setting up the compute node and before the Slurm daemon (<code>slurmd</code>) starts. Use this stage for tasks that must complete before the node accepts jobs, such as mounting shared storage, configuring networking, or installing software packages.</p>
    pub fn node_bootstrapped(mut self, input: crate::types::NodeLifecycleScript) -> Self {
        let mut v = self.node_bootstrapped.unwrap_or_default();
        v.push(input);
        self.node_bootstrapped = ::std::option::Option::Some(v);
        self
    }
    /// <p>The scripts to run after PCS finishes setting up the compute node and before the Slurm daemon (<code>slurmd</code>) starts. Use this stage for tasks that must complete before the node accepts jobs, such as mounting shared storage, configuring networking, or installing software packages.</p>
    pub fn set_node_bootstrapped(mut self, input: ::std::option::Option<::std::vec::Vec<crate::types::NodeLifecycleScript>>) -> Self {
        self.node_bootstrapped = input;
        self
    }
    /// <p>The scripts to run after PCS finishes setting up the compute node and before the Slurm daemon (<code>slurmd</code>) starts. Use this stage for tasks that must complete before the node accepts jobs, such as mounting shared storage, configuring networking, or installing software packages.</p>
    pub fn get_node_bootstrapped(&self) -> &::std::option::Option<::std::vec::Vec<crate::types::NodeLifecycleScript>> {
        &self.node_bootstrapped
    }
    /// Appends an item to `node_ready`.
    ///
    /// To override the contents of this collection use [`set_node_ready`](Self::set_node_ready).
    ///
    /// <p>The scripts to run after the Slurm daemon (<code>slurmd</code>) starts and the compute node registers with the Slurm controller. Use this stage for tasks that require Slurm to be running, such as running Slurm commands.</p>
    pub fn node_ready(mut self, input: crate::types::NodeLifecycleScript) -> Self {
        let mut v = self.node_ready.unwrap_or_default();
        v.push(input);
        self.node_ready = ::std::option::Option::Some(v);
        self
    }
    /// <p>The scripts to run after the Slurm daemon (<code>slurmd</code>) starts and the compute node registers with the Slurm controller. Use this stage for tasks that require Slurm to be running, such as running Slurm commands.</p>
    pub fn set_node_ready(mut self, input: ::std::option::Option<::std::vec::Vec<crate::types::NodeLifecycleScript>>) -> Self {
        self.node_ready = input;
        self
    }
    /// <p>The scripts to run after the Slurm daemon (<code>slurmd</code>) starts and the compute node registers with the Slurm controller. Use this stage for tasks that require Slurm to be running, such as running Slurm commands.</p>
    pub fn get_node_ready(&self) -> &::std::option::Option<::std::vec::Vec<crate::types::NodeLifecycleScript>> {
        &self.node_ready
    }
    /// Consumes the builder and constructs a [`NodeLifecycleStages`](crate::types::NodeLifecycleStages).
    pub fn build(self) -> crate::types::NodeLifecycleStages {
        crate::types::NodeLifecycleStages {
            node_bootstrapped: self.node_bootstrapped,
            node_ready: self.node_ready,
        }
    }
}
