// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct ListResourcesInput {
    /// <p>ARN identifier.</p>
    pub service_arn: ::std::option::Option<::std::string::String>,
    /// <p>Filter resources by service function identifier.</p>
    pub service_function_id: ::std::option::Option<::std::string::String>,
    /// <p>Filter resources by AWS Region.</p>
    pub aws_region: ::std::option::Option<::std::string::String>,
    /// <p>The CloudFormation resource types to include in the response.</p>
    pub resource_types: ::std::option::Option<::std::vec::Vec<::std::string::String>>,
    /// <p>Specifies whether to filter non-billable resources. When true (the default), the operation returns only billable resources.</p>
    pub billable: ::std::option::Option<bool>,
    /// <p>Pagination page size.</p>
    pub max_results: ::std::option::Option<i32>,
    /// <p>Pagination token.</p>
    pub next_token: ::std::option::Option<::std::string::String>,
}
impl ListResourcesInput {
    /// <p>ARN identifier.</p>
    pub fn service_arn(&self) -> ::std::option::Option<&str> {
        self.service_arn.as_deref()
    }
    /// <p>Filter resources by service function identifier.</p>
    pub fn service_function_id(&self) -> ::std::option::Option<&str> {
        self.service_function_id.as_deref()
    }
    /// <p>Filter resources by AWS Region.</p>
    pub fn aws_region(&self) -> ::std::option::Option<&str> {
        self.aws_region.as_deref()
    }
    /// <p>The CloudFormation resource types to include in the response.</p>
    ///
    /// If no value was sent for this field, a default will be set. If you want to determine if no value was sent, use `.resource_types.is_none()`.
    pub fn resource_types(&self) -> &[::std::string::String] {
        self.resource_types.as_deref().unwrap_or_default()
    }
    /// <p>Specifies whether to filter non-billable resources. When true (the default), the operation returns only billable resources.</p>
    pub fn billable(&self) -> ::std::option::Option<bool> {
        self.billable
    }
    /// <p>Pagination page size.</p>
    pub fn max_results(&self) -> ::std::option::Option<i32> {
        self.max_results
    }
    /// <p>Pagination token.</p>
    pub fn next_token(&self) -> ::std::option::Option<&str> {
        self.next_token.as_deref()
    }
}
impl ListResourcesInput {
    /// Creates a new builder-style object to manufacture [`ListResourcesInput`](crate::operation::list_resources::ListResourcesInput).
    pub fn builder() -> crate::operation::list_resources::builders::ListResourcesInputBuilder {
        crate::operation::list_resources::builders::ListResourcesInputBuilder::default()
    }
}

/// A builder for [`ListResourcesInput`](crate::operation::list_resources::ListResourcesInput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct ListResourcesInputBuilder {
    pub(crate) service_arn: ::std::option::Option<::std::string::String>,
    pub(crate) service_function_id: ::std::option::Option<::std::string::String>,
    pub(crate) aws_region: ::std::option::Option<::std::string::String>,
    pub(crate) resource_types: ::std::option::Option<::std::vec::Vec<::std::string::String>>,
    pub(crate) billable: ::std::option::Option<bool>,
    pub(crate) max_results: ::std::option::Option<i32>,
    pub(crate) next_token: ::std::option::Option<::std::string::String>,
}
impl ListResourcesInputBuilder {
    /// <p>ARN identifier.</p>
    /// This field is required.
    pub fn service_arn(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.service_arn = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>ARN identifier.</p>
    pub fn set_service_arn(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.service_arn = input;
        self
    }
    /// <p>ARN identifier.</p>
    pub fn get_service_arn(&self) -> &::std::option::Option<::std::string::String> {
        &self.service_arn
    }
    /// <p>Filter resources by service function identifier.</p>
    pub fn service_function_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.service_function_id = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>Filter resources by service function identifier.</p>
    pub fn set_service_function_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.service_function_id = input;
        self
    }
    /// <p>Filter resources by service function identifier.</p>
    pub fn get_service_function_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.service_function_id
    }
    /// <p>Filter resources by AWS Region.</p>
    pub fn aws_region(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.aws_region = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>Filter resources by AWS Region.</p>
    pub fn set_aws_region(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.aws_region = input;
        self
    }
    /// <p>Filter resources by AWS Region.</p>
    pub fn get_aws_region(&self) -> &::std::option::Option<::std::string::String> {
        &self.aws_region
    }
    /// Appends an item to `resource_types`.
    ///
    /// To override the contents of this collection use [`set_resource_types`](Self::set_resource_types).
    ///
    /// <p>The CloudFormation resource types to include in the response.</p>
    pub fn resource_types(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        let mut v = self.resource_types.unwrap_or_default();
        v.push(input.into());
        self.resource_types = ::std::option::Option::Some(v);
        self
    }
    /// <p>The CloudFormation resource types to include in the response.</p>
    pub fn set_resource_types(mut self, input: ::std::option::Option<::std::vec::Vec<::std::string::String>>) -> Self {
        self.resource_types = input;
        self
    }
    /// <p>The CloudFormation resource types to include in the response.</p>
    pub fn get_resource_types(&self) -> &::std::option::Option<::std::vec::Vec<::std::string::String>> {
        &self.resource_types
    }
    /// <p>Specifies whether to filter non-billable resources. When true (the default), the operation returns only billable resources.</p>
    pub fn billable(mut self, input: bool) -> Self {
        self.billable = ::std::option::Option::Some(input);
        self
    }
    /// <p>Specifies whether to filter non-billable resources. When true (the default), the operation returns only billable resources.</p>
    pub fn set_billable(mut self, input: ::std::option::Option<bool>) -> Self {
        self.billable = input;
        self
    }
    /// <p>Specifies whether to filter non-billable resources. When true (the default), the operation returns only billable resources.</p>
    pub fn get_billable(&self) -> &::std::option::Option<bool> {
        &self.billable
    }
    /// <p>Pagination page size.</p>
    pub fn max_results(mut self, input: i32) -> Self {
        self.max_results = ::std::option::Option::Some(input);
        self
    }
    /// <p>Pagination page size.</p>
    pub fn set_max_results(mut self, input: ::std::option::Option<i32>) -> Self {
        self.max_results = input;
        self
    }
    /// <p>Pagination page size.</p>
    pub fn get_max_results(&self) -> &::std::option::Option<i32> {
        &self.max_results
    }
    /// <p>Pagination token.</p>
    pub fn next_token(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.next_token = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>Pagination token.</p>
    pub fn set_next_token(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.next_token = input;
        self
    }
    /// <p>Pagination token.</p>
    pub fn get_next_token(&self) -> &::std::option::Option<::std::string::String> {
        &self.next_token
    }
    /// Consumes the builder and constructs a [`ListResourcesInput`](crate::operation::list_resources::ListResourcesInput).
    pub fn build(
        self,
    ) -> ::std::result::Result<crate::operation::list_resources::ListResourcesInput, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(crate::operation::list_resources::ListResourcesInput {
            service_arn: self.service_arn,
            service_function_id: self.service_function_id,
            aws_region: self.aws_region,
            resource_types: self.resource_types,
            billable: self.billable,
            max_results: self.max_results,
            next_token: self.next_token,
        })
    }
}
