// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_create_data_transformation_profile_source(
    object_3: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::types::CreateDataTransformationProfileSource,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    match input {
        crate::types::CreateDataTransformationProfileSource::StarterProfile(inner) => {
            #[allow(unused_mut)]
            let mut object_1 = object_3.key("StarterProfile").start_object();
            crate::protocol_serde::shape_starter_profile_source::ser_starter_profile_source(&mut object_1, inner)?;
            object_1.finish();
        }
        crate::types::CreateDataTransformationProfileSource::ExistingVersionedProfileId(inner) => {
            #[allow(unused_mut)]
            let mut object_2 = object_3.key("ExistingVersionedProfileId").start_object();
            crate::protocol_serde::shape_existing_versioned_profile_source::ser_existing_versioned_profile_source(&mut object_2, inner)?;
            object_2.finish();
        }
        crate::types::CreateDataTransformationProfileSource::ProfileMapping(inner) => {
            #[allow(unused_mut)]
            let mut object_3 = object_3.key("ProfileMapping").start_object();
            crate::protocol_serde::shape_profile_mapping_source::ser_profile_mapping_source(&mut object_3, inner)?;
            object_3.finish();
        }
        crate::types::CreateDataTransformationProfileSource::SampleData(inner) => {
            #[allow(unused_mut)]
            let mut object_4 = object_3.key("SampleData").start_object();
            crate::protocol_serde::shape_sample_data_source::ser_sample_data_source(&mut object_4, inner)?;
            object_4.finish();
        }
        crate::types::CreateDataTransformationProfileSource::Unknown => {
            return Err(::aws_smithy_types::error::operation::SerializationError::unknown_variant(
                "CreateDataTransformationProfileSource",
            ))
        }
    }
    Ok(())
}
