// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct DeleteQev2IdcApplicationInput {
    /// <p>The Amazon Resource Name (ARN) for the Amazon Redshift Query Editor (QEV2) IAM Identity Center application to delete.</p>
    pub qev2_idc_application_arn: ::std::option::Option<::std::string::String>,
}
impl DeleteQev2IdcApplicationInput {
    /// <p>The Amazon Resource Name (ARN) for the Amazon Redshift Query Editor (QEV2) IAM Identity Center application to delete.</p>
    pub fn qev2_idc_application_arn(&self) -> ::std::option::Option<&str> {
        self.qev2_idc_application_arn.as_deref()
    }
}
impl DeleteQev2IdcApplicationInput {
    /// Creates a new builder-style object to manufacture [`DeleteQev2IdcApplicationInput`](crate::operation::delete_qev2_idc_application::DeleteQev2IdcApplicationInput).
    pub fn builder() -> crate::operation::delete_qev2_idc_application::builders::DeleteQev2IdcApplicationInputBuilder {
        crate::operation::delete_qev2_idc_application::builders::DeleteQev2IdcApplicationInputBuilder::default()
    }
}

/// A builder for [`DeleteQev2IdcApplicationInput`](crate::operation::delete_qev2_idc_application::DeleteQev2IdcApplicationInput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct DeleteQev2IdcApplicationInputBuilder {
    pub(crate) qev2_idc_application_arn: ::std::option::Option<::std::string::String>,
}
impl DeleteQev2IdcApplicationInputBuilder {
    /// <p>The Amazon Resource Name (ARN) for the Amazon Redshift Query Editor (QEV2) IAM Identity Center application to delete.</p>
    /// This field is required.
    pub fn qev2_idc_application_arn(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.qev2_idc_application_arn = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The Amazon Resource Name (ARN) for the Amazon Redshift Query Editor (QEV2) IAM Identity Center application to delete.</p>
    pub fn set_qev2_idc_application_arn(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.qev2_idc_application_arn = input;
        self
    }
    /// <p>The Amazon Resource Name (ARN) for the Amazon Redshift Query Editor (QEV2) IAM Identity Center application to delete.</p>
    pub fn get_qev2_idc_application_arn(&self) -> &::std::option::Option<::std::string::String> {
        &self.qev2_idc_application_arn
    }
    /// Consumes the builder and constructs a [`DeleteQev2IdcApplicationInput`](crate::operation::delete_qev2_idc_application::DeleteQev2IdcApplicationInput).
    pub fn build(
        self,
    ) -> ::std::result::Result<
        crate::operation::delete_qev2_idc_application::DeleteQev2IdcApplicationInput,
        ::aws_smithy_types::error::operation::BuildError,
    > {
        ::std::result::Result::Ok(crate::operation::delete_qev2_idc_application::DeleteQev2IdcApplicationInput {
            qev2_idc_application_arn: self.qev2_idc_application_arn,
        })
    }
}
