// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_update_application_input_input(
    encoder: &mut ::aws_smithy_cbor::Encoder,
    #[allow(unused)] input: &crate::operation::update_application::UpdateApplicationInput,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    encoder.begin_map();
    if let Some(var_1) = &input.name {
        encoder.str("Name").str(var_1.as_str());
    }
    if let Some(var_2) = &input.display_name {
        encoder.str("DisplayName").str(var_2.as_str());
    }
    if let Some(var_3) = &input.description {
        encoder.str("Description").str(var_3.as_str());
    }
    if let Some(var_4) = &input.icon_s3_location {
        encoder.str("IconS3Location");
        crate::protocol_serde::shape_s3_location::ser_s3_location(encoder, var_4)?;
    }
    if let Some(var_5) = &input.launch_path {
        encoder.str("LaunchPath").str(var_5.as_str());
    }
    if let Some(var_6) = &input.working_directory {
        encoder.str("WorkingDirectory").str(var_6.as_str());
    }
    if let Some(var_7) = &input.launch_parameters {
        encoder.str("LaunchParameters").str(var_7.as_str());
    }
    if let Some(var_8) = &input.app_block_arn {
        encoder.str("AppBlockArn").str(var_8.as_str());
    }
    if let Some(var_9) = &input.attributes_to_delete {
        encoder.str("AttributesToDelete");
        encoder.array((*var_9).len());
        for item_10 in var_9 {
            {
                encoder.str(item_10.as_str());
            }
        }
    }
    encoder.end();
    Ok(())
}
