// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_list_entitled_applications_input_input(
    encoder: &mut ::aws_smithy_cbor::Encoder,
    #[allow(unused)] input: &crate::operation::list_entitled_applications::ListEntitledApplicationsInput,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    encoder.begin_map();
    if let Some(var_1) = &input.stack_name {
        encoder.str("StackName").str(var_1.as_str());
    }
    if let Some(var_2) = &input.entitlement_name {
        encoder.str("EntitlementName").str(var_2.as_str());
    }
    if let Some(var_3) = &input.next_token {
        encoder.str("NextToken").str(var_3.as_str());
    }
    if let Some(var_4) = &input.max_results {
        encoder.str("MaxResults").integer(*var_4);
    }
    encoder.end();
    Ok(())
}
