// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_disable_user_input_input(
    encoder: &mut ::aws_smithy_cbor::Encoder,
    #[allow(unused)] input: &crate::operation::disable_user::DisableUserInput,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    encoder.begin_map();
    if let Some(var_1) = &input.user_name {
        encoder.str("UserName").str(var_1.as_str());
    }
    if let Some(var_2) = &input.authentication_type {
        encoder.str("AuthenticationType").str(var_2.as_str());
    }
    encoder.end();
    Ok(())
}
