// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_describe_sessions_input_input(
    encoder: &mut ::aws_smithy_cbor::Encoder,
    #[allow(unused)] input: &crate::operation::describe_sessions::DescribeSessionsInput,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    encoder.begin_map();
    if let Some(var_1) = &input.stack_name {
        encoder.str("StackName").str(var_1.as_str());
    }
    if let Some(var_2) = &input.fleet_name {
        encoder.str("FleetName").str(var_2.as_str());
    }
    if let Some(var_3) = &input.user_id {
        encoder.str("UserId").str(var_3.as_str());
    }
    if let Some(var_4) = &input.next_token {
        encoder.str("NextToken").str(var_4.as_str());
    }
    if let Some(var_5) = &input.limit {
        encoder.str("Limit").integer(*var_5);
    }
    if let Some(var_6) = &input.authentication_type {
        encoder.str("AuthenticationType").str(var_6.as_str());
    }
    if let Some(var_7) = &input.instance_id {
        encoder.str("InstanceId").str(var_7.as_str());
    }
    encoder.end();
    Ok(())
}
