// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_associate_software_to_image_builder_input_input(
    encoder: &mut ::aws_smithy_cbor::Encoder,
    #[allow(unused)] input: &crate::operation::associate_software_to_image_builder::AssociateSoftwareToImageBuilderInput,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    encoder.begin_map();
    if let Some(var_1) = &input.image_builder_name {
        encoder.str("ImageBuilderName").str(var_1.as_str());
    }
    if let Some(var_2) = &input.software_names {
        encoder.str("SoftwareNames");
        encoder.array((*var_2).len());
        for item_3 in var_2 {
            {
                encoder.str(item_3.as_str());
            }
        }
    }
    encoder.end();
    Ok(())
}
