// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_compute_capacity(
    encoder: &mut ::aws_smithy_cbor::Encoder,
    #[allow(unused)] input: &crate::types::ComputeCapacity,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    encoder.begin_map();
    if let Some(var_1) = &input.desired_instances {
        encoder.str("DesiredInstances").integer(*var_1);
    }
    if let Some(var_2) = &input.desired_sessions {
        encoder.str("DesiredSessions").integer(*var_2);
    }
    encoder.end();
    Ok(())
}
