// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_update_app_block_builder_input_input(
    encoder: &mut ::aws_smithy_cbor::Encoder,
    #[allow(unused)] input: &crate::operation::update_app_block_builder::UpdateAppBlockBuilderInput,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    encoder.begin_map();
    if let Some(var_1) = &input.name {
        encoder.str("Name").str(var_1.as_str());
    }
    if let Some(var_2) = &input.description {
        encoder.str("Description").str(var_2.as_str());
    }
    if let Some(var_3) = &input.display_name {
        encoder.str("DisplayName").str(var_3.as_str());
    }
    if let Some(var_4) = &input.platform {
        encoder.str("Platform").str(var_4.as_str());
    }
    if let Some(var_5) = &input.instance_type {
        encoder.str("InstanceType").str(var_5.as_str());
    }
    if let Some(var_6) = &input.vpc_config {
        encoder.str("VpcConfig");
        crate::protocol_serde::shape_vpc_config::ser_vpc_config(encoder, var_6)?;
    }
    if let Some(var_7) = &input.enable_default_internet_access {
        encoder.str("EnableDefaultInternetAccess").boolean(*var_7);
    }
    if let Some(var_8) = &input.iam_role_arn {
        encoder.str("IamRoleArn").str(var_8.as_str());
    }
    if let Some(var_9) = &input.access_endpoints {
        encoder.str("AccessEndpoints");
        encoder.array((*var_9).len());
        for item_10 in var_9 {
            {
                crate::protocol_serde::shape_access_endpoint::ser_access_endpoint(encoder, item_10)?;
            }
        }
    }
    if let Some(var_11) = &input.attributes_to_delete {
        encoder.str("AttributesToDelete");
        encoder.array((*var_11).len());
        for item_12 in var_11 {
            {
                encoder.str(item_12.as_str());
            }
        }
    }
    if let Some(var_13) = &input.disable_imdsv1 {
        encoder.str("DisableIMDSV1").boolean(*var_13);
    }
    encoder.end();
    Ok(())
}
