// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_create_directory_config_input_input(
    encoder: &mut ::aws_smithy_cbor::Encoder,
    #[allow(unused)] input: &crate::operation::create_directory_config::CreateDirectoryConfigInput,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    encoder.begin_map();
    if let Some(var_1) = &input.directory_name {
        encoder.str("DirectoryName").str(var_1.as_str());
    }
    if let Some(var_2) = &input.organizational_unit_distinguished_names {
        encoder.str("OrganizationalUnitDistinguishedNames");
        encoder.array((*var_2).len());
        for item_3 in var_2 {
            {
                encoder.str(item_3.as_str());
            }
        }
    }
    if let Some(var_4) = &input.service_account_credentials {
        encoder.str("ServiceAccountCredentials");
        crate::protocol_serde::shape_service_account_credentials::ser_service_account_credentials(encoder, var_4)?;
    }
    if let Some(var_5) = &input.certificate_based_auth_properties {
        encoder.str("CertificateBasedAuthProperties");
        crate::protocol_serde::shape_certificate_based_auth_properties::ser_certificate_based_auth_properties(encoder, var_5)?;
    }
    encoder.end();
    Ok(())
}
