// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_start_browser_session_input_input(
    object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::operation::start_browser_session::StartBrowserSessionInput,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    if let Some(var_1) = &input.certificates {
        let mut array_2 = object.key("certificates").start_array();
        for item_3 in var_1 {
            {
                #[allow(unused_mut)]
                let mut object_4 = array_2.value().start_object();
                crate::protocol_serde::shape_certificate::ser_certificate(&mut object_4, item_3)?;
                object_4.finish();
            }
        }
        array_2.finish();
    }
    if let Some(var_5) = &input.client_token {
        object.key("clientToken").string(var_5.as_str());
    }
    if let Some(var_6) = &input.enterprise_policies {
        let mut array_7 = object.key("enterprisePolicies").start_array();
        for item_8 in var_6 {
            {
                #[allow(unused_mut)]
                let mut object_9 = array_7.value().start_object();
                crate::protocol_serde::shape_browser_enterprise_policy::ser_browser_enterprise_policy(&mut object_9, item_8)?;
                object_9.finish();
            }
        }
        array_7.finish();
    }
    if let Some(var_10) = &input.extensions {
        let mut array_11 = object.key("extensions").start_array();
        for item_12 in var_10 {
            {
                #[allow(unused_mut)]
                let mut object_13 = array_11.value().start_object();
                crate::protocol_serde::shape_browser_extension::ser_browser_extension(&mut object_13, item_12)?;
                object_13.finish();
            }
        }
        array_11.finish();
    }
    if let Some(var_14) = &input.filesystem_configurations {
        let mut array_15 = object.key("filesystemConfigurations").start_array();
        for item_16 in var_14 {
            {
                #[allow(unused_mut)]
                let mut object_17 = array_15.value().start_object();
                crate::protocol_serde::shape_tools_file_system_configuration::ser_tools_file_system_configuration(&mut object_17, item_16)?;
                object_17.finish();
            }
        }
        array_15.finish();
    }
    if let Some(var_18) = &input.name {
        object.key("name").string(var_18.as_str());
    }
    if let Some(var_19) = &input.profile_configuration {
        #[allow(unused_mut)]
        let mut object_20 = object.key("profileConfiguration").start_object();
        crate::protocol_serde::shape_browser_profile_configuration::ser_browser_profile_configuration(&mut object_20, var_19)?;
        object_20.finish();
    }
    if let Some(var_21) = &input.proxy_configuration {
        #[allow(unused_mut)]
        let mut object_22 = object.key("proxyConfiguration").start_object();
        crate::protocol_serde::shape_proxy_configuration::ser_proxy_configuration(&mut object_22, var_21)?;
        object_22.finish();
    }
    if let Some(var_23) = &input.session_timeout_seconds {
        object.key("sessionTimeoutSeconds").number(
            #[allow(clippy::useless_conversion)]
            ::aws_smithy_types::Number::NegInt((*var_23).into()),
        );
    }
    if let Some(var_24) = &input.view_port {
        #[allow(unused_mut)]
        let mut object_25 = object.key("viewPort").start_object();
        crate::protocol_serde::shape_view_port::ser_view_port(&mut object_25, var_24)?;
        object_25.finish();
    }
    Ok(())
}
