// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// When writing a match expression against `ResourcesStringField`, it is important to ensure
/// your code is forward-compatible. That is, if a match arm handles a case for a
/// feature that is supported by the service but has not been represented as an enum
/// variant in a current version of SDK, your code should continue to work when you
/// upgrade SDK to a future version in which the enum does include a variant for that
/// feature.
///
/// Here is an example of how you can make a match expression forward-compatible:
///
/// ```text
/// # let resourcesstringfield = unimplemented!();
/// match resourcesstringfield {
///     ResourcesStringField::AccountId => { /* ... */ },
///     ResourcesStringField::AccountName => { /* ... */ },
///     ResourcesStringField::DiscoveryType => { /* ... */ },
///     ResourcesStringField::FindingType => { /* ... */ },
///     ResourcesStringField::ProductName => { /* ... */ },
///     ResourcesStringField::Region => { /* ... */ },
///     ResourcesStringField::ResourceCategory => { /* ... */ },
///     ResourcesStringField::ResourceCloudPartition => { /* ... */ },
///     ResourcesStringField::ResourceGuid => { /* ... */ },
///     ResourcesStringField::ResourceId => { /* ... */ },
///     ResourcesStringField::CanonicalId => { /* ... */ },
///     ResourcesStringField::HostResourceGuid => { /* ... */ },
///     ResourcesStringField::HostResourceType => { /* ... */ },
///     ResourcesStringField::ResourceName => { /* ... */ },
///     ResourcesStringField::ResourceOwnerAccountId => { /* ... */ },
///     ResourcesStringField::ResourceOwnerOrgId => { /* ... */ },
///     ResourcesStringField::ResourceProvider => { /* ... */ },
///     ResourcesStringField::ResourceRegion => { /* ... */ },
///     ResourcesStringField::ResourceSubCategory => { /* ... */ },
///     ResourcesStringField::ResourceType => { /* ... */ },
///     other @ _ if other.as_str() == "NewFeature" => { /* handles a case for `NewFeature` */ },
///     _ => { /* ... */ },
/// }
/// ```
/// The above code demonstrates that when `resourcesstringfield` represents
/// `NewFeature`, the execution path will lead to the second last match arm,
/// even though the enum does not contain a variant `ResourcesStringField::NewFeature`
/// in the current version of SDK. The reason is that the variable `other`,
/// created by the `@` operator, is bound to
/// `ResourcesStringField::Unknown(UnknownVariantValue("NewFeature".to_owned()))`
/// and calling `as_str` on it yields `"NewFeature"`.
/// This match expression is forward-compatible when executed with a newer
/// version of SDK where the variant `ResourcesStringField::NewFeature` is defined.
/// Specifically, when `resourcesstringfield` represents `NewFeature`,
/// the execution path will hit the second last match arm as before by virtue of
/// calling `as_str` on `ResourcesStringField::NewFeature` also yielding `"NewFeature"`.
///
/// Explicitly matching on the `Unknown` variant should
/// be avoided for two reasons:
/// - The inner data `UnknownVariantValue` is opaque, and no further information can be extracted.
/// - It might inadvertently shadow other intended match arms.
///
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(
    ::std::clone::Clone, ::std::cmp::Eq, ::std::cmp::Ord, ::std::cmp::PartialEq, ::std::cmp::PartialOrd, ::std::fmt::Debug, ::std::hash::Hash,
)]
pub enum ResourcesStringField {
    #[allow(missing_docs)] // documentation missing in model
    AccountId,
    #[allow(missing_docs)] // documentation missing in model
    AccountName,
    #[allow(missing_docs)] // documentation missing in model
    DiscoveryType,
    #[allow(missing_docs)] // documentation missing in model
    FindingType,
    #[allow(missing_docs)] // documentation missing in model
    ProductName,
    #[allow(missing_docs)] // documentation missing in model
    Region,
    #[allow(missing_docs)] // documentation missing in model
    ResourceCategory,
    #[allow(missing_docs)] // documentation missing in model
    ResourceCloudPartition,
    #[allow(missing_docs)] // documentation missing in model
    ResourceGuid,
    #[allow(missing_docs)] // documentation missing in model
    ResourceId,
    #[allow(missing_docs)] // documentation missing in model
    CanonicalId,
    #[allow(missing_docs)] // documentation missing in model
    HostResourceGuid,
    #[allow(missing_docs)] // documentation missing in model
    HostResourceType,
    #[allow(missing_docs)] // documentation missing in model
    ResourceName,
    #[allow(missing_docs)] // documentation missing in model
    ResourceOwnerAccountId,
    #[allow(missing_docs)] // documentation missing in model
    ResourceOwnerOrgId,
    #[allow(missing_docs)] // documentation missing in model
    ResourceProvider,
    #[allow(missing_docs)] // documentation missing in model
    ResourceRegion,
    #[allow(missing_docs)] // documentation missing in model
    ResourceSubCategory,
    #[allow(missing_docs)] // documentation missing in model
    ResourceType,
    /// `Unknown` contains new variants that have been added since this code was generated.
    #[deprecated(note = "Don't directly match on `Unknown`. See the docs on this enum for the correct way to handle unknown variants.")]
    Unknown(crate::primitives::sealed_enum_unknown::UnknownVariantValue),
}
impl ::std::convert::From<&str> for ResourcesStringField {
    fn from(s: &str) -> Self {
        match s {
            "AccountId" => ResourcesStringField::AccountId,
            "AccountName" => ResourcesStringField::AccountName,
            "DiscoveryType" => ResourcesStringField::DiscoveryType,
            "FindingsSummary.FindingType" => ResourcesStringField::FindingType,
            "FindingsSummary.ProductName" => ResourcesStringField::ProductName,
            "Region" => ResourcesStringField::Region,
            "ResourceCategory" => ResourcesStringField::ResourceCategory,
            "ResourceCloudPartition" => ResourcesStringField::ResourceCloudPartition,
            "ResourceGuid" => ResourcesStringField::ResourceGuid,
            "ResourceId" => ResourcesStringField::ResourceId,
            "ResourceInfo.AIDetails.CanonicalId" => ResourcesStringField::CanonicalId,
            "ResourceInfo.AIDetails.HostResourceGuid" => ResourcesStringField::HostResourceGuid,
            "ResourceInfo.AIDetails.HostResourceType" => ResourcesStringField::HostResourceType,
            "ResourceName" => ResourcesStringField::ResourceName,
            "ResourceOwnerAccountId" => ResourcesStringField::ResourceOwnerAccountId,
            "ResourceOwnerOrgId" => ResourcesStringField::ResourceOwnerOrgId,
            "ResourceProvider" => ResourcesStringField::ResourceProvider,
            "ResourceRegion" => ResourcesStringField::ResourceRegion,
            "ResourceSubCategory" => ResourcesStringField::ResourceSubCategory,
            "ResourceType" => ResourcesStringField::ResourceType,
            other => ResourcesStringField::Unknown(crate::primitives::sealed_enum_unknown::UnknownVariantValue(other.to_owned())),
        }
    }
}
impl ::std::str::FromStr for ResourcesStringField {
    type Err = ::std::convert::Infallible;

    fn from_str(s: &str) -> ::std::result::Result<Self, <Self as ::std::str::FromStr>::Err> {
        ::std::result::Result::Ok(ResourcesStringField::from(s))
    }
}
impl ResourcesStringField {
    /// Returns the `&str` value of the enum member.
    pub fn as_str(&self) -> &str {
        match self {
            ResourcesStringField::AccountId => "AccountId",
            ResourcesStringField::AccountName => "AccountName",
            ResourcesStringField::DiscoveryType => "DiscoveryType",
            ResourcesStringField::FindingType => "FindingsSummary.FindingType",
            ResourcesStringField::ProductName => "FindingsSummary.ProductName",
            ResourcesStringField::Region => "Region",
            ResourcesStringField::ResourceCategory => "ResourceCategory",
            ResourcesStringField::ResourceCloudPartition => "ResourceCloudPartition",
            ResourcesStringField::ResourceGuid => "ResourceGuid",
            ResourcesStringField::ResourceId => "ResourceId",
            ResourcesStringField::CanonicalId => "ResourceInfo.AIDetails.CanonicalId",
            ResourcesStringField::HostResourceGuid => "ResourceInfo.AIDetails.HostResourceGuid",
            ResourcesStringField::HostResourceType => "ResourceInfo.AIDetails.HostResourceType",
            ResourcesStringField::ResourceName => "ResourceName",
            ResourcesStringField::ResourceOwnerAccountId => "ResourceOwnerAccountId",
            ResourcesStringField::ResourceOwnerOrgId => "ResourceOwnerOrgId",
            ResourcesStringField::ResourceProvider => "ResourceProvider",
            ResourcesStringField::ResourceRegion => "ResourceRegion",
            ResourcesStringField::ResourceSubCategory => "ResourceSubCategory",
            ResourcesStringField::ResourceType => "ResourceType",
            ResourcesStringField::Unknown(value) => value.as_str(),
        }
    }
    /// Returns all the `&str` representations of the enum members.
    pub const fn values() -> &'static [&'static str] {
        &[
            "AccountId",
            "AccountName",
            "DiscoveryType",
            "FindingsSummary.FindingType",
            "FindingsSummary.ProductName",
            "Region",
            "ResourceCategory",
            "ResourceCloudPartition",
            "ResourceGuid",
            "ResourceId",
            "ResourceInfo.AIDetails.CanonicalId",
            "ResourceInfo.AIDetails.HostResourceGuid",
            "ResourceInfo.AIDetails.HostResourceType",
            "ResourceName",
            "ResourceOwnerAccountId",
            "ResourceOwnerOrgId",
            "ResourceProvider",
            "ResourceRegion",
            "ResourceSubCategory",
            "ResourceType",
        ]
    }
}
impl ::std::convert::AsRef<str> for ResourcesStringField {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}
impl ResourcesStringField {
    /// Parses the enum value while disallowing unknown variants.
    ///
    /// Unknown variants will result in an error.
    pub fn try_parse(value: &str) -> ::std::result::Result<Self, crate::error::UnknownVariantError> {
        match Self::from(value) {
            #[allow(deprecated)]
            Self::Unknown(_) => ::std::result::Result::Err(crate::error::UnknownVariantError::new(value)),
            known => Ok(known),
        }
    }
}
impl ::std::fmt::Display for ResourcesStringField {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        match self {
            ResourcesStringField::AccountId => write!(f, "AccountId"),
            ResourcesStringField::AccountName => write!(f, "AccountName"),
            ResourcesStringField::DiscoveryType => write!(f, "DiscoveryType"),
            ResourcesStringField::FindingType => write!(f, "FindingsSummary.FindingType"),
            ResourcesStringField::ProductName => write!(f, "FindingsSummary.ProductName"),
            ResourcesStringField::Region => write!(f, "Region"),
            ResourcesStringField::ResourceCategory => write!(f, "ResourceCategory"),
            ResourcesStringField::ResourceCloudPartition => write!(f, "ResourceCloudPartition"),
            ResourcesStringField::ResourceGuid => write!(f, "ResourceGuid"),
            ResourcesStringField::ResourceId => write!(f, "ResourceId"),
            ResourcesStringField::CanonicalId => write!(f, "ResourceInfo.AIDetails.CanonicalId"),
            ResourcesStringField::HostResourceGuid => write!(f, "ResourceInfo.AIDetails.HostResourceGuid"),
            ResourcesStringField::HostResourceType => write!(f, "ResourceInfo.AIDetails.HostResourceType"),
            ResourcesStringField::ResourceName => write!(f, "ResourceName"),
            ResourcesStringField::ResourceOwnerAccountId => write!(f, "ResourceOwnerAccountId"),
            ResourcesStringField::ResourceOwnerOrgId => write!(f, "ResourceOwnerOrgId"),
            ResourcesStringField::ResourceProvider => write!(f, "ResourceProvider"),
            ResourcesStringField::ResourceRegion => write!(f, "ResourceRegion"),
            ResourcesStringField::ResourceSubCategory => write!(f, "ResourceSubCategory"),
            ResourcesStringField::ResourceType => write!(f, "ResourceType"),
            ResourcesStringField::Unknown(value) => write!(f, "{value}"),
        }
    }
}
