// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>Additional details about a resource that are specific to its category. For AI/ML resources and their host resources, this structure contains <code>AIDetails</code>.</p>
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct ResourceInfo {
    /// <p>Details that are specific to self-hosted AI resources and their host resources.</p>
    pub ai_details: ::std::option::Option<crate::types::AiDetails>,
}
impl ResourceInfo {
    /// <p>Details that are specific to self-hosted AI resources and their host resources.</p>
    pub fn ai_details(&self) -> ::std::option::Option<&crate::types::AiDetails> {
        self.ai_details.as_ref()
    }
}
impl ResourceInfo {
    /// Creates a new builder-style object to manufacture [`ResourceInfo`](crate::types::ResourceInfo).
    pub fn builder() -> crate::types::builders::ResourceInfoBuilder {
        crate::types::builders::ResourceInfoBuilder::default()
    }
}

/// A builder for [`ResourceInfo`](crate::types::ResourceInfo).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct ResourceInfoBuilder {
    pub(crate) ai_details: ::std::option::Option<crate::types::AiDetails>,
}
impl ResourceInfoBuilder {
    /// <p>Details that are specific to self-hosted AI resources and their host resources.</p>
    pub fn ai_details(mut self, input: crate::types::AiDetails) -> Self {
        self.ai_details = ::std::option::Option::Some(input);
        self
    }
    /// <p>Details that are specific to self-hosted AI resources and their host resources.</p>
    pub fn set_ai_details(mut self, input: ::std::option::Option<crate::types::AiDetails>) -> Self {
        self.ai_details = input;
        self
    }
    /// <p>Details that are specific to self-hosted AI resources and their host resources.</p>
    pub fn get_ai_details(&self) -> &::std::option::Option<crate::types::AiDetails> {
        &self.ai_details
    }
    /// Consumes the builder and constructs a [`ResourceInfo`](crate::types::ResourceInfo).
    pub fn build(self) -> crate::types::ResourceInfo {
        crate::types::ResourceInfo { ai_details: self.ai_details }
    }
}
