// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_rescore_input_input(
    encoder: &mut ::aws_smithy_cbor::Encoder,
    #[allow(unused)] input: &crate::operation::rescore::RescoreInput,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    encoder.begin_map();
    if let Some(var_1) = &input.rescore_execution_plan_id {
        encoder.str("RescoreExecutionPlanId").str(var_1.as_str());
    }
    if let Some(var_2) = &input.search_query {
        encoder.str("SearchQuery").str(var_2.as_str());
    }
    if let Some(var_3) = &input.documents {
        encoder.str("Documents");
        encoder.array((*var_3).len());
        for item_4 in var_3 {
            {
                crate::protocol_serde::shape_document::ser_document(encoder, item_4)?;
            }
        }
    }
    encoder.end();
    Ok(())
}
